### ISSUE TITLE
我之前提的当物品有自定义名字，显示还是原版名字问题

### ISSUE THREAD

**Issue by mcpanglei** [Ghost-chu/QuickShop-Reremake#10]
我现在用的1.2.0，我出售一个自定义了名字的纸，纸的名字是”修复卷轴”，上架后还是会显示Paper，这个是我配置有问题吗？你之前回复说1.1.5已经加了这个功能，从哪开启呢？

**Comment by Ghost-chu** [comment]
物品名称显示是Preview Item会显示 牌子上还是本身的名字

**Comment by Ghost-chu** [comment]
added this feature in commit 122f3f88a330254914bfcfa32c3d8b9b138a8e7b
