### ISSUE TITLE
Slimefun

### ISSUE THREAD

**Issue by cheesepufftyler** [Ghost-chu/QuickShop-Reremake#100]
Im trying to make it so players can sell slimefun items. but it dont work.

**Comment by Ghost-chu** [comment]
Try /qs create

**Comment by cheesepufftyler** [comment]
Does not create a shop or do anything if i hold the slimefun item in hand and type something like /qs create 10

But when I try to create a shop buy hitting the chest with the slimefun item, i get this:
![1](https://user-images.githubusercontent.com/19861859/59155609-322d5700-8a5b-11e9-9495-489823906b48.png)

And nothing after that.

**Comment by Ghost-chu** [comment]
This error message is you can't place the block at shop position, it may some plugin cancel that, not a bug
