### ISSUE TITLE
Events not working - v2.0.0 - Commit: 9be8733

### ISSUE THREAD

**Issue by LJack2k** [Ghost-chu/QuickShop-Reremake#101]
Tested on
Version: v2.0.0
Commit: 9be8733

I tried several events to see if it works or not, but none of them are getting triggered. I tried:
ShopCreateEvent
ShopPurchaseEvent
ShopSuccessPurchaseEvent

I switched back to 1.4.4.13 and ShopCreateEvent, ShopPurchaseEvent work properly.

I know about the changes in events and that events are moved to a different location. Did something else change?

**Comment by Ghost-chu** [comment]
we will test it, thanks you reporting.

**Comment by Ghost-chu** [comment]
Can't reproduce this issue, if possible, please upload your demo addon jar.

**Comment by LJack2k** [comment]
https://github.com/oxidenetwork/OxideQSRStats-Spigot
https://github.com/oxidenetwork/OxideQSRStats-Spigot/target/OxideQSRStats-0.0.5.jar

**Comment by Ghost-chu** [comment]
[21:13:13 INFO]: [OxideQSRStats-Spigot] [DEBUG] CraftPlayer{name=Ghost_chu} created a shop
[21:13:13 INFO]: [OxideQSRStats-Spigot] [DEBUG] CraftPlayer{name=Ghost_chu} created a shop

It works

**Comment by LJack2k** [comment]
I was dumb. I forgot to update my QuickShop to the correct version. Sorry for wasting your time, and thank you for testingit.
