### ISSUE TITLE
[BUG] Memory Leak Suspect

### ISSUE THREAD

**Issue by coco0325** [Ghost-chu/QuickShop-Reremake#1027]
### Describe the bug:
Memory leak suspect.
A LinkedBlockingQueue consumes more than 1.7GB of memory.

### Screenshots:
![image](https://user-images.githubusercontent.com/22321097/120886599-62e00100-c621-11eb-845d-9f87852caeb2.png)

### Additional context:
QuickShop version: 4.0.8.3

**Comment by sandtechnology** [comment]
We are investigating this problem, look like is the task does not executed correctly, how about enable  `use-global-virtual-item-queue` ?

**Comment by coco0325** [comment]
I saw some commits related to this problem. Did they fix it?
05eeb9e4f5075c1fc829b562ceb9fbacc37629ee
9d0ba4086b24e8581d823d7fd2e66ff75cd953cb

**Comment by coco0325** [comment]
> We are investigating this problem, look like is the task does not executed correctly, how about enable `use-global-virtual-item-queue` ?

Thank you, I will try that.

**Comment by sandtechnology** [comment]
> I saw some commits related to this problem. Did they fix it?
> [05eeb9e](https://github.com/Ghost-chu/QuickShop-Reremake/commit/05eeb9e4f5075c1fc829b562ceb9fbacc37629ee)
> [9d0ba40](https://github.com/Ghost-chu/QuickShop-Reremake/commit/9d0ba4086b24e8581d823d7fd2e66ff75cd953cb)

Not sure, we just fixing the container shop  memory leak in those commit.

**Comment by sandtechnology** [comment]
Try to update to 4.0.8.4 and see if it still happening https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-multi-currency.62575/download?version=401780

**Comment by sandtechnology** [comment]
Feel free to reopen this issue if you still meeting this problem in 4.0.8.6
