### ISSUE TITLE
Some tweaks

### ISSUE THREAD

**Issue by Ghost-chu** [Ghost-chu/QuickShop-Reremake#103]
* [ ] Move all Procedure Oriented codes to Object Oriented.
* [ ] Write adapter for configuration, make sure only configuration can direct access the original config.
* [x] Move the duplicate code part to standalone method.
* [x] Move some Utils out of Util.class
* [x] Simplify project codes

**Comment by Vlvxingze** [comment]
Well,it is my first time to see this..
Is this mission list?
If I done one,and I should mark it?

**Comment by Ghost-chu** [comment]
> Well,it is my first time to see this..
> Is this mission list?
> If I done one,and I should mark it?

Yes if you complete it.
