### ISSUE TITLE
[BUG] Unable to Get API

### ISSUE THREAD

**Issue by coco0325** [Ghost-chu/QuickShop-Reremake#1035]
### Describe the bug:
Other plugins are unable to get QuickShopAPI in Tuinity version newer than 230. (NullPointerException)

**Comment by sandtechnology** [comment]
Please provide the error

**Comment by coco0325** [comment]
No other error, only get NullPointerException when calling QuickShopAPI.getShopAPI().getShop(b.getLocation()).isPresent().

**Comment by sandtechnology** [comment]
So what is your stacktrace?

**Comment by sandtechnology** [comment]
Also I think it should be the problem for Tuinity, please contact them.

**Comment by Ghost-chu** [comment]
we need stacktrace to track this issue, please upload it

**Comment by coco0325** [comment]
Problem fixed. (Maven compiled QuickShop in the other plugin.)
