### ISSUE TITLE
[BUG] MysqlPlayerDataBridge Offline Support Broken When Buying All Stock

### ISSUE THREAD

**Issue by coco0325** [Ghost-chu/QuickShop-Reremake#1048]
### Describe the bug:
When a player buying all (More specific, enter 'all' when buying) stock in a shop, MysqlPlayerDataBridge won't give shop owner money when joining the server.

No stacktrace.
Quickshop version: 4.0.8.6
Tuinity 1.16.5

**Comment by sandtechnology** [comment]
It's MysqlPlayerDataBridge bug, please report to them.

**Comment by coco0325** [comment]
Is there a option to disable buy all function?

**Comment by sandtechnology** [comment]
We handling buy "all" just like other inputting number way, and there is no way to disable it, also I think it should be MPDB issue anyway.
