### ISSUE TITLE
armor stands go missing if two shops selling/buying the same thing across from each other

### ISSUE THREAD

**Issue by deadman96385** [Ghost-chu/QuickShop-Reremake#105]
So we have a spawn shop that you can buy and sell wood at, there is one side that sells the wood and one side that buys the wood. When quick shop is manually reloaded one side is proper and there is none on the other side but then like 10-30 seconds after that they go in a random order of some being on one side and some on the other side. We have the display item option set to armor stands instead of drops.

![2019-06-09_17 01 32](https://user-images.githubusercontent.com/2042793/59164927-5465ba00-8ad9-11e9-8763-6c3ec9726b84.png)
![2019-06-09_17 09 11](https://user-images.githubusercontent.com/2042793/59164928-5465ba00-8ad9-11e9-85e5-2786918dc5bb.png)

**Comment by Ghost-chu** [comment]
Already fixed in #958 builds
