### ISSUE TITLE
[BUG] Plugin doesn't create tables 

### ISSUE THREAD

**Issue by KeyAs99** [Ghost-chu/QuickShop-Reremake#1058]
HI

I just downloaded quickshop for my server 1.16.5 and I don't know why the plugin doensn't create the tables in my database "shops".

My Config: https://pastebin.com/g39ppWgC
Error in console:  https://prnt.sc/14xzljs

**Comment by sandtechnology** [comment]
Please provide the FULL log when quickshop loading, also the database software information (which version? what database you are using?)

**Comment by sandtechnology** [comment]
Also you need to create database manually, this may be the problem.

**Comment by Ghost-chu** [comment]
This issue closed because no paste provided
