### ISSUE TITLE
[BUG] Failed to update game assets from MojangAPI server because the language code en_ not supported by Minecraft.

### ISSUE THREAD

**Issue by Noneatme** [Ghost-chu/QuickShop-Reremake#1059]
### Describe the bug:
When the plugin loads, it fails to query game assets from the MojangAPI because it tries to load the assets with the language code '_en', but this language code is not set in the config file. Apparently it loads the wrong language code.

### To Reproduce:
- Use Ubuntu 20.04 (server), install Java 16 from [this ppa](https://launchpad.net/~linuxuprising/+archive/ubuntu/java)
- Install latest Spigot with the plugins listed below
- Install the QuickShop plugin, start the server, stop the server
- Edit the config file to add your database login data, do not modify any language code settings.
- Save the config and start the server

### Expected behavior:
- No warnings in the console window.
- The plugin should load the data from the MojangAPI with the correct language code: 'en-US'

### Screenshots:
Errros:
https://mclo.gs/mnLetUf

### Paste link:
https://pastebin.com/1sGcEirq

### Additional context:
Thanks for looking into this. I suggest the failed transaction error results from the missing game assets not being loaded or something.

**Comment by sandtechnology** [comment]
A work around is setting `game-language` to correct language, but for English you can safe to ignore it (Default to en).

**Comment by Noneatme** [comment]
> 
> 
> A work around is setting `game-language` to correct language, but for English you can safe to ignore it (Default to en).

Yeah, setting game-language: en-US will work as a workaround, thanks!
Yet I think it is still a bug that it doesn't work out-of-the-box with the default config file.
