### ISSUE TITLE
Reserve Support

### ISSUE THREAD

**Issue by creatorfromhell** [Ghost-chu/QuickShop-Reremake#107]
I am the developer of the plugin Reserve, a modern economy API with modern economy features in mind. As I am now ready to publicly push the API, I'm currently looking for developers to add support for it.

Link: https://github.com/TheNewEconomy/Reserve

Advantages over Vault:
- Multi-currency support
- Async support using Java's completeable futures
- Optional Extended API to allow third party plugins to add new currencies

Current Plugins that support Reserve:
- Towny
- ChestShop3
- MineBay

Current Providers/Planned Providers:
- The New Economy
- Towny Eco

Thanks in advance,
creatorfromhell

**Comment by Ghost-chu** [comment]
temporarily won't will add this support.
i think Vault is enough and this plugin no friendly javadoc.
many reasons, this support will delay.

**Comment by creatorfromhell** [comment]
> temporarily won't will add this support.
> i think Vault is enough and this plugin no friendly javadoc.
> many reasons, this support will delay.

Which javadocs are missing? The api files are loaded with javadocs?

**Comment by Ghost-chu** [comment]
Reserve should have a demo to let us know how use that and how process the data.
But it looks like only give an Interface for demo.

**Comment by creatorfromhell** [comment]
> Reserve should have a demo to let us know how use that and how process the data.
> But it looks like only give an Interface for demo.

That's what javadocs are for, is to explain the method is used for an what each parameter does. Each method in the API documents not only what the method does, but what each parameter does, and what the return value means.
