### ISSUE TITLE
No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry.

### ISSUE THREAD

**Issue by kaniesha** [Ghost-chu/QuickShop-Reremake#108]
Hello QuickShop devs, I'm not sure if this is something I need to be worried about. Is it something I need to configure?

https://gist.github.com/kaniesha/242af3c33613df6817867cf87f7a0646

Also sorry for not replying regarding my last issue, I had to wait for the server owner to update spigot and then the error I was seeing before did go away.

**Comment by Ghost-chu** [comment]
No, you didn't need, ignore that
