### ISSUE TITLE
air block ober chest, flowting items not loading.

### ISSUE THREAD

**Issue by vox4455** [Ghost-chu/QuickShop-Reremake#109]
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -76#-4 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -76#-8 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -77#-5 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -78#-6 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -77#-6 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -79#-4 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -77#-7 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -75#-8 was unloaded, searching the shops...
[Wed, 12. Jun 2019 00:58:23 UTC INFO] [DEBUG] [org.maxgamer.quickshop.Listeners.ChunkListener] [onChunkUnload] (48) Chunk -79#-6 was unloaded, searching the shops...

**Comment by vox4455** [comment]
Figured out the shop holograms dont load unless there are two full air blocks above. otherwise the shop loads but the hologram dose not and then spams console with debug  stuff.

just running cmi and quickshop. both are up to date.

please advise,

**Comment by Ghost-chu** [comment]
sorry, im in hospital, you issue may need waiting somedays to reply.

**Comment by vox4455** [comment]
Get well soon!

**Comment by Ghost-chu** [comment]
can you test the latest snapshot?

**Comment by Ghost-chu** [comment]
already fixed in latest snapshot
