### ISSUE TITLE
预览商品时，存在ItemFlag的未做相应处理

### ISSUE THREAD

**Issue by mcpanglei** [Ghost-chu/QuickShop-Reremake#11]
当出售商品带有ItemFlag.HIDE_ATTRIBUTES, ItemFlag.HIDE_ENCHANTS, ItemFlag.HIDE_UNBREAKABLE 这些ItemFlag时，预览商品里希望做相应处理，比如一件物品有附魔，但是加了ItemFlag.HIDE_ENCHANTS，希望在预览里不要显示相关附魔信息。

**Comment by Ghost-chu** [comment]
感谢建议，因为这是手动获取物品属性(not NMS)，所以当时并未考虑到这个情况。
下一步会判断ItemTag或者使用NMS获取物品信息

**Comment by langwan** [comment]
1.13.1 物品、书都可以 书可以看到附魔内容 但是再生药水 就显示成 药水 这就麻烦了


potioni18n:
  AWKWARD: 粗制的药水
  EMPTY: 不可合成的药水
  FIRE_RESISTANCE: 抗火药水
  HARMING: 伤害药水
  HEALING: 治疗药水
  INVISIBILITY: 隐身药水
  LEAPING: 跳跃药水
  LEVITATION: 飘浮药水
  LUCK: 幸运药水
  MUNDANE: 平凡的药水
  NIGHT_VISION: 夜视药水
  POISON: 剧毒药水
  REGENERATION: 再生药水
  SLOW_FALLING: 缓降药水
  SLOWNESS: 迟缓药水
  STRENGTH: 力量药水
  SWIFTNESS: 迅捷药水
  THICK: 浓稠的药水
  TURTLE_MASTER: 神龟药水
  WATER: 水瓶
  WATER_BREATHING: 水肺药水
  WEAKNESS: 虚弱药水

**Comment by langwan** [comment]
对啦 还有一个问题 东西南北四个方向 三个方向正确 有一个方向总是错的 我是说牌子不正对着我

**Comment by Ghost-chu** [comment]
Added in Reremake-1.2.6(Advanced Item Preview)
