### ISSUE TITLE
[BUG] QuickShop doesn't create tables, my config is good

### ISSUE THREAD

**Issue by KeyAs99** [Ghost-chu/QuickShop-Reremake#1113]
Hi, QuickShop can't create tables on my database. I have created my database but it doesnt work.
I can't paste here qs logs because the plugin is crashed and it doesn't load.

But I have an screenshot of my console.
![image](https://user-images.githubusercontent.com/20386409/121808304-136c8700-cc58-11eb-8bf3-1019a2464e78.png)

**Comment by KeyAs99** [comment]
![image](https://user-images.githubusercontent.com/20386409/121808325-2ed79200-cc58-11eb-9bef-1841e826e537.png)
![image](https://user-images.githubusercontent.com/20386409/121808332-35660980-cc58-11eb-9f2c-98fac552c018.png)

**Comment by sandtechnology** [comment]
Please provide the full login when loading plugin

**Comment by KeyAs99** [comment]
Ok
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/6643910/latest.log)

**Comment by KeyAs99** [comment]
Im Using Java 16

**Comment by sandtechnology** [comment]
Could you provide the information for your database?

**Comment by KeyAs99** [comment]
Im Using phpmyadmin, this is my localhost config
![image](https://user-images.githubusercontent.com/20386409/121808634-b8d42a80-cc59-11eb-9d21-bbd50f4510a3.png)

user root config:
![image](https://user-images.githubusercontent.com/20386409/121808648-d3a69f00-cc59-11eb-9c15-b9ae0abafb49.png)

mysql working good
![image](https://user-images.githubusercontent.com/20386409/121808660-e0c38e00-cc59-11eb-8c44-e0d74de3dd47.png)

**Comment by KeyAs99** [comment]
![image](https://user-images.githubusercontent.com/20386409/121808687-094b8800-cc5a-11eb-9399-2f3a27af46c9.png)
Database Empty

**Comment by KeyAs99** [comment]
Im using other plugins like luckperms that are working good in my database

**Comment by Ghost-chu** [comment]
Please provide paste: /qs paste

**Comment by KeyAs99** [comment]
I said that it doesnt work because plugins is crashed ... :(

**Comment by Ghost-chu** [comment]
please upload whole config.yml file

**Comment by KeyAs99** [comment]
[config.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/6643929/config.zip)

**Comment by Ghost-chu** [comment]
try set `dev-mode` to `true` and restart the server to check any new things in console.
(you may need re-upload new server logs)

**Comment by KeyAs99** [comment]
Done

New latest log: 
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/6643939/latest.log)

**Comment by Ghost-chu** [comment]
Please stand by, we're checking our code and trying to reproduce.

**Comment by Ghost-chu** [comment]
Bug confirmed, MySQL connection timed out on my Test Server.
Issue priority changed to Major.
@sandtechnology

**Comment by KeyAs99** [comment]
Yeah, I got the same bug
I'll be waiting the update

**Comment by Ghost-chu** [comment]
[2021-06-13-1.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/6643970/2021-06-13-1.zip)
Please check this log is same with you.

**Comment by KeyAs99** [comment]
No, mi server doesn't stop just appears a infinite loop in my console, but the game works good

**Comment by KeyAs99** [comment]
I thought that the problem could be due to mysql connections and I checked it and it doesn't the error

**Comment by Ghost-chu** [comment]
We noticed QuickShop will auto-reconnect when connecting failed and it won't stop actually.
Try this snapshot https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/lastSuccessfulBuild/artifact/target/QuickShop.jar
We set max tried 3 times and you should see error messages.

**Comment by KeyAs99** [comment]
Im getting same error and tables aren't created, database still emty
![image](https://user-images.githubusercontent.com/20386409/121810381-f7211800-cc60-11eb-9265-5904cf60b1ff.png)
![Uploading image.png…]()
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/6644023/latest.log)

**Comment by KeyAs99** [comment]
I checked my mysql log and I saw this error:
2021-06-13 16:04:25 114 [Warning] Aborted connection 114 to db: 'survival' user: 'root' host: 'localhost' (Got an error reading communication packets)
2021-06-13 16:04:25 112 [Warning] Aborted connection 112 to db: 'quickshop' user: 'root' host: 'localhost' (Got an error reading communication packets)
2021-06-13 16:04:25 111 [Warning] Aborted connection 111 to db: 'quickshop' user: 'root' host: 'localhost' (Got an error reading communication packets)

**Comment by Ghost-chu** [comment]
Could you try connect database with IPV6?
```yaml
host: '[::1]'
```

**Comment by KeyAs99** [comment]
Same error :(

**Comment by Ghost-chu** [comment]
I had no idea because it works for me.

**Comment by Ghost-chu** [comment]
I guess there something wrong with database or JDBC driver

**Comment by KeyAs99** [comment]
PHPMyadmin
what are you using?

**Comment by Ghost-chu** [comment]
PHPMyAdmin with MySQL5.7.26

**Comment by Ghost-chu** [comment]
Could you upload new server logs with new QuickShop snapshot?

**Comment by Ghost-chu** [comment]
also if you want, join our discord support server: https://discord.gg/bfefw2E

**Comment by KeyAs99** [comment]
Yes, but I don't know why it doesnt work luckperms, minepacks, jobs reloaded are working good with my database
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/6644037/latest.log)

**Comment by KeyAs99** [comment]
Maybe can you give me all tables to test it?

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/blob/master/src/main/java/org/maxgamer/quickshop/database/DatabaseHelper.java
Need to sleep, so please contact @sandtechnology to continue to get supports
