### ISSUE TITLE
error occurred when enabling

### ISSUE THREAD

**Issue by MaddiHunt** [Ghost-chu/QuickShop-Reremake#112]
in loading the server, i get an error stating "Error occurred while enabling Quickshop vReremake 1.4.4.13 (is it out of date?)

![image](https://user-images.githubusercontent.com/51791849/59474153-cc065280-8e13-11e9-88fe-ee443332e710.png)

**Comment by Ghost-chu** [comment]
Please paste full error logs

**Comment by MaddiHunt** [comment]
![image](https://user-images.githubusercontent.com/51791849/59479453-134c0d80-8e2b-11e9-876e-b173c3d951d3.png)

here you go!

**Comment by Ghost-chu** [comment]
1.x life crycle is ended, nolonger accept 1.x issue feedback.

**Comment by MaddiHunt** [comment]
ServerMiner says the plugin is up to date, do you have any idea how I could update to 2.x without losing all my shops?

![image](https://user-images.githubusercontent.com/51791849/59510167-078b3600-8e81-11e9-8994-07c4ae1a40ba.png)
