### ISSUE TITLE
API bug 

### ISSUE THREAD

**Issue by iSkyify** [Ghost-chu/QuickShop-Reremake#113]
Using jetshoppers plugin,  if an icon is floating:
" InventoryPreview.isPreviewItem(item); " does not work it is picking up floating icons 

https://www.spigotmc.org/resources/jetshoppers-gui-stats-suction-filter-link-holograms-1-8-1-14-support.67298/

**Comment by Jet315** [comment]
Seems to be InventoryPreview.isPreviewItem(item) is returning false, despite it being a preview icon?

**Comment by Ghost-chu** [comment]
DisplayItem.checkIsGuardItem(ItemStack)
