### ISSUE TITLE
[Feature] Add light support (light-block) and glowing text on sign

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#1155]
### Describe the Feature:
With 1.17 adding the light block does there seem to be a way to apply light without the need of packet manipulation anymore (At least I think that's the case), so perhaps having an option to put a light block (with pre-configured light intensity) above the shop chest could be an idea.

The next thing would be an option to have the signs display their text with a glow. This is yet again a 1.17 feature but I believe it could be a good one to have.

**Comment by Ghost-chu** [comment]
Sounds Great, It would be awesome

**Comment by Ghost-chu** [comment]
The Light block on the chest looks strange, it should place manually.
