### ISSUE TITLE
old shop dont work

### ISSUE THREAD

**Issue by ABKgamer** [Ghost-chu/QuickShop-Reremake#117]
shop that is made in old version dont work you have to remake the shop

**Comment by ABKgamer** [comment]
and config getting reset

**Comment by Ghost-chu** [comment]
Any errors in console?

**Comment by ABKgamer** [comment]
weirdly no error

**Comment by ABKgamer** [comment]
i was on 2.0.4

**Comment by ABKgamer** [comment]
if i try to change price it says to shop found

**Comment by Ghost-chu** [comment]
Update to latest version before report the bug

**Comment by Ghost-chu** [comment]
This issue will closed.
Create new one after you up-to-date both of Spigot, QuickShop and give me an link for QS Paste

**Comment by ABKgamer** [comment]
https://paste.ubuntu.com/p/CP6jX9TxZD/
