### ISSUE TITLE
Item display on signs [feature request]

### ISSUE THREAD

**Issue by korhox** [Ghost-chu/QuickShop-Reremake#120]
Hi!

It would be nice addition, if display items would spawn on chests, where is sign like in picture shown below.

Example of this feature can be viewed in middle chests. It is visible now, because the shop abowe was just made.

![image](https://user-images.githubusercontent.com/10478812/59649508-a5d21100-918b-11e9-8c77-c4652b5067d8.png)

**Comment by Ghost-chu** [comment]
Done
