### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chypik** [Ghost-chu/QuickShop-Reremake#1264]
### Describe the bug:
[QuickShop] Virtual DisplayItem Support Test: Failed to initialize VirtualDisplayItem

### To Reproduce:
starting a clean server without players
Paper version git-Paper-90 (MC: 1.17.1)
QuickShop v4.0.9.4  (Build #97)

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- 【https://pastebin.com/xpiNgJ82】

### Additional context:
latest.log.
https://pastebin.com/57U8mK7i

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1402/
How about this build?
