### ISSUE TITLE
doesn't work after server restart

### ISSUE THREAD

**Issue by AydenWasTaken** [Ghost-chu/QuickShop-Reremake#127]
As said, the plugin stops working after a restart. When added to the plugins folder for the first time and then start the server, it works. After shutting the server down and starting it again (either through a restart or turning it off, then on manually) it stops. The message in the server console says that it did not find an economy plugin. I have tested both vault (v1.7.2-b107) and AConomy (Version 2.2) work without a problem.

**Comment by Ghost-chu** [comment]
Try latest release

**Comment by BluePhoenixGame** [comment]
I had those both plugins before. I was even able to use reload.

**Comment by Ghost-chu** [comment]
Long time no more response, issue closed
