### ISSUE TITLE
[Minor Bug]

### ISSUE THREAD

**Issue by KeyAs99** [Ghost-chu/QuickShop-Reremake#1280]
Hi, maybe this is not a quickshop bug

I'm using this plugin to delete shops: https://www.spigotmc.org/resources/advancedregionmarket-shop-bridge.77484/
but holograms are still appearing on the ground.
![image](https://user-images.githubusercontent.com/20386409/125178477-8defde80-e1e5-11eb-9c1c-e131532d9a50.png)

**Comment by sandtechnology** [comment]
Are you using the latest version of Quickshop? Please provide the paste by /qs paste.

**Comment by KeyAs99** [comment]
https://paste.ubuntu.com/p/NsyWsSSJZD/

**Comment by KeyAs99** [comment]
That's happens only in enchanted items

**Comment by Ghost-chu** [comment]
can reproduce that with real displayitem



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 11, 2021 21:26 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Ghost-chu/QuickShop-Reremake] [Minor Bug] (#1280)




 
That's happens only in enchanted items

**Comment by KeyAs99** [comment]
The owner of that plugin answered me:

![image](https://user-images.githubusercontent.com/20386409/125354562-3b88fc00-e364-11eb-8366-b96578059b61.png)
