### ISSUE TITLE
Causes Server Crash in 1.14.3

### ISSUE THREAD

**Issue by SirEraz** [Ghost-chu/QuickShop-Reremake#129]
After trying to create a shop in Spigot 1.14.3, my server crashed. I tested a few times to ensure it was Quickshop, and even after uninstalling other potential issue plugins, it continued to cause a crash upon creating a shop. I'm not sure if this is due to simply a large amount of lag, similar to another posted issue, or a separate issue entirely.

For more context, the item I attempted to create a shop with was an emerald. I punched the chest, the prompt appeared, and I typed "1". All appeared to be working for about 5 seconds, as a sign appeared, but then the server crashed. The other plugins I have installed are: CoreProtect, LuckPerms, BukkitCore, WorldEdit, Vault, WorldGuard, ProtocolLib, Multiverse-Core, Essentials, PerWorldInventory, QuickShop, SimplePortals, and EssentialsSpawn.

**Comment by iSkyify** [comment]
Glad I disabled it and didn't experience that issue. REALLY hoping he jumps on this to fix.

**Comment by Ghost-chu** [comment]
Thanks for reporting, please give me the crash-reports, logs, and link of /qs paste

**Comment by Ghost-chu** [comment]
This issue was closed cause can't reproduce.

QSRR already have 354 server running under 1.14.3, so this issue was closed.
