### ISSUE TITLE
chest shop not requiring money to purchase

### ISSUE THREAD

**Issue by Kenton126** [Ghost-chu/QuickShop-Reremake#130]
On my minecraft server i am selling spawners with the is plugin and it is not taking money from the player. I am using EssentialsX and the chest shop is a admin shop.

**Comment by Ghost-chu** [comment]
You can sell items to you created shop, you won't get any money.

**Comment by Kenton126** [comment]
The player will be purchasing the item for 200000 but they get the item without losing any money

**Comment by Ghost-chu** [comment]
Make sure your.economy system correctly process the withdraw, everythings fine on my test server

**Comment by Ghost-chu** [comment]
Rewrited purchase part, update and try again.
