### ISSUE TITLE
Chestshop does not prevent hopper minecart

### ISSUE THREAD

**Issue by ray040417** [Ghost-chu/QuickShop-Reremake#131]
When you place a hopper minecart under a chestshop, it will steal the item in the chest, here is my config:
protect:
  minecart: true
  entity: true
  redstone: true
  structuregrow: true
  explode: true
  hopper: true
Using version 2.1.2

**Comment by ray040417** [comment]
![image](https://user-images.githubusercontent.com/21973258/60455127-45b38400-9bfb-11e9-8ddd-8228b99de97a.png)


![image](https://user-images.githubusercontent.com/21973258/60455109-37656800-9bfb-11e9-8571-4b83028d0b80.png)

**Comment by Ghost-chu** [comment]
Could you turn on debug mode(/qs debug) and try again?
You should will see alert in console, reply me the result.

and paste (/qs paste)

**Comment by Ghost-chu** [comment]
Test the snapshot in Discord

**Comment by Ghost-chu** [comment]
Fixed in latest release, but not tested
