### ISSUE TITLE
I put Vault in the folder "plugins", but QS showed me that I didn't have a economy plugin.

### ISSUE THREAD

**Issue by Cyrilic1209** [Ghost-chu/QuickShop-Reremake#1343]
Log:
[10:52:43] [Server thread/ERROR]: [QuickShop] No Economy plugin detected! Please make sure that you have a
[10:52:43] [Server thread/ERROR]: [QuickShop] compatible economy plugin installed to get Vault working.

the version of Vault is 1.7.3, and the version of QS is 4.0.9.7.

When I start/reload my server or execute cmds ("/qs ...") , it always shows that message. 

Was there a little bug in the code? or were there some mistakes in my operations?

what should i do?

**Comment by sandtechnology** [comment]
Vault is a "bridge" for economy plugin, not an economy plugin, please install an economy plugin and try again

**Comment by Cyrilic1209** [comment]
Ok! Thank you
