### ISSUE TITLE
Ver 2.2.4 Kick

### ISSUE THREAD

**Issue by kena73** [Ghost-chu/QuickShop-Reremake#135]
Ver 2.2.4 proceeds to kick users when attempting to buy items from a shop without any errors or messages in the console, not much else to add to it.

**Comment by Ghost-chu** [comment]
Can you execute command /qs debug and buy/sell again, then execute command /qs paste?

**Comment by kena73** [comment]
Here's the paste but sadly I wasn't able to get the bug to happen again
https://paste.ubuntu.com/p/Y3kwX8fSHB/
