### ISSUE TITLE
ClearLagg removes holograms

### ISSUE THREAD

**Issue by donut4490** [Ghost-chu/QuickShop-Reremake#136]
Not sure if this is a bug or a feature request, but ClearLagg will remove the holograms above the chest. I know some of the other plugins have a feature to prevent this, does QuickShop have one? Perfect plugin otherwise.

**Comment by Ghost-chu** [comment]
ClearLagg no api or events can let us cancel they remove us items.

I not clear about ClearLagg config, but i remember they have fillter to control what item shouldn't be removed.

These marks may can help you.

Set prevent items contains `QuickShop DisplayItem` on their lores.
Set prevent items contains `QuickShop DisplayItem` on their display-name.
