### ISSUE TITLE
Unable to create shop with ItemsAdder blocks

### ISSUE THREAD

**Issue by donut4490** [Ghost-chu/QuickShop-Reremake#137]
When attempting to create a shop with a custom block made with the plugin ItemsAdder, the block replaces the chest. Non-block items like food work fine though.

**Comment by Ghost-chu** [comment]
Try /qs create command

**Comment by donut4490** [comment]
When using the command, the chest turns into the block. I can provide a
video if you want.

**Comment by Ghost-chu** [comment]
hmmm, it looks is protection checks issue,  i will try fix in next version.

**Comment by donut4490** [comment]
Awesome, thanks! Definitely staying with this plugin.

Sent from Mail for Windows 10

**Comment by Ghost-chu** [comment]
fixed

**Comment by donut4490** [comment]
Just updated, still has problem,

**Comment by Ghost-chu** [comment]
I didn't have ItemAdder, so i can't test it

**Comment by donut4490** [comment]
I can probably get you a copy

Sent from Mail for Windows 10

**Comment by Ghost-chu** [comment]
This already fixed, please update.

**Comment by donut4490** [comment]
Works perfectly now. Thanks so much!
