### ISSUE TITLE
"Use SQLite" Warning does not check if SQLite is already being used

### ISSUE THREAD

**Issue by mctom987** [Ghost-chu/QuickShop-Reremake#138]
The performance check for using a database can throw this exception when using the local SQLite configuration.

https://github.com/Ghost-chu/QuickShop-Reremake/blob/ad28fe67151ade962f47f061e1b07659af511b60/src/main/java/org/maxgamer/quickshop/Database/DatabaseManager.java#L83

**Comment by Ghost-chu** [comment]
Thanks advice, it will changes in next version
:)
