### ISSUE TITLE
The economy does not detect the plugin.

### ISSUE THREAD

**Issue by OverBrave** [Ghost-chu/QuickShop-Reremake#140]
I use justessentials plugin but not detect economy feature. Please fix this?

**Comment by Ghost-chu** [comment]
Test passed use EssEconomy system.

**Comment by OverBrave** [comment]
not essentials economy Just essentials plugin this another plugin... 

I use JustEssentials plugin and its have economy features. But chestshop not deteceh economy plugin. Please add this justessentials economy features on the dev build. How fast , good for me.

If you need Here, this is how JEssentials hooks into Vault: https://github.com/bluecreeper111/JEssentials/blob/master/src/com/bluecreeper111/jessentials/api/VaultHook.java
And this is how the economy is implemented: https://github.com/bluecreeper111/JEssentials/blob/master/src/com/bluecreeper111/jessentials/api/JEconomy.java

**Comment by Ghost-chu** [comment]
Fixed, avaliable in next version.
