### ISSUE TITLE
[BUG] When i create a shop with a custom item it deletes automatically with error

### ISSUE THREAD

**Issue by EarlyGamer45** [Ghost-chu/QuickShop-Reremake#1406]
### To Reproduce:
1. Go to 'Use an item with custom symbols'
2. Create a shop
3. Insert the sell price

### Expected behavior:
When i create a shop with a custom symbol it gives an error.
Error paste: https://pastebin.com/Xj3w9BwR
See video above.
### Screenshots:

Video: https://youtu.be/vbN8FhUGkg4

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- 【https://mega.nz/file/FT5kCahJ】
-  [ AtzXdW1WYF91t2dEYFBmz5_7iJg5zG1FfXCUSmmfGTI ]
### Additional context:
Leave this section body empty if no additional context provided.

**Comment by Ghost-chu** [comment]
Not quickshop issue, you might want ask for help to de.codingair.tradesystem author.

**Comment by EarlyGamer45** [comment]
I realized now that I gave you the wrong link of the plugin error, sorry!
Here's the error when i create a shop with the custom item.
https://pastebin.com/FMMgnhHC

**Comment by sandtechnology** [comment]
Please enable `auto-fix-encoding-issue-in-database` in config.yml, is the encoding issue

**Comment by EarlyGamer45** [comment]
not working

**Comment by sandtechnology** [comment]
Could you test it with this version?  (QuickShop-4.0.9.7-SNAPSHOT.jar) https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1516/

**Comment by EarlyGamer45** [comment]
Now it works fine.
The bug as been fixed, thanks for the support.

**Comment by sandtechnology** [comment]
https://www.spigotmc.org/resources/quickshop-reremake-1-17-ready-multi-currency.62575/download?version=414310
