### ISSUE TITLE
Suggestion : Ability to use special ascii caracter for currency

### ISSUE THREAD

**Issue by NoKiSenpai** [Ghost-chu/QuickShop-Reremake#143]
Hello hello ! 

I would like to use "&b♦" for my currency but QS doesn't accept.

Is it possible to add use of these symbols? (and color directly in config.yml)

Like 
`alternate-currency-symbol: '&b♦'`
instead of
`alternate-currency-symbol: $`

Thanks :D

**Comment by Ghost-chu** [comment]
It controled by Economy plugin by default.
If you custom it in QS, you need enable force quickshop format.

**Comment by Ghost-chu** [comment]
Set `disable-vault-format` to true.
Let quickshop use qs-self format

**Comment by NoKiSenpai** [comment]
It works nice ! Thanks ! :)

But how can I display my currency AFTER amount?

Like
`230 ♦`
instead of
`♦ 230`

Please?

**Comment by Ghost-chu** [comment]
No you can't
This feature only exist for solve other stupid economy plugin not include format and throw error issue.

It only will call after failed format by Vault.
Now you force turn on it.

So you shouldn't have too high except for this feature.

**Comment by NoKiSenpai** [comment]
It's ok, thanks ! :)
