### ISSUE TITLE
[BUG] All shops disappeared

### ISSUE THREAD

**Issue by Bloodlex** [Ghost-chu/QuickShop-Reremake#1435]
### Describe the bug:
After server restart all of shops disappeared, this means there is a sign, but no shops are detected there.
I can see a message in a console like on the attached pastebin in additional context.
Please help.

### To Reproduce:
1. Install the newest version
2. Restart the server
3. All shops disappear

### Expected behavior:
Shops should work like before the restart.

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- [https://pastebin.com/PHxC0dwT](https://pastebin.com/PHxC0dwT)

### Additional context:
Console log
[https://pastebin.com/tBfXmUJv)](https://pastebin.com/tBfXmUJv)

Other plugins:
Plugins (65): ActionHealth, AdvancedChests, AdvancedLogger*, AdvancedRegionMarket, AntiVPN, AntiWorldFly, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterHeads, ChestSort, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, dynmap, Dynmap-WorldGuard*, EasyCarts, Epidemic, Essentials, EssentialsChat, ExcellentEnchants, GSit, Harbor, HolographicDisplays, Images, Jobs, KeepChunks, LangUtils, LogBlock, LuckPerms, LWC, LWCTrust, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, PetMaster, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, QuickShopList, RegionRaid, SkinsRestorer, Spartan, StackMob, SuperVanish, TAB, TitleManager, TreeAssist, Vault, Vehicles, VehiclesFlags, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by sandtechnology** [comment]
> You can try force load this ItemStack by our hacked ItemStack read util(shop.force-load-downgrade-items), but beware, the data may damaged if you load on this lower Minecraft server version, Please backup your world and database before enable!
Please enable `force-load-downgrade-items` in config.yml, you are loading shops in the new Minecraft version and then load them in older version, causing shop load failed.
