### ISSUE TITLE
High TPS on 1.14.3 Server

### ISSUE THREAD

**Issue by EnderGamingFilms** [Ghost-chu/QuickShop-Reremake#144]
So I was trying to reduce lag on my server and noticed that QuickShop is using a large amount... Is there anyway to lower the amount of lag I am getting?

https://imgur.com/5BTYHUY

**Comment by Ghost-chu** [comment]
Known issue, it looks terrible im 1.14.x version.
We are trying optimize the plugin for that, thanks for reporting
