### ISSUE TITLE
Permissions broken? [BUG] [1.14.3]

### ISSUE THREAD

**Issue by cloakfox** [Ghost-chu/QuickShop-Reremake#145]
**Describe the bug**
My players are unable to create any shops on Paper 1.14.3 using latest quickshops plugin (version 2.2.10)

The weird thing is that I can still create/use shops on my own account that has OP. I've double checked the permissions for default players and everything looks good and should be working.

The weird thing is that players do not get any messages ingame that they don't have permissions to create or use shops. It just doensn't appear to work for them, nothing responds. And no errors are parsed in console or ingame.

**To Reproduce**
See above.

**Expected behavior**

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
https://paste.ubuntu.com/p/Q6rxhDHG5y/

**Additional context**
Something is broken.

**Comment by Ghost-chu** [comment]
It works fine on my survival server with LuckPerms on QuickShop 2.2.10.
Maybe you should check you have spelling issue on permission name?

**Comment by cloakfox** [comment]
Sigh.. please lol. Im not joking.

**Comment by Ghost-chu** [comment]
If possible, please give me your server IP address.
And you need access me to OP and whitelist(if have).

My Minecraft ID is `Ghost_chu`.
I will visit your server tomorrow.

Before that, i hope you can join our Discord server to get help.

Because now have 1000+ servers running QuickShopRR and 293 server running 2.2.10 version without permission issue.

**Comment by cloakfox** [comment]
IP: mcfoxcraft.com
Then join survival, your account should have all quickshop perms.

**Comment by Ghost-chu** [comment]
I'm online now

**Comment by Ghost-chu** [comment]
After test, it seems is your permission settings issues.
Please check it by yourself first.

**Comment by cloakfox** [comment]
And what exactly is this issue? The only plugin not working currently is QuickShop ReRemake..

If there are issues with my permissions settings more plugins would have broken too.

**Comment by Ghost-chu** [comment]
> And what exactly is this issue? The only plugin not working currently is QuickShop ReRemake..
> 
> If there are issues with my permissions settings, more plugins would be broken too.

I don't know, But quickshop use standard bukkit permission system, so if other plugin works fine, qsrr should works fine too.

**Comment by oxgen1** [comment]
I had this exact Same issue and the problem was NoCheatsPlus (which you have also) I removed NoCheatsPlus and it fixed  the issue
