### ISSUE TITLE
Plugin does not work with certain economies / balance goes into - [BUG]

### ISSUE THREAD

**Issue by Allison000** [Ghost-chu/QuickShop-Reremake#147]
I've tried using GemsEconomy, sadly the quickshop does not detect that plugin despite it working perfectly in server.

Other than that, I tried VEconomy, and the plugin allows it to go into - balance, I had made an admin shop and one player bought over 64 diamonds and went into more than -2000$ in debt even though it's impossible to do so on that plugin (this was the developers response, something regarding withdraw() directly - https://i.imgur.com/LrvEb7w.png)

Would really love to get this plugin running, I am using 1.14.3.

**Comment by Ghost-chu** [comment]
Economy not return failure signal to Vault, so quickshop think this is success.
Anyway, i will add a option to allow user enable/disable this feature if they had a economy plugin not return correct signal.

**Comment by Ghost-chu** [comment]
New settings was added for this in master
