### ISSUE TITLE
[BUG] Shops aren't being made with items that involve custom enchants.

### ISSUE THREAD

**Issue by DXUltimate** [Ghost-chu/QuickShop-Reremake#149]
**Describe the bug**
Shops aren't being made at all involving custom enchants.

**To Reproduce**
1. Download paper 127+
2. Download Enchantment Solution and boot up server.
3. Spennd 50 levels to get custom enchants
4. try to create a shop with said custom enchants.

**Expected behavior**
The shop to be created, as per normal.

**Screenshots**
https://www.youtube.com/watch?v=WmtxapvXdng&feature=youtu.be

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
https://paste.ubuntu.com/p/kK8qz9MvpJ/

**Comment by Ghost-chu** [comment]
it looks reason is some plugin cancel the event and force process it by it self.
