### ISSUE TITLE
QS uses server's location for language, even if both "language" and "game-language" are set differently

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#1499]
When setting an item to buy/sell does QuickShop use whatever language the server's system is set too.
In my case would this be de-CH, which has some annoying downsides since it's more a "joke" language than a real one. Even after setting both `language` and `game-language` in the config.yml to `en-US` does QuickShop still use the german language for items.

This causes issues where f.e. the item is displayed with that particular language on the sign, which may confuse people that aren't aware of it.

**Comment by sandtechnology** [comment]
How about use `/qs reset lang`? It shouldn't happened in the latest release

**Comment by Andre601** [comment]
> How about use `/qs reset lang`? It shouldn't happened in the latest release

This command worked. Thanks
