### ISSUE TITLE
[BUG] AdminShops Still Notify orginial author

### ISSUE THREAD

**Issue by BluePhoenixGame** [Ghost-chu/QuickShop-Reremake#150]
**Describe the bug**
Getting updates about a admin shop
**To Reproduce**
Create a admin shop, by creating the shop. Right clicking it and setting it to unlimited.
Then sell/buy anything and you get output like if it was one of your shops.
**Expected behavior**
No output to the original maker, but a output in the console.

**Screenshots**

![Screenshot from 2019-07-20 17-06-07](https://user-images.githubusercontent.com/38372706/61580312-cc7bc280-ab10-11e9-88fb-d0e6679c7b97.png)

**Paste link:**
https://paste.ubuntu.com/p/yMsNCx6s6z/

**Additional context**
Great plugin you made btw, i just don't want info as if it was one of my shops. Because in our survival server i am a part of it too. So i play too, and i don't want to be notified like it was one of my shops.

**Comment by Ghost-chu** [comment]
Actually this not a bug, because owner still is you in database.
AdminShop just display name when unlimited mode on.

**Comment by BluePhoenixGame** [comment]
Can a feature be added so i can make AdminShops with the expected behaviours i listed? Essentially sepparating unlimited with a new feature adminshop. Similar to chestshop's admin shop?

**Comment by Ghost-chu** [comment]
Not hard, but you may need waiting after i finished my surgery.

**Comment by Ghost-chu** [comment]
Before i update, you can turn on `ignore-unlimited-shop-messages` to ignore all unlimited shops msgs to you.

**Comment by BluePhoenixGame** [comment]
Oh, i hope you get better. No need to rush somehing like that for me. Take your time :)

I might have missed that in the config.

**Comment by kena73** [comment]
May I recommend looking at the shop and running "/qs setowner Server"
I had the same problem and that fixed it for me

**Comment by BluePhoenixGame** [comment]
Ah nice, but wouldn't it error out since there is no user with name Server? That otherwise seems like a great fix.
