### ISSUE TITLE
Elite Mobs compatability

### ISSUE THREAD

**Issue by elaineandsparky** [Ghost-chu/QuickShop-Reremake#1500]
We use your plugin and Elite Mobs.
I'm not sure if you are familiar with this plugin but if not, you can get items which are soulbound to the player who got them. If someone else has this soulbound item it is worthless to them, they cannot use it.
Our players are starting to list these items for sale in chestshops. Whilst it does display that it is soulbound in the item preview an unsuspecting player may fall victim to this.
I notice there is a blacklist option in the config but the way Elite mobs generates these items it would be impossible to list all items here.
We know we have a bit of educating amoungst our players to do here about soulbound items but I was wondering if there is any way for it to be set that no elite items/soulbound items could be sold in the shops?

**Comment by Ghost-chu** [comment]
I'm not sure how EliteMobs works, but if they have a soulbound lore, you might can add the lore keyword to lore blacklist.

```yaml
  #The list of lore keywords that are blocked from being sold.
  #This will not affect existing shops!
  blacklist-lores:
    - "keyword"
 ```
Case Sensitive

**Comment by elaineandsparky** [comment]
Thank you!
I had missed this in the configs and SoulBound was already there but not working due to capital letters. A bit of playing around and the items are now blacklisted.
