### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VenomHZ** [Ghost-chu/QuickShop-Reremake#151]
**Describe the bug**

**To Reproduce**
1. be just normal member
2. type /qs create
3. See error

**Expected behavior**
i want normal member (not OP) can create shop

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
- https://paste.ubuntu.com/p/mXBHKbBm8W/

**Comment by Ghost-chu** [comment]
Please first up-to-date plugin, you still 2.2.8, if still see this error, please open new ticket.
