### ISSUE TITLE
Large parts of english translation gone

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#1517]
The english translation on Crowdin is now at only 8% as of writing this, while it was at pretty much 100% before.

Did something happen or why do we have such a huge loss of translation here?

**Comment by Ghost-chu** [comment]
We have moved the storage location and Crowdin platform automatically processed our translation to migrate, and maybe that is why.

**Comment by Ghost-chu** [comment]
QuickShop v5 uses Crowdin OTA distribution, so we don't need package translations into the jar.
