### ISSUE TITLE
[BUG] Normal member can't create shop

### ISSUE THREAD

**Issue by VenomHZ** [Ghost-chu/QuickShop-Reremake#152]
Describe the bug
Normal member can't do /qs create. Only OP can do it.

To Reproduce
1. be just normal member
2. type /qs create
3. See error

Expected behavior
i want normal member (not OP) can create shop

Paste link:
Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.

https://paste.ubuntu.com/p/4QR2qg3BXs/

**Comment by Ghost-chu** [comment]
Please set permission follow the permission list
