### ISSUE TITLE
[BUG] log-actions seem not to work in 2.3.0

### ISSUE THREAD

**Issue by kumaisu** [Ghost-chu/QuickShop-Reremake#153]
**Describe the bug**
No records in qs.log when purchasing items from another player shop

**To Reproduce**
1. Set log-action item in config.yml to true
2. Buy items in the shop
3. Check qs.log

**Expected behavior**
Under normal circumstances, qs.log will keep track of trading

I am using this log to create a plug-in that can get trading statistics

**Comment by Ghost-chu** [comment]
thanks for report, for stats i advice you make a addon, and log will fixed in next version(in plan)

**Comment by kumaisu** [comment]
Thank you for correspondence
Wait for a fix in the next version
