### ISSUE TITLE
[BUG] Item preview shows actual Item name instead of custom name

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#1538]
### Description

When left-clicking a shop sign to buy an item will the Item name listed (The one you can click on to see a preview) display the actual item name and not any custom one it may have, if the item was renamed.

### Steps to reproduce

1. Create a shop selling a renamed (and custom textured) item.
2. Left-click the sign to enter buy mode
3. See how the base item name is used and not the custom one (3rd line in UI)

### Expected Behaviour

QuickShop should display the actual name displayed by the item (The one you set during renaming)

### Screenshots

See the "Gegenstand" line
![image](https://user-images.githubusercontent.com/11576465/139603119-8af78fae-7244-459b-ab43-bc5f00f89de2.png)

### `/qs paste` URL

https://paste.helpch.at/afovuxecej

### Additional Context

The hover text applied to the item name is actually displaying the display name of the item itself.

**Comment by Ghost-chu** [comment]
confirmed

**Comment by Ghost-chu** [comment]
try this build: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1907/artifact/target/QuickShop.jar

try to fix it on the phone, not tested yet.

reopen this issue if still not working

**Comment by Andre601** [comment]
Doesn't fix it. Also, I can't reopen issues that are closed by others... even my own.

**Comment by Ghost-chu** [comment]
will look it after I back to my dormitory

**Comment by Ghost-chu** [comment]
please try this build: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/1908/artifact/target/QuickShop.jar

**Comment by Andre601** [comment]
This fixed the issue, thanks.
