### ISSUE TITLE
[BUG] Shops made with custom enchantments do not stay after server restart.

### ISSUE THREAD

**Issue by DXUltimate** [Ghost-chu/QuickShop-Reremake#154]
**Describe the bug**
Shops made with custom NBT data like custom enchantments aren't staying after server restart.

**To Reproduce**
1. Download paper-135+, Enchantment Solution (example plugin), and Quickshop
2. Use /qs create on a custom enchanted item and put item into chest for shop to notice it
3. Restart server
4. Left click exact same shop sign, and it refreshes to 0. See images below.

**Expected behavior**
The shops loaded up, with the custom enchantments.

**Screenshots**
Before restart and fresh creation of shop
https://i.imgur.com/JJqtQ1h.jpg

After restart
https://i.imgur.com/OnbyxD9.jpg

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
https://paste.ubuntu.com/p/ZPWSpghsRh/

**Additional context**
Only happens with custom things.

**Comment by Ghost-chu** [comment]
It same under spigot?

**Comment by DXUltimate** [comment]
Yeah, exact same.

**Comment by Ghost-chu** [comment]
did you used like CustomEnchanted plugins?

**Comment by Ghost-chu** [comment]
Too long time no response
