### ISSUE TITLE
Quickshop won't load "security error SHA-256" [BUG] 

### ISSUE THREAD

**Issue by LuluxClient** [Ghost-chu/QuickShop-Reremake#1549]
### Description

When I added the new update of quickshop I got this error : https://pastebin.com/PXQpWCEg

### Steps to reproduce

Download latest Paperspigot 1.17.1 and download quickshop latest and start your server

### Expected Behaviour

Quickshop should work

### Screenshots

none

### `/qs paste` URL

not loaded no config fils created

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/issues/1085
