### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ItsSynchro** [Ghost-chu/QuickShop-Reremake#1553]
### Description

Modified messages.yml's have a "Missing Language" line where the name of the item is supposed to be for "Out of Stock" shops.

### Steps to reproduce

1. Use https://paste.gg/p/anonymous/c07f8978e77d49a7b936ce8026547b2f
2. Left click on a shop or buy out a shop till its "Out of Stock"

### Expected Behaviour

Show the actual item that has Ran Out of Stock instead of showing "Missing Language"

### Screenshots

![2021-11-02_17 24 40](https://user-images.githubusercontent.com/16171807/139958401-0ba195a3-9968-411b-b657-c461ba43bdb0.png)

### `/qs paste` URL

https://paste.helpch.at/ituqofeqez

**Comment by Ghost-chu** [comment]
Make sure your override file is valid JSON format.

**Comment by ItsSynchro** [comment]
> Make sure your override file is valid JSON format.

In the "Steps to Reproduce" I provided my messages.yml. I've gone ahead and pasted it inside jsonlint.com and it says its a "valid JSO
![Screenshot 2021-11-02 192558](https://user-images.githubusercontent.com/16171807/139965584-702e98e7-df2e-4235-9ffb-e1e37bd59aca.png)
N"

**Comment by Ghost-chu** [comment]
> > Make sure your override file is valid JSON format.
> 
> In the "Steps to Reproduce" I provided my messages.yml. I've gone ahead and pasted it inside jsonlint.com and it says its a "valid JSON" ![Screenshot 2021-11-02 192558](https://user-images.githubusercontent.com/16171807/139965584-702e98e7-df2e-4235-9ffb-e1e37bd59aca.png)

override file can only override part of texts, try only add the texts that modified.

I will check this issue later.

**Comment by Ghost-chu** [comment]
also, if you trying override the section, you must make sure all keys in section has been correctly override. Or they will missing.

**Comment by ItsSynchro** [comment]
> also, if you trying override the section, you must make sure all keys in section has been correctly override. Or they will missing.

Sorry but I'm a little bit confused... Previously, my messages.json file worked perfectly fine whilst in the default directory when previously to updating to the big update. However after the major update it ceased working. I would really love some sort of example as to what you mean as I'd like to go back to using my modified messages.json

**Comment by Ghost-chu** [comment]
> > also, if you trying override the section, you must make sure all keys in section has been correctly override. Or they will missing.
> 
> Sorry but I'm a little bit confused... Previously, my messages.json file worked perfectly fine whilst in the default directory when previously to updating to the big update. However after the major update it ceased working. I would really love some sort of example as to what you mean as I'd like to go back to using my modified messages.json

we nolonger use messages.json in this big update, so plugin won't read it of course.

**Comment by Ghost-chu** [comment]
should fixed in 5.0.0.7
