### ISSUE TITLE
[BUG] 2.2.10 Kick 

### ISSUE THREAD

**Issue by kena73** [Ghost-chu/QuickShop-Reremake#156]
User tries to buy/sell from/to shop, gets kicked with no error messages in the console.
https://paste.ubuntu.com/p/dFs7Gskw3M/
https://imgur.com/a/zoqhlbr

**Comment by Ghost-chu** [comment]
please report issue use template.
and qs WON'T kick player, you should check your other plugin

**Comment by Ghost-chu** [comment]
A solution is try reset your language file, that may broken

**Comment by kallemarc** [comment]
Which bungee version do you use?
