### ISSUE TITLE
[BUG] Opening this project in eclipse

### ISSUE THREAD

**Issue by log4b0at** [Ghost-chu/QuickShop-Reremake#158]
**Describe the bug**
When i clone the project and try to open it in eclipse i have about 300 errors, some methods doens't exist on certain class, is the code up to date?
For example in QuickShop.java i have error like "this.getLogWatcher" does'nt exist, or "this.getShopManager", also "getSentryErrorReporter".

**To Reproduce**
1. Clone the project
2. Import in eclipse

**Comment by log4b0at** [comment]
Here is a screen of differents errors in the code that i have:
![image](https://user-images.githubusercontent.com/28230813/61938219-dda15500-af90-11e9-8de1-886919b2ab8c.png)

**Comment by Ghost-chu** [comment]
You need install Extension `lombok`

**Comment by log4b0at** [comment]
ok i will check that right now

**Comment by log4b0at** [comment]
after installing i cant re-open eclipse anymore.. this is weird

**Comment by log4b0at** [comment]
ok i have found the problem, when the installer copy lombok path in my eclipse.ini he replace "(" and ")" characters by "\(" and "\)" and this stop eclipse to work.
How to activate it now?

**Comment by Ghost-chu** [comment]
I don't know, I like use IJ(IDEA)…
