### ISSUE TITLE
[BUG] Kick from Server 2.3.1

### ISSUE THREAD

**Issue by kallemarc** [Ghost-chu/QuickShop-Reremake#159]
Do not enter / QS and enter a spacebar behind it.
Even when inserted with STGR + V you are kicked by the server.
Bug in Video.

https://kallemarc.de/Screens/2019-19-07-28-11-53.mp4

**Comment by Ghost-chu** [comment]
Could you run command /qs paste after you got kicked?
I need some infomation for this error, thanks.

**Comment by kallemarc** [comment]
No, because one is also kicked for it

**Comment by Ghost-chu** [comment]
use console, make sure you are using default language(en)

**Comment by kallemarc** [comment]
The problem lies with the bungee /qs [TAB] sending empty packets.
In the waterfall config, this had to be changed:

allow_empty_packets: false to allow_empty_packets: ture

But that can not be the solution.
please fix it.

**Comment by Ghost-chu** [comment]
your language file may broken, reset your language file to english.

amg I need /qs paste url.
if you can't use command in game, run command in console.

**Comment by Ghost-chu** [comment]
too long time no response, issue closed
