### ISSUE TITLE
Suggestion: Ability to buy in bulk

### ISSUE THREAD

**Issue by FixTheAdmin** [Ghost-chu/QuickShop-Reremake#16]
First of all, thank you for this plugin. It's just what we need.

Our server uses gold ingots as currency an we'd like the ability to sell items in bulk for a certain price. Eg 32 cobblestone for 1 gold. Right now we can only sell 1 cobblestone for 1 gold as minimum.

Thanks for taking time.

**Comment by Ghost-chu** [comment]
We are no plan add this feature now, But it sounds cool, So maybe will add in future!
Thanks your advice. This issues will keep open until feature added.

**Comment by Bezod** [comment]
Very sorry to hear that. Thanks for keeping the issue open for future reference 👍

**Comment by BluePhoenixGame** [comment]
I hope to see this added. Like how chestshop does it.

**Comment by Ghost-chu** [comment]
add this request to v4 milestone
