### ISSUE TITLE
[BUG] False Permission quickshio.areashop.bypass

### ISSUE THREAD

**Issue by kallemarc** [Ghost-chu/QuickShop-Reremake#160]
quickshio.areashop.bypass 

The permission 

> quickshio.areashop.bypass

was found by Luckperms.
Please fix the spelling error.

https://kallemarc.de/Screens/2019-19-07-28-17-05.png

**Comment by Ghost-chu** [comment]
quickshop doesn't registered permission quickshio. or quickshop.areshop.
so this not our problems.
