### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kallemarc** [Ghost-chu/QuickShop-Reremake#161]
That's the bug here
https://github.com/Ghost-chu/QuickShop-Reremake/issues/160

I have now made a test server.
This Luckperms still has not been found by Luckperms, so this must be in QuickShop.

[18:02:54 INFO]: Plugins (4): LuckPerms, Vault, QuickShop, Essentials

https://paste.ubuntu.com/p/W2mGJ3kqt2/

**Comment by Ghost-chu** [comment]
okay i will check it, thanks for reporting
