### ISSUE TITLE
Suggestion: Admin Shop

### ISSUE THREAD

**Issue by Kyrobi** [Ghost-chu/QuickShop-Reremake#163]
I know there is already an Unlimited Shop. However, you can only make it if you set it to unlimited.

However, I want to sell limited-time items with a set amount of quantity.

So maybe something like `/qs setowner AdminShop` will set it as an admin shop. The money can just disappear when a person buys from it.

I could just set it as my own shop, but I don't want to gain money from it.

**Comment by Ghost-chu** [comment]
Linked with #601
