### ISSUE TITLE
[BUG] ITEM NBT NOT SUPPORTED

### ISSUE THREAD

**Issue by Va1a** [Ghost-chu/QuickShop-Reremake#166]
**Describe the bug**
When I set up an item with a custom nbt in the latest version as of the bug reports creation date, the shop does not register items with the same nbt for some reason. it says 0 available.

**To Reproduce**
1. Make an item with custom lore "test"
2. Use /qs create to make a shop with that item
3. Try to sell it to the shop after making it an adminshop

**Expected behavior**
I expected the shop to register the same item and allow me to sell/buy it.

**Screenshots**
N/A

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
https://paste.ubuntu.com/p/b5zYn497qg/

**Additional context**
N/A

**Comment by Ghost-chu** [comment]
Confirmed, it support nbt, just lore check broken

**Comment by Ghost-chu** [comment]
Fixed in 2.3.9
