### ISSUE TITLE
[SEVERE BUG] items match not working on some items.

### ISSUE THREAD

**Issue by LoneDev6** [Ghost-chu/QuickShop-Reremake#168]
**Describe the bug**
items counter not increating for some items..

**To Reproduce**
1. create an item with this command:
/give @p minecraft:stone{AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:0.1f,Operation:0,UUIDMost:57871,UUIDLeast:153194}]} 1

2. create a shop, put the item in chest
3. see that the counter is not incremented and you can't buy the item

**Expected behavior**
Counter increased

**Comment by LoneDev6** [comment]
Did you even read that?

**Comment by Ghost-chu** [comment]
Already fixed, test in latest version, if still have problem, reopen this ticket

**Comment by LoneDev6** [comment]
Not working on the latest version 2.3.9.6
Did you test it? Use the command i sent you to generate the item

**Comment by Ghost-chu** [comment]
No any test, because it works for me.
Maybe you need do command `/qs paste` after check failed, and sent to there

**Comment by LoneDev6** [comment]
I can't share my server info, /qs paste inclused logs and things i can't share publicly.
I can contact you on Discord maybe?

**Comment by Ghost-chu** [comment]
Yes you can

**Comment by LoneDev6** [comment]
Send me discord message
LoneDev#7444

**Comment by Ghost-chu** [comment]
solved
