### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by mcx6** [Ghost-chu/QuickShop-Reremake#17]
please add the ability to choose how much of the item you want to sell in the shop 
to help out people who uses a physical money

**Comment by Ghost-chu** [comment]
This feature already exist, player can choose how many items sell/buy in once.
If you mean like 1 dollar buy 2 items, you should see this issue:https://github.com/Ghost-chu/QuickShop-Reremake/issues/16

If this not you want get, please open a new issue, thanks!
