### ISSUE TITLE
[BUG] Item Entities Stuck - Inc picture

### ISSUE THREAD

**Issue by AlureonTM** [Ghost-chu/QuickShop-Reremake#170]
**Describe the bug**
For the player shops, after removing all of the items from a shop chest sometimes it will bug out and cause this https://i.imgur.com/REpjxgk.png

**To Reproduce**
Not 100% sure but it seems like when the chests are empty they can disappear leaving the shop half there and half not? Players on my server just noticed it started happening and there isn't a shop to be removed to have the entity removed.

**Expected behavior**
No floating entity after shop is gone

**Screenshots**
https://i.imgur.com/REpjxgk.png
https://i.imgur.com/pn3SP7L.png
https://i.imgur.com/qIrify1.png

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
- https://paste.ubuntu.com/p/dT5VtWgrZf/

**Additional context**
n/a

**Comment by Ghost-chu** [comment]
It looks shop not got remove correctly.
Did you use plugin or worldedit/setblock to removed it?

**Comment by AlureonTM** [comment]
No I didn't. Its out in the "wild" where players are creating their own shops.

**Comment by Ghost-chu** [comment]
Big chance is target shop not correctly removed from server, usually is force-stop server plugin, upgrade to new version and try again

**Comment by Ghost-chu** [comment]
Fixed in 2.3.9.5
