### ISSUE TITLE
[BUG] Chest/sign duplication

### ISSUE THREAD

**Issue by DefinitlyEvil** [Ghost-chu/QuickShop-Reremake#171]
**Describe the bug**
Left click chest or sign will cause a new item to spawn and drop, thus caused item duplication. 
Does not require target to be a shop. 

**To Reproduce**
1. Install Residense (latest) plugin
2. Place down a chest
3. Go to survival mode
4. Left click it. 

**Expected behavior**
Shouldn't drop obviously. 

**Screenshots**
N/A

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
- Failed to generate one

**Comment by Ghost-chu** [comment]
This issue cannot reproduce by me on test server and my production server, Residense is a premium so i can't test it.
If possible, hope you can pm me your server address in discord.

**Comment by Ghost-chu** [comment]
K, I think this issue is caused by build-permission-checker, it will call events to plugins and check the event staus.
So maybe i should find a way to fix it...

**Comment by DefinitlyEvil** [comment]
Thanks! ;) 
For now I think I will just block all chest/sign drops. xD

**Comment by Ghost-chu** [comment]
[QuickShop-Reremake 2.3.10.jar.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/3544880/QuickShop-Reremake.2.3.10.jar.zip)
Please install this snapshot.
And configure `shop.protection-checking-filter` listener blacklist, add residence's BlockBreakEvent listener in it.

**Comment by Ghost-chu** [comment]
You can turn on `DevMode` or use command `/qs debug`, and try duplication the chest/sign again, You should can see the listeners calls in console, find resdenice's one and follow the guide in config.example.yml to add it in filter

**Comment by Ghost-chu** [comment]
[QuickShop-Reremake 2.3.10.jar.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/3544904/QuickShop-Reremake.2.3.10.jar.zip)
snapshot update, force set the fake event to drop noting, hope can solve this

**Comment by DefinitlyEvil** [comment]
Thanks, I'm gonna try tonight!

**Comment by DefinitlyEvil** [comment]
Oh btw the player doesn't need to break the block, he just needs to left click once.

**Comment by Ghost-chu** [comment]
no idea, quickshop won't spawn anything when you clicking except display item.

**Comment by DefinitlyEvil** [comment]
Then there might be some incompatibilities, idk. xD
