### ISSUE TITLE
Feature request: custom quantity sale

### ISSUE THREAD

**Issue by dorianxonic** [Ghost-chu/QuickShop-Reremake#175]
**Hi!** 
My server uses diamonds as economy currency through [_Gringotts_](https://github.com/MinecraftWars/Gringotts) because those are not a farmable item. I would like to be able to set the quantity of the item which is being sold, because right now there are few items that can be worth _X diamonds/each_. If this is something you're looking forward to, I'd be glad to test it.

**Comment by Ghost-chu** [comment]
A good idea is use item economy plugin to do it
