### ISSUE TITLE
[BUG] Vault with bPermissions2

### ISSUE THREAD

**Issue by log4b0at** [Ghost-chu/QuickShop-Reremake#180]
**Describe the bug**
Permissions seems doesn't work when using Vault with bPermissions2

**To Reproduce**

1. Create bukkit server
2. Install Vault and bPermissions2
3. Set permission-type to 1 in config.yml of Quickshop
4. Add quickshop.use, quickshop.create.sell, quickshop.create.buy, quickshop.create.cmd and all others nodes to a group like members
5. See that members can't create shop by /qs create or by punching a chest
No error message displayed after using /qs create,
I can create shop when im op.
I use worldguard. The problem is the same out of the spawn region.
I use AreaShop and the plugin that Ghost-chu made to make a bridge between quickshop and areashop (update necessary?)
Thanks for your time
**Paste link:**
- https://paste.ubuntu.com/p/2ZFVNtsVpF/

**Comment by log4b0at** [comment]
I will install LuckPerms to see if this is really a problem with bPermissions2

**Comment by Ghost-chu** [comment]
no any permissions was set in the LuckPerms
