### ISSUE TITLE
[BUG] Server crashes after creating a shop 1.14.4

### ISSUE THREAD

**Issue by AugusDogus** [Ghost-chu/QuickShop-Reremake#187]
**Describe the bug**
After creating a shop in Spigot 1.14.4, my server crashed. I was able to reproduce the bug several times to ensure it was QuickShop that caused the crash. 

**To Reproduce**
1. Click a chest with any item.
2. Type any price in for the item.
3. Wait approximately 5 (five) seconds for the server to crash.

**Expected behavior**
1. Click a chest with any item.
2. Type any price in for the item.
3. Have users able to buy or sell from the shop without the server crashing.

**Paste link:**
- https://paste.ubuntu.com/p/r6Bg6zNBtG/

**Additional context**
- Using `QuickShop-Reremake.2.4.3.1.jar` on `Paper-187 for 1.14.4`
- I've also went ahead and captured the logs manually that occur leading up to and during the crash of the server. You can see those here: [https://gist.github.com/AugusDogus/de06b443f2d45b8a62686548e2a9f40d](https://gist.github.com/AugusDogus/de06b443f2d45b8a62686548e2a9f40d)

**Speculation**
- This could be a duplicate of #129.
- This appears to be an issue with running the `JDBC4PreparedStatement`

**Comment by Ghost-chu** [comment]
This sounds like a JDK bug, follow these steps to try fix your problem.
https://community.oracle.com/thread/2553773
