### ISSUE TITLE
[BUG] GriefPreventjon and WorldGuard bypass

### ISSUE THREAD

**Issue by Dinoosawruss** [Ghost-chu/QuickShop-Reremake#188]
**Describe the bug**
Currently, when utilizing GriefPrevention, players will still be able to create a QuickShop sign within another user's claim. This effectively bypasses the claim, allowing users to steal items from QuickShop chests, and other chests unrelated to QuickShop if they have an open face. Additionally, players are able to create QuickShop signs on chests that already have a QuickShop set up.

**To Reproduce**
1. Open server with grief prevention / world guard
2. Make a claim
3. Try and make a shop (on an account that doesn’t have access to the claim)

**Expected behavior**
Player gets told they can’t make shops there

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text
- https://paste.ubuntu.com/p/SYtvctMRq2/

**Additional context**
This also happens with world guard allowing people to make shops in spawns

**Comment by Dinoosawruss** [comment]
Why was it closed?

**Comment by Ghost-chu** [comment]
It was fixed in new release.



---Original---
