### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheSavior22** [Ghost-chu/QuickShop-Reremake#189]
hello, I have the economy of each world separated, that is, when someone pays another player, the money is in that world, but when you buy in a store the money does not stay in that world, it goes to the world in which There is the creator of the store, that creates problems for me, if they could fix it it would be fantastic: D

**Comment by Ghost-chu** [comment]
Follow the template and this not quickshop should to do, you might need contact your economy plugin author ask for support
