### ISSUE TITLE
[BUG]Item display bug

### ISSUE THREAD

**Issue by Jason897759** [Ghost-chu/QuickShop-Reremake#193]
**Describe the bug**
If you place several shops next to each other the items are not displayed correctly.

**To Reproduce**
1. Use the newest version of the plugin(2.4.6.2)
2. Place a few shops next to each other
3. Click on a Shop

**Expected behavior**
The items are displayed correctly.

**Screenshots**
https://prnt.sc/pg4hvw

**Paste link:**
- 【https://paste.ubuntu.com/p/YPbwnCWrxS/】

**Comment by Andre601** [comment]
In addition, do items also disappear when you remove shops right next to it (destroy the chest)

**Comment by Jason897759** [comment]
> o items also disappear when you remove shops right next to it (destroy the chest)

Yeah, they do.
