### ISSUE TITLE
[BUG] Dropped items disappear (chest icon)

### ISSUE THREAD

**Issue by LoneDev6** [Ghost-chu/QuickShop-Reremake#194]
**Describe the bug**
Sometimes items drops disappear, to fix this you have to click to buy item and it reappears.

I'm using latest version of the plugin and paper 1.14.4 latest build

**Comment by Jason897759** [comment]
I think you mean the same bug that I have already reported. https://github.com/Ghost-chu/QuickShop-Reremake/issues/193

**Comment by LoneDev6** [comment]
Maybe, but happens also with this:
![immagine](https://user-images.githubusercontent.com/27242001/66358979-78e17e00-e975-11e9-9440-4900065fdac3.png)

**Comment by Ghost-chu** [comment]
Revert the changes, the update will test after 4 days when a back to home
#192 #193 #195 #197
