### ISSUE TITLE
[Feature Request] MysqlEconomyBridge compatibility

### ISSUE THREAD

**Issue by gp-Airee** [Ghost-chu/QuickShop-Reremake#196]
We use [MysqlEconomyBridge](https://github.com/brunyman/MysqlEconomyBridge) to sync the economy between 3 different servers. There's a problem though, once you join a server it refreshes your balance from the database. Could you please fix this? If you need ideas for implementation of a fix, I have ideas.

**Comment by Ghost-chu** [comment]
QuickShop use Vault api, all trade process by Vault, so you should ask the MysqlEconomyBridge's author for support.
