### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Phoenixsword69** [Ghost-chu/QuickShop-Reremake#197]
Ok so im using a minehut server (1.14.4 server hosting platform) and when i make sign shop it will crash almost instantly without warning

**To Reproduce**
Go on a minehut server with the plugin
Make a sign shop of any kind
Wait a few seconds
It will crash

**Expected behavior**
It was expected to stay up and not crash and allow you to use it

**Screenshots**
---

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
https://paste.ubuntu.com/p/8Pq98sBQ4r/

**Additional context**
Minehut uses an in-built plugin downloader so it may not be up-to-date because you cannot import downloaded plugin files ;-;

**Comment by Ghost-chu** [comment]
This plugin build is really old, you must update to latest build.
