### ISSUE TITLE
[BUG]item name in anvil makes shop give money but do not take item from player

### ISSUE THREAD

**Issue by MintSkye** [Ghost-chu/QuickShop-Reremake#199]
**Describe the bug**
If a player change a diamond name in the anvil,then sold it to shop.The shop will give the player money but let player keep the diamond.
not only the diamond but also any other item have this bug.
version : QuickShop Reremake 2.4.6.2
paper -git 214

**Comment by Jason897759** [comment]
Already reported https://github.com/Ghost-chu/QuickShop-Reremake/issues/195
