### ISSUE TITLE
BUG Shops stop working after server restart!

### ISSUE THREAD

**Issue by Nesseley** [Ghost-chu/QuickShop-Reremake#2]
Using latest version of QuickShop 1.13

Works perfect, but after a restart the shops stop working.
I click the shop sign and nothing happens in the chat. I can't buy or sell to the shops.

**Comment by Nesseley** [comment]
I get this error on startup
https://pastebin.com/RUvBekqt

**Comment by Nesseley** [comment]
"Error loading shops" when switching to mysql database.
https://pastebin.com/gAuRb6wP

**Comment by Ghost-chu** [comment]
check your vault and economy plugin

**Comment by Nesseley** [comment]
I am using 
Vault version 1.6.6-b${env.TRAVIS_BUILD_NUMBER}
TheNewEconomy version 0.1.1.2

**Comment by Nesseley** [comment]
Shops gets created and put into mysql. 
But after a restart the "error loading shops" comes up and then the shops gets wiped from mysql.

**Comment by Nesseley** [comment]
https://pastebin.com/s2pSpqS7

Getting these errors on startup

**Comment by Nesseley** [comment]
also this is startup: https://pastebin.com/QWipV4jk

**Comment by Nesseley** [comment]
I've tried the new release and still have the problem with shops not loading.
error: https://pastebin.com/TKm7Uqvn

**Comment by Ghost-chu** [comment]
Try lastet version and report error report thanks!

**Comment by Nesseley** [comment]
Would you be able to port this plugin to 1.13.1?

**Comment by Ghost-chu** [comment]
Already support 1.13.1 But still have some bugs need fix

**Comment by Ghost-chu** [comment]
Can you use lastet build and send me DEBUG log in console with this issues to help fix?

**Comment by Nesseley** [comment]
https://pastebin.com/xJ7T465z

Still errors on 1.2.3 spigot 1.13.1

**Comment by Ghost-chu** [comment]
Looks is your economy plugin not support coin symbol

**Comment by Ghost-chu** [comment]
This issue now fixed in lastet build, If still not working, please create a new issue.
