### ISSUE TITLE
[BUG] item not consumed on sale in unlimited shops

### ISSUE THREAD

**Issue by Aurrys** [Ghost-chu/QuickShop-Reremake#202]
[version qs reremake 2.4.6.4]
When you try to sell items in an unlimitted buying shop, if the item has been renamed once, then renamed again with the original name of the block, the sale is made but the plugin doesn't consume the items.

**To Reproduce**
1. Get a diamond block.
2. Create a unlimited quickshop buying diamond blocks
3. Rename your block to anything you want.
4. Rename your block AGAIN to 'Block of Diamond'
5. Try to sell it
6. Notice that you have money and the block is still in your inventory.

**Expected behavior**
Either refuse the sale, or consume the blocks.

**Paste link:**
Sorry no paste link, bug on production server and the paste output is several hundreds of thousands of lines. The bug is explicit enough I believe, and when the bug occurs, here's the console output :
[14:53:15] [Server thread/WARN]: [QuickShop] Could not take all items from a players inventory on purchase! Vayns_, missing: 42, item: Diamond Block!

**Comment by Ghost-chu** [comment]
duplicate #200
