### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by florosss** [Ghost-chu/QuickShop-Reremake#203]
Hello,
Some time ago, I asked you a functionality. I fear there was a misunderstanding, due to my english writing.
Could you create a permission to ignore the shop creation tax ? → I wish to put the tax globally but remove it from some player ranks.
I hope it will help in the development to get this demand in better english than before.
Thank you by advance for any answer. The players community is beginning to ask me regularly the advancement of the rank.
Cordially

**Comment by Ghost-chu** [comment]
Added in commit 36e9ac4 and will release in next release version.
