### ISSUE TITLE
[BUG] Changing Double-chest inventory does not update sign

### ISSUE THREAD

**Issue by JoschuaSchneider** [Ghost-chu/QuickShop-Reremake#206]
**Describe the bug**
When creating a Doublechest shop (with quickshops.create.double permission), updating the items inside the container does not immediately update the sign (as it does with a single chest).
After Right-clicking the sign to bring up the controlpanel, the amount updates correctly.

**To Reproduce**
1. Create a double chest shop or extend a single chest one
2. Put Items inside the chest or take them out
3. The amount does not change until right-clicking the sign

**Expected behavior**
The amount on the sign should update on changing the containers inventory like with a single chest shop.

**Screenshots**
The Setup:
![2019-11-10_17 42 13](https://user-images.githubusercontent.com/11740387/68547456-2bc45200-03e2-11ea-9b01-444ca376dab6.png)
The 704 Cobble:
![2019-11-10_17 42 35](https://user-images.githubusercontent.com/11740387/68547468-40a0e580-03e2-11ea-8af3-035bbf75a860.png)
Removed one stack of cobble (sign still at 704):
![2019-11-10_17 42 31](https://user-images.githubusercontent.com/11740387/68547470-4f879800-03e2-11ea-8420-01c9fa56caa2.png)
Sign updated after right-clicking:
![2019-11-10_17 42 44](https://user-images.githubusercontent.com/11740387/68547486-60380e00-03e2-11ea-9635-70aa21a93e3e.png)
The stats say "0 double shops":
![2019-11-10_17 51 17](https://user-images.githubusercontent.com/11740387/68547521-b907a680-03e2-11ea-8c53-3879888bcf69.png)

**Paste link:**

**Additional context**
QuickShops-Reremake version 2.4.7, running paper 1.14.4

I hope I'm not missing something here.

**Comment by Ghost-chu** [comment]
unlucky, i had no time to update plugin these days, it schedule to next weekend to fix, thanks report.

And if you can create a paste, it would be nice, i can get the plugin debug logs and server information from there.
If you afarid some secret thing leak in there, you can PM me in discord.

**Comment by JoschuaSchneider** [comment]
Yeah no problem, thats very minor, I just noticed it and wanted to let you know :)

I appreciate the time and work you put into this!
I'll also provide you with the paste asap!

Thanks for the fast reply!

**Comment by Ghost-chu** [comment]
Edit the code on mobile, build by Travis-Ci, so this build without any tests, hope it got fixed.

https://github.com/Ghost-chu/BinaryRepository/raw/master/QuickShop-Reremake/1430/target/QuickShop-Reremake%202.4.7.jar

**Comment by JoschuaSchneider** [comment]
I'll give it a try in a couple of minutes. Thanks!

I've also got a question about the enchantment matcher, can you accept me on discord when you got time?

Sorry for all the spam ^^
