### ISSUE TITLE
Shop Sign placement issue

### ISSUE THREAD

**Issue by lilacorn** [Ghost-chu/QuickShop-Reremake#21]
Signs will not be where you are facing the chest, it will go on the available empty space either left or right sides. if no empty sides, it will not place one on the chest. `here are the screenshots of what i am talkin about.
![i_053ddc8704](https://user-images.githubusercontent.com/6467895/48042502-62b8b580-e147-11e8-928a-cd646874689b.png)
![i_ed9bade40e](https://user-images.githubusercontent.com/6467895/48042503-62b8b580-e147-11e8-9336-d069b0632603.png)

`

**Comment by Ghost-chu** [comment]
Can't to reproduce this issue on spigot-1.13.2, keep open issue and waiting more test.
Thank you feedback.

**Comment by Ghost-chu** [comment]
Hey! Did you placed two same chest and not linked? 

Like this:    CHESTCHESTCHEST

**Comment by lilacorn** [comment]
the chests that are in the picture is chest trap chest trap so it does not end up as a double chests. another person has this problem as well and they posted on the plugin forum on spigot site.

**Comment by lilacorn** [comment]
this is the only thing i seen randomly in my server logs when i do /qs create 

https://pastebin.com/6pzxp2Tp

**Comment by Ghost-chu** [comment]
Try create by normaly not /qs create

**Comment by lilacorn** [comment]
players need to be not in vanish if they are and not in creative. so it works that way for me. i will post a reply to that one guy who is having same problem with the sign being on one side too.
