### ISSUE TITLE
[BUG] Heavy lag

### ISSUE THREAD

**Issue by zettlinger** [Ghost-chu/QuickShop-Reremake#218]
**Describe the bug**
Heavy lag with a user that has a guardian farm, minecarthopper to collect and then a sorting machine. NO linked shops! but timings lists Quickshop as being a 30-40% drag on the minecarthoppers anyway

**To Reproduce**
1. make guardian farm with a single minecarthopper to collect to sorter
2. stay near it
3. look at tps plummet
4. check on timings and see the single minecart hopper use 41% of tick

**Expected behavior**
No / little lag when there isnt a quickshop connected to a minecart_hopper

**Screenshots**
![quickshop delays](https://user-images.githubusercontent.com/1674418/69009586-eb6f5180-0956-11ea-89f1-2ba9cb2aeeb9.png)

**Paste link:**
https://paste.ubuntu.com/p/xtfMNXBQxM/

**Additional context**
full timings before and after shutting down Quickshop (the item to look for is pasted as screenshot above) Timings always slows my machine a lot from 20 tps to 10-15 so the overloaded situation is normal. What isnt normal that minecarthoppers, not linked to shops are suddenly 40% of the tick due to quickshop.

I mitigated part of the problem by lowering mobspawns but would like to see if the shop plugin could be made to run less heavy :)   Thanks!

Before (with chestshop lag): 
https://timings.aikar.co/?id=a7f4bf69b148415f9e89a9603c15f5f1

after shutting down quickshop: (notice no more mention of the heavy load on minecart hoppers from 41% to 1.8%)
https://timings.aikar.co/?id=c8782c66119f42ee8c814ea1471542a4

And thank you for your time and effort, the players LOVE the shop plugin so i hope we can resolve the tps hits :)

**Comment by Ghost-chu** [comment]
Please use Spark sampler to create performance sample, timings is sucks and can't show any useful infomations.

Download here: https://www.spigotmc.org/resources/spark.57242/

**Comment by zettlinger** [comment]
Which reports you want run ? i am adding it now

**Comment by Ghost-chu** [comment]
/spark sampler --start
wait 10mins
/spark sampler --stop

give me the link

**Comment by zettlinger** [comment]
Thanks for the explanation, i had already ran all the options but not for 10 min :)
The link below is one for over 10 min and thanks for mention this plugin, it helps to pin down lag in combo with the timings (this goes much deeper into which exact command than timings)

https://sparkprofiler.github.io/#Do36RccWCM

**Comment by Ghost-chu** [comment]
oof, debugLog eaten so many performance, your server heavy overloaded

**Comment by zettlinger** [comment]
it is a 2990WX with 128GB mem on NVMEs. quarter of the cores set to the linux VM:  8 cores,16 threads , main core was at 72% or so when i did the spark, the rest barely used.

**Comment by Ghost-chu** [comment]
try this beta version: https://github.com/Ghost-chu/BinaryRepository/raw/master/QuickShop-Reremake/1524/target/QuickShop-Reremake%202.4.7.2.jar
and set `disable-debuglogger` to true in config.yml

**Comment by zettlinger** [comment]
rebooting server now, i assume you want another 10 min or more spark after so will add that as an edit to this comment once i got it :)  Thank you so far for the help :)

**Comment by Ghost-chu** [comment]
only need spark report if qs still cause laggy

**Comment by Ghost-chu** [comment]
if everythings be fine, just close this issue

**Comment by Ghost-chu** [comment]
go sleeping, just comment below and i will check them when i get up.

**Comment by zettlinger** [comment]
Sleep well :)

First indication seems good but i forgot to change the db info so no shops were active. Running spark once more with all the shops active and will let you know. I will close the issue if it seems fixed :)
Thanks again

**Comment by zettlinger** [comment]
Problem seems solved, minecart hopper went from 41% to 1,8% with your beta version

Thank you for the fix !!

Closing the issue
