### ISSUE TITLE
Duplicate item

### ISSUE THREAD

**Issue by MatteoLego** [Ghost-chu/QuickShop-Reremake#219]
If you drop an object near the chest, it will merge with the article on the chest.
Objects above the chest will reappear, but "duplicate" items remain in my inventory.

I hope you understand better from the photos than I wrote.

Edit 2: We use clearlag, we deactivate itemmerge and it work.
The we use spigot (itemmerge) and it dont drop the item above anymore.

![2019-11-18_06 47 15](https://user-images.githubusercontent.com/49399082/69027717-2e214000-09d0-11ea-925d-51dbe020c8a8.png)
![2019-11-18_06 47 19](https://user-images.githubusercontent.com/49399082/69027718-2e214000-09d0-11ea-8e4a-574c669ad5ba.png)
![2019-11-18_06 47 22](https://user-images.githubusercontent.com/49399082/69027719-2eb9d680-09d0-11ea-9364-964097afa960.png)
![2019-11-18_06 47 26](https://user-images.githubusercontent.com/49399082/69027720-2eb9d680-09d0-11ea-9e49-962fc431fd75.png)
![2019-11-18_06 47 32](https://user-images.githubusercontent.com/49399082/69027721-2eb9d680-09d0-11ea-818d-f852ebe7a642.png)
![2019-11-18_06 47 35](https://user-images.githubusercontent.com/49399082/69027722-2eb9d680-09d0-11ea-9114-45f30eda3114.png)
![2019-11-18_06 47 38](https://user-images.githubusercontent.com/49399082/69027723-2eb9d680-09d0-11ea-9d7c-84409defb7ef.png)

**Comment by Ghost-chu** [comment]
![2019-11-18_14 12 44](https://user-images.githubusercontent.com/30802565/69028631-8dea0c00-0a0d-11ea-9bcf-1c9b351ea24e.png)
No template and can't reproduce, issue closed
