### ISSUE TITLE
[BUG] Log again

### ISSUE THREAD

**Issue by Ectabro** [Ghost-chu/QuickShop-Reremake#220]
**Describe the bug**
Since the last version, logs are written, but is it normal that item name isn't show anymore in log ?
I give you a screen of my test logs to show you

**Expected behavior**

**Screenshots**
https://image.noelshack.com/fichiers/2019/47/2/1574180656-log.png

**Comment by Ghost-chu** [comment]
Must paste the link of /qs paste.

**Comment by Ectabro** [comment]
https://paste.ubuntu.com/p/535CFXpHvB/

**Comment by Ghost-chu** [comment]
It looks is my fault, should replace the PlaceHolder ^^
