### ISSUE TITLE
[BUG] Shops still persist under two "removal" conditions

### ISSUE THREAD

**Issue by SextupleTap** [Ghost-chu/QuickShop-Reremake#221]
**Describe the bug**
When removing a shop with a command that fills blocks, the shops block entity will be deleted or replaced but it will not cause the removal of the shop, this allows the shop to persist whilst not being intractable physically, only being intractable with commands, this behavior can also be seen if enabling shulker box shops and removing it with a piston (as well as filling it in with another block via commands).

**To Reproduce**
1. Place a chest (or any other shop enabled block entity) and create a shop
2. Fill the chest (or any other shop enabled block entity) with any block such as air or stone
3. Upon completing step 2, the shop wasn't deleted and is now unable to be interacted with physically.
4. This can be reproduced with making a shop with a shulker box and pushing it with a piston, the shulker box will break but the shop won't be removed

**Expected behavior**
The expected behavior is where if the block entity for a shop ceases to exist under any condition, the shop will immediately remove itself, as to prevent the creation of invisible and physically non intractable shops under all circumstances.

**Screenshots**
It's more difficult to convey it through screenshots, this video along with the provided steps for reproducing above will make the process clear:
- https://www.youtube.com/watch?v=91oIjyVqYGY

**Paste link:**
 Execute command /qs paste, you will got a link contains your server infomations, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If create failed, you should can find a paste file under plugin/QuickShop folder.
- https://paste.ubuntu.com/p/pmytdsVr2Q/

**Additional context**
The bug itself doesn't seem to be game breaking, it causes the display item to persist but it also still retains its protected properties and can be removed with command deletion or by replacing a block entity in the position where it was removed and then removing it again to delete the shop. The plugin doesn't seem to glitch nor does the server either. This bug is most likely just an inconsistency with expected behavior and can allow players to create invisible shops that can't be interacted with unless a block entity is re-placed or its manually deleted.

**Comment by Ghost-chu** [comment]
Actually is it before, but if server load wrong world or world not loaded, all shop will removed by accident.
So now only remove block by player break, and plugin will actually remove the shop.

**Comment by Ghost-chu** [comment]
Thank you feedback, maybe i will add new command to allow all invaild shops.

**Comment by Ghost-chu** [comment]
![image](https://user-images.githubusercontent.com/30802565/69409847-c0b13e80-0d44-11ea-9ee0-c90ce00a094d.png)
Hope you enjoy it. /qs cleanghost
