### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Kyrobi** [Ghost-chu/QuickShop-Reremake#223]
**Describe**

`/qs find` will not show empty shops. This way, the plugin does not point to empty shops all the time.

It could be a config option to enable/disable finding empty shops.

**Comment by Ghost-chu** [comment]
Please use Feature Request template next time :)

**Comment by Kyrobi** [comment]
The feature request template does not exist :(

![image](https://user-images.githubusercontent.com/20980266/69487735-9d5dc080-0e24-11ea-892d-4b4a5b114966.png)
