### ISSUE TITLE
Error creating the MySql database

### ISSUE THREAD

**Issue by arboriginal** [Ghost-chu/QuickShop-Reremake#23]
Hi,

When using MySql as database, I've got an error on server startup:

> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'owner' used in key specification without a key length

Complete error in the log can be find here:
https://gist.github.com/arboriginal/af4ad9c3dcaddb141916385deb1ce57d

Sorry, I can't provide MySQL version information because my hosting service doesn't share it.

**Bonus:** Adding a table prefix will be IMHO a good idea ;)

**Edit:** Sorry, missing informations about my server and plugin versions...
QS version 1.3.0 / paperSpigot version 1.3.2 (paperclip-388).

**Comment by Ghost-chu** [comment]
Thanks for report.
Add in next version.

**Comment by Ghost-chu** [comment]
Fix `com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'owner' used in key specification without a key length` problem in 1.3.0.2.
Add `Database table prefix` in 1.3.0.2

But... I can't fix about CMI's issue, But i'm using CMI too, no this problem, Maybe you turn on somethings?

**Comment by arboriginal** [comment]
Sorry Ghost-chu but I don't understand what is the "CMI's issue".
(I will install the last release today, when players will disconnect to my server).

**Comment by Ghost-chu** [comment]
Sorry, looks i reply the wrong issue, you know, Because a bugly version, i have many issues on Github and SpigotMC.org

**Comment by Ghost-chu** [comment]
Just ignore about CMI's issues part
