### ISSUE TITLE
[FEATURE] Experimental versions

### ISSUE THREAD

**Issue by portlek** [Ghost-chu/QuickShop-Reremake#231]
We can create a new branch that we can test the new features that come from pull requests.

Why I want this is, for example, I can't test my pull request enough by myself so, I need testers for it.

The way is simple;
> Create a new branch called dev
> Our pull requests will accept for the created branch
> And release a pre-release version for spigot with -dev suffix.
> Then we will wait for the issue reports.
> Finally, we will fix the dev branch issues.

Everybody is happy :)

**Comment by Ghost-chu** [comment]
TravisCI will auto-upload builds to my BinaryRepo, check it. Include PR

**Comment by Ghost-chu** [comment]
There is: https://github.com/Ghost-chu/BinaryRepository

**Comment by portlek** [comment]
I'm not talking about that. I said we can release the build on the Spigot with -dev prefix. The server owners don't care this repo I think.
