### ISSUE TITLE
[BUG] Some languages are broken and will not load

### ISSUE THREAD

**Issue by a3s** [Ghost-chu/QuickShop-Reremake#234]
**Describe the bug**
RU, ES, DE, JA, KO languages have incorrect yml syntax and will not load.

**To Reproduce**
1. Open specified language files
2. Validate yml file
3. See error

**Expected behavior**
Files should have correct syntax.

**Additional context**
RU:
```
  toggle-unlimited:
    unlimited: "&aShop is now unlimited"
    limited: "&aShop is now limited"
    ? ""
      : "&aМагазин теперь {0}"
```
ES:
```
    limited: "&aShop is now limited"
    ? ""
      : "&aLa tienda está {0}"
```
etc.

I guess something is broken in language generation.

**Comment by Ghost-chu** [comment]
I will feedback this issue to OneSkyApp platform.

**Comment by Ghost-chu** [comment]
fixed, new version migrate to JSON format
