### ISSUE TITLE
[BUG] Economy username cannot be null (Essentials Economy)

### ISSUE THREAD

**Issue by Corenb** [Ghost-chu/QuickShop-Reremake#237]
Spam in logs with latest version (2.4.8.7):

https://pastebin.com/ZERGn5xY

**Comment by portlek** [comment]
Thank you for the report, It will be fixed next release.

**Comment by Ghost-chu** [comment]
Problem at
```
final double ownerBalance = eco.getBalance(shop.getOwner());
```
at PlayerListener.java, shop owner is null,

**Comment by portlek** [comment]
Shop owner method has @NotNull annotations so it shouldn't be null.

**Comment by Ghost-chu** [comment]
> Shop owner method has NotNull annotations so it shouldn't be null.

Yes it impossible be null.
But if bukkit getOfflinePlayer(UUID) can't get player, it won't return null, so qs shouldn't exception. But economy plugin may not. It maybe can't process this correctlly.

**Comment by Ghost-chu** [comment]
This looks thorwed by Essentials, quickshop can't block it.
And you probably reset Essentials user data before or set shop owner to a invaild user.
