### ISSUE TITLE
[BUG] Staff list Remove after each Restart

### ISSUE THREAD

**Issue by JamesBach93** [Ghost-chu/QuickShop-Reremake#239]
**Describe the bug**

**To Reproduce**

**Expected behavior**
After each Restart the Staff List ist Empty.
First i create an Shop, and i put Someone in the Staff list.
Than i Restart the Server and it shows this (screenshot) what happend after every Restart.
The Restarts on my Server are on 00:00 and 12:00.

**Screenshots**
https://i.imgur.com/Lbca9Fh.png

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/mz3cf62pXr/

**Additional context**

**Comment by Ghost-chu** [comment]
Require have a deep check on ContainerShop and DatabaseHelper

**Comment by JoschuaSchneider** [comment]
As far as I can see, there is no representation of staff in the Database. So calling update after a moderation change does not save staff anywhere.

So its only in memory until the server restarts.

**Comment by Ghost-chu** [comment]
> As far as I can see, there is no representation of staff in the Database. So calling update after a moderation change does not save staff anywhere.
> 
> So its only in memory until the server restarts.

The moderators save as owner in database.
```
{"owner":"43b89a96-d161-47e0-a854-f1c301c016a0","staffs":[]}
```
but yes, it doesn't saved.

**Comment by Ghost-chu** [comment]
There actually will udpate the moderator infomations,
https://github.com/Ghost-chu/QuickShop-Reremake/blob/904f1a4c0019d80f21764b39ff73ecbedd9b0847/src/main/java/org/maxgamer/quickshop/Shop/ContainerShop.java#L220

And it should write to database:
https://github.com/Ghost-chu/QuickShop-Reremake/blob/904f1a4c0019d80f21764b39ff73ecbedd9b0847/src/main/java/org/maxgamer/quickshop/Database/DatabaseHelper.java#L202

And no sql exception throwed. Need go deeper for find reason.

**Comment by JoschuaSchneider** [comment]
I see, so the error is either incorrect serialization or the data actually gets saved but not initialized.

I did not quickly find the code where you setup the ShopModerator but this could be it:
https://github.com/Ghost-chu/QuickShop-Reremake/blob/904f1a4c0019d80f21764b39ff73ecbedd9b0847/src/main/java/org/maxgamer/quickshop/Shop/ShopModerator.java#L57

The constructor with staffs does not set the staffs.

**Comment by JoschuaSchneider** [comment]
I just tested, and that does not seem to be the cause of the problem.

As you said, it does not reach the database. I'll continue searching for other clues.

The constructor should still be fixed I think.

**Comment by JamesBach93** [comment]
Hello, i have one Problem with this too.
I get an really big error in the console when a player hit the "AdminShop" Sign. (Only on AdminShop)
To sell his Stuff in the AdminShop. When i try /qs paste i get an empty page but i dont have switch something, that means the Paste on this issue is the Same. =)

**Comment by JoschuaSchneider** [comment]
The paste for this issue is not empty and the issue you have seems unrelated.

I would create a separate issue using the template so that the dev can keep track of it even if this issue gets resolved 😊
