### ISSUE TITLE
(feature request) Type amount on a sign instead of chat

### ISSUE THREAD

**Issue by arboriginal** [Ghost-chu/QuickShop-Reremake#24]
It could be confusing for players to have to type in the chat directly.
It results some times in number randomly posted in the game chat :)

Not something urgent but it could be nice to display a sign to let them type in it.
I saw this in other plugins so it's possible but don't know if complex.

**Comment by Ghost-chu** [comment]
QuickShop have a stupid trade process from upstream, This cause We cannot change it easy.
But maybe one day we will rewrite that part :)
