### ISSUE TITLE
[BUG] Enchanted books bug

### ISSUE THREAD

**Issue by CircusCow** [Ghost-chu/QuickShop-Reremake#240]
Creating a chesthop with an item like an enchanted book will register the enchants to that sign. But the shop will sell ANY enchanted book in it's slot regardless of a match to enchants
Enchanted books all share the same name "Enchanted Book" while potions have individual names, and sub-item-ids which makes sense why they would be protected from this

**Comment by Ghost-chu** [comment]
EnchantStorage different with enchant on the tools/armor, this is a bug.
It will fix in next release (one week after).

Please provide the paste to help us fix the bugs.(/qs paste)
