### ISSUE TITLE
QuickShop Reremake Problem

### ISSUE THREAD

**Issue by ChaosAndre** [Ghost-chu/QuickShop-Reremake#241]
Hallo.undzwar if a player buys something and he enters the number in the chat, it sees every other player this number.

**Comment by Ghost-chu** [comment]
This issue cause by your installed chat plugin, please check it before reporting.

**Comment by ChaosAndre** [comment]
I have no chat plugin installed

**Comment by Ghost-chu** [comment]
Must provide the paste link.
/qs paste
**Please use template next time**

**Comment by ChaosAndre** [comment]
https://paste.ubuntu.com/p/5DWRsckNm4/

**Comment by Ghost-chu** [comment]
Please disable the `disable-debuglogger` before reporting.
And enable `force-bukkit-chat-handler` then try again.

**Comment by cakoyo** [comment]
Unlikely to happen, try the latest version or give clear steps to reproduce. You feel free to open a new issue.
