### ISSUE TITLE
Can't change decimal notation for prices

### ISSUE THREAD

**Issue by lookez** [Ghost-chu/QuickShop-Reremake#242]
I'd like to change the price from looking like xxx,xxx,xxx.xx to xxxxxxxxx.xx since commas and dots are so similar on signs and cause a lot of confusion, but no matter what I change in "decimal-format" (with use-deciaml-format = true already) the price remains full of commas, am I doing something wrong or is this feature bugged?

**Comment by portlek** [comment]
It will be fixed in the next release.

**Comment by Ghost-chu** [comment]
fixed in next release
