### ISSUE TITLE
[BUG] DisplayItem bug on shop clean (armorstand option)

### ISSUE THREAD

**Issue by Futurixel** [Ghost-chu/QuickShop-Reremake#245]
**Describe the bug**
When cleaning empty shops using /qs clean, the displayItems do not delete themselves correctly. 

**To Reproduce**
1. Have some empty shops 
2. Config display-type set to 1 (armorstands)
3. Do /qs clean when chunk is unloaded

**Expected behavior**
Deletion of all shop displays deleted after /qs clean even chunks are not loaded. Maybe save infos of deleted shops temporarily and then delete displayitems once the chunk loads?

**Screenshots**
![image](https://user-images.githubusercontent.com/52638579/70611171-0b67fd00-1c05-11ea-9787-8ba826911524.png)

**Paste link:**
Server restarted after the clean so i don't have the QS Paste

**Additional context**
Running on latest build of Paper-Spigot 1.14.4
Running on latest build QuickShop 2.4.8.7

**Comment by Ghost-chu** [comment]
Require the paste(/qs paste when server running) and crash-report/latest.log files.

**Comment by Ghost-chu** [comment]
I have add a special mark, it allow you remove with 3rd party or quickshop purger(not add yet) feature to remove dupes display.
