### ISSUE TITLE
[BUG] Modified message will being reset after loaded

### ISSUE THREAD

**Issue by moontai0724** [Ghost-chu/QuickShop-Reremake#253]
**Describe the bug**
After modified messages.yml file, some messages will auto reset to default (English).

**To Reproduce**
1. Modify 'message.yml'
2. Start server
3. Check result

**Additional context**

Here's a list I confirmed that will reset to English:
- not-a-number
- not-a-integer
- purchase-failed
- no-pending-action
- permission-denied-3rd-party
- how-many-buy
- how-many-sell
- command/toggle-unlimited/unlimited
- command/toggle-unlimited/limited
- cmmand/description/owner
- cmmand/description/remove
- cmmand/description/amount
- cmmand/description/about
- cmmand/description/help
- cmmand/description/supercreate
- updatenotify/onekeybuttontitle
- updatenotify/remote-disable-warning
- shop-removed-cause-ongoing-fee

**Comment by Ghost-chu** [comment]
Try set `language-version` to 24 and execute /qs reload

**Comment by moontai0724** [comment]
Hi,
Thanks for fast reply,
the `language-version` in messages.yml is already set to 24 by default, still.
I have even tried set to 23 or 25, both not working properly.

**Comment by Ghost-chu** [comment]
Can you provide a paste (/qs paste) on this issue?

**Comment by moontai0724** [comment]
Hi,
Here's the link: [https://paste.ubuntu.com/p/vMs2NjFWGc/](https://paste.ubuntu.com/p/vMs2NjFWGc/).

Chinese inside seems fail to display caused by encoding,
here's a full content of messages.yml: [before loading](https://gist.github.com/moontai0724/23a52be49c0ea489531d5c3110b5ed24) [after loading](https://gist.github.com/moontai0724/2f192563e5a0f869b6fab5995a878856)

**Comment by Ghost-chu** [comment]
```
language-version: '24'
```
this can't be a yaml string, must is int.

```
language-version: 24
```

**Comment by moontai0724** [comment]
Hi,
I tried both string or number,
it will turn into string after loaded anyway.

**Comment by Ghost-chu** [comment]
We are finished new language system.
You can translate files on https://quickshop.oneskyapp.com

**Comment by moontai0724** [comment]
Thanks for your excellent reply,
I have finished zh_TW few days ago.

BTW, I noticed plugin updated today,
but still using deprecated language translation.

**Comment by Ghost-chu** [comment]
you need delete messages.json to let plugin regen.
