### ISSUE TITLE
[BUG] Shops Reset after Restart

### ISSUE THREAD

**Issue by JamesBach93** [Ghost-chu/QuickShop-Reremake#259]
**Describe the bug**

**To Reproduce**

**Expected behavior**
After an Restart, the AdminShop and UserShops are removed.
The Signs are there but nothing happend after klick on this sign.

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/bcmpXvjd36/

**Additional context**
I tried the lastest Version. After this i have this problem. Now i switched to the version befor 1.15
After each restart, i have to make the AdminShop new.. again and again and again :/

**Comment by Ghost-chu** [comment]
```
java.lang.IllegalArgumentException: Newer version! Server downgrades are not supported!
```
You can't downgrade the Spigot/Minecraft version, this is error from Spigot, please reset your database after downgrade.
