### ISSUE TITLE
(minor) Error message not translatable

### ISSUE THREAD

**Issue by arboriginal** [Ghost-chu/QuickShop-Reremake#26]
When trying remove a shop with admin permissions by using the "remove" in the sign:
"You do not have permission to use that command. Try break the shop instead?"

This sentence should be in the translatable sentences (messages.yml).

But maybe it's a bug: Admin shouldn't be able to use the remove link?
**Edit:** Forgot to say... Breaking the chest works.

**Comment by Ghost-chu** [comment]
Thanks report, All error messages is hard-coding, It is orgion version issue, it will add into message.yml.
Thanks report :)
