### ISSUE TITLE
MySQL error on 2.4.9

### ISSUE THREAD

**Issue by Corenb** [Ghost-chu/QuickShop-Reremake#260]
QuickShop v2.4.9 with MariaDB:

`>.... [23:36:53 WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xCE\xB20,00...' for column `s1_survie`.`qs_messages`.`message` at row 1
>.... [23:36:53 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
>.... [23:36:53 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
>.... [23:36:53 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
>.... [23:36:53 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
>.... [23:36:53 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
>.... [23:36:53 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
>.... [23:36:53 WARN]: at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
>.... [23:36:53 WARN]: at org.maxgamer.quickshop.Database.DatabaseManager.runTask(DatabaseManager.java:107)
>.... [23:36:53 WARN]: at org.maxgamer.quickshop.Database.DatabaseManager.access$000(DatabaseManager.java:22)
>.... [23:36:53 WARN]: at org.maxgamer.quickshop.Database.DatabaseManager$1.run(DatabaseManager.java:59)
>.... [23:36:53 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [23:36:53 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [23:36:53 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [23:36:53 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [23:36:53 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [23:36:53 WARN]: at java.lang.Thread.run(Thread.java:748)`

**Comment by Ghost-chu** [comment]
Can you run command `/qs paste` after this error appear again?

**Comment by portlek** [comment]
ping @Corenb

**Comment by Corenb** [comment]
I think it was a bug due to my MariaDB server... I have no longer this error after a reinstallation
