### ISSUE TITLE
[BUG] BlockBreakEvent fired when try create a shop

### ISSUE THREAD

**Issue by nokisenpai** [Ghost-chu/QuickShop-Reremake#262]
**Describe the bug**
The event "BlockBreakEvent" is fired when we try create a shop.

**To Reproduce**

1. Place a simple chest
2. Do simple left click on the chest with an item in main hand (to request shop creation)
3. See from an other plugin that the event "BlockBreakEvent" is fired.

**Expected behavior**
The event "BlockBreakEvent" Should not be fired. We don't break the chest. We just "hit" it.

**Screenshots**
//If applicable, add screenshots to help explain your problem.

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/9PWbCnBG5R/

**Additional context**
I catch the event "BlockBreakEvent" with my own plugins (a jobs plugin and a sorter plugin).
My jobs plugin use BlockBreakEvent to give money when a player break a chest.
My sorter plugin use BlockBreakEvent to delete a sorter registered on a chest.

Edit : 
I found this : 
"1. Set nothing drops in our custom BlockBreakEvent, make sure other plugin don't process the event incorrectly."
From : 
https://www.spigotmc.org/resources/quickshop-reremake-1-15-ready-bees-bees-bee.62575/update?update=295324

But leaves, spawner and tallgrass may doesn't drop anything. Which is a problem for my jobs plugin.

**Comment by Ghost-chu** [comment]
This is protection check
