### ISSUE TITLE
QuickShop debug?

### ISSUE THREAD

**Issue by jordanwilliams1** [Ghost-chu/QuickShop-Reremake#263]
Why is my console spammed with QuickShop debug? Downloaded latest version from spigot today.

https://i.gyazo.com/846a0bcf1d2996746f6f5e5de268f9b3.png

config.yml
disable-debuglogger: true

**Comment by Ghost-chu** [comment]
/qs debug




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jordanwilliams1"<notifications@github.com&gt;; 
发送时间: 2019年12月21日(星期六) 下午5:49
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Ghost-chu/QuickShop-Reremake] QuickShop debug? (#263)




Why is my console spammed with QuickShop debug? Downloaded latest version from spigot today.
 
https://i.gyazo.com/846a0bcf1d2996746f6f5e5de268f9b3.png
 
disable-debuglogger: true

**Comment by jordanwilliams1** [comment]
@Ghost-chu thank you.
