### ISSUE TITLE
Failed to deposit the money for player CraftOfflinePlayerUG

### ISSUE THREAD

**Issue by erDUKE21** [Ghost-chu/QuickShop-Reremake#264]
If a player try to buy on a shop when his owner are disconnected, the console show me this.

>.... [00:53:33 WARN]: [QuickShop] Failed to deposit the money for player CraftOfflinePlayer[UUID=49b619a3-548d-3a49-a43c-a7fc24a7b5ec]

Why?

**Comment by Ghost-chu** [comment]
You using a trash economy plugin, change one.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "erDUKE21"<notifications@github.com&gt;; 
发送时间: 2019年12月22日(星期天) 上午9:01
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Ghost-chu/QuickShop-Reremake] Failed to deposit the money for player CraftOfflinePlayerUG (#264)




If a player try to buy on a shop when his owner are disconnected, the console show me this.
  
.... [00:53:33 WARN]: [QuickShop] Failed to deposit the money for player CraftOfflinePlayer[UUID=49b619a3-548d-3a49-a43c-a7fc24a7b5ec]
  
Why?

**Comment by erDUKE21** [comment]
I'm using TheNewEconomy, is that bad?

**Comment by portlek** [comment]
I guess it is not using Vault @erDUKE21 so maybe the problem is that
