### ISSUE TITLE
[Feature] Combo shops (shops that buy and sell)

### ISSUE THREAD

**Issue by TT10** [Ghost-chu/QuickShop-Reremake#265]
It would be nice to have combo shops that buy and sell.
Many shop plug-ins have it and it's very handy for shop owners.
By the way, it should be done in a way that doesn't confuse shop customers (which some other plug-ins fail at).

It would also be nice for shop owners if it checks that buy price is inferior to sell price.

**Comment by donut4490** [comment]
Most of this can be done with two signs on a double chest.

**Comment by TT10** [comment]
Yes but that mean you "have to" build with double chest everywhere, so that's a constraint.

And also, signs do not update properly on double chests ( about this, also see: https://github.com/Ghost-chu/QuickShop-Reremake/issues/268 )

**Comment by Ghost-chu** [comment]
Closed due we had no plan to add that yet
