### ISSUE TITLE
InventoryCloseEvent

### ISSUE THREAD

**Issue by CaliDreams** [Ghost-chu/QuickShop-Reremake#27]
I'm running into this error in console constantly spamming me:

https://pastebin.com/xDEZFH7P

I don't know if maybe it's a compatibility issue with CMI's GUI's? I'm using your latest version of this plugin (1.3.0) with CMI 8.0.23.0 on a 1.13.2

**Comment by Ghost-chu** [comment]
I will check it and try fix it.
Thanks report it :)

**Comment by Ghost-chu** [comment]
Fixed in 1.3.0.1
