### ISSUE TITLE
[QUESTION] Possible bug. I keep getting notifications that a player has bought from my shop when it's actually an admin shop.

### ISSUE THREAD

**Issue by donut4490** [Ghost-chu/QuickShop-Reremake#270]
Not sure if this is a bug or if I just can't figure out how to turn it off.

**Comment by judgetread** [comment]
Have you set:

`ignore-unlimited-shop-messages: true`

Turns off messages when player buys from a unlimited shop

**Comment by donut4490** [comment]
How did I not see that. Thanks lol
