### ISSUE TITLE
[PERFORMANCE] InventoryMoveEvent

### ISSUE THREAD

**Issue by Fabrimat** [Ghost-chu/QuickShop-Reremake#275]
![image](https://user-images.githubusercontent.com/13642582/71547677-3abb8f80-29a3-11ea-8edc-925e7ff9a90d.png)
I noticed that this method is using a lot of resources, going into the code it seems to be the sign update when hoppers add items.
Can you add an option to disable that listener? I am not using that feature and it's very heavy on my cpu.

If you need the paste and other stuff just tell me and I will upload them.
Thank you in advance

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/issues/267

**Comment by Fabrimat** [comment]
> #267

I don't understand much lol

**Comment by Ghost-chu** [comment]
Now is scheduled update the sign.
