### ISSUE TITLE
[BUG] BlockBreakEvent called on chest

### ISSUE THREAD

**Issue by LoneDev6** [Ghost-chu/QuickShop-Reremake#276]
**Describe the bug**
BlockBreakEvent event is called when you left click a chest with item to sell

**To Reproduce**
1. Create a simple plugin that listens to BlockBreakEvent 
2. Place chest
3. Left click on chest with an item and you see BlockBreakEvent  is called.
4. Unload plugin QuickShop
5. Click again on chest, you see BlockBreakEvent is not called

**Expected behavior**
No BlockBreakEvent event to be called

**Additional context**
Latest paper spigot build

**Comment by Ghost-chu** [comment]
#262

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/blob/master/src/main/java/org/maxgamer/quickshop/Util/PermissionChecker.java

**Comment by LoneDev6** [comment]
You should cancel the event so other plugins can check isCancelled

```
    public static boolean canBreak(Block block, Player player)
    {
        if(block.getType() == Material.AIR)
            return false;
        BlockBreakEvent b = new BlockBreakEvent(block, player);
        Bukkit.getServer().getPluginManager().callEvent(b);
        boolean can = false;
        if (!b.isCancelled())
            can = true;
        b.setCancelled(true);
        return can;
    }

```

**Comment by LoneDev6** [comment]
> 
> 
> You should cancel the event so other plugins can check isCancelled
> 
> ```
>     public static boolean canBreak(Block block, Player player)
>     {
>         if(block.getType() == Material.AIR)
>             return false;
>         BlockBreakEvent b = new BlockBreakEvent(block, player);
>         Bukkit.getServer().getPluginManager().callEvent(b);
>         boolean can = false;
>         if (!b.isCancelled())
>             can = true;
>         b.setCancelled(true);
>         return can;
>     }
> ```

@Ghost-chu

**Comment by sandtechnology** [comment]
> 
> 
> > You should cancel the event so other plugins can check isCancelled
> > ```
> >     public static boolean canBreak(Block block, Player player)
> >     {
> >         if(block.getType() == Material.AIR)
> >             return false;
> >         BlockBreakEvent b = new BlockBreakEvent(block, player);
> >         Bukkit.getServer().getPluginManager().callEvent(b);
> >         boolean can = false;
> >         if (!b.isCancelled())
> >             can = true;
> >         b.setCancelled(true);
> >         return can;
> >     }
> > ```
> 
> @Ghost-chu

It Already cancelled...........
https://github.com/Ghost-chu/QuickShop-Reremake/blob/2d675d23feaac1d9c73b86e8dc568bdbd55b28a6/src/main/java/org/maxgamer/quickshop/Util/PermissionChecker.java#L111

**Comment by Ghost-chu** [comment]
Git toolbox say that written by you （ ’ - ’ * )



---Original---

**Comment by sandtechnology** [comment]
> 
> Git toolbox say that written by you （ ’ - ’ * )
> […](#)
> ---Original--- From: "sandtechnology"<notifications@github.com&gt; Date: Sun, Apr 5, 2020 01:25 AM To: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; Cc: "Mention"<mention@noreply.github.com&gt;;"Ghost_chu"<wyf001912hp@gmail.com&gt;; Subject: Re: [Ghost-chu/QuickShop-Reremake] [BUG] BlockBreakEvent called on chest (#276) You should cancel the event so other plugins can check isCancelled public static boolean canBreak(Block block, Player player) { if(block.getType() == Material.AIR) return false; BlockBreakEvent b = new BlockBreakEvent(block, player); Bukkit.getServer().getPluginManager().callEvent(b); boolean can = false; if (!b.isCancelled()) can = true; b.setCancelled(true); return can; } @Ghost-chu It Already cancelled........... https://github.com/Ghost-chu/QuickShop-Reremake/blob/2d675d23feaac1d9c73b86e8dc568bdbd55b28a6/src/main/java/org/maxgamer/quickshop/Util/PermissionChecker.java#L111 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

nvm, just remind it already implemented

**Comment by LoneDev6** [comment]
> 
> 
> > > You should cancel the event so other plugins can check isCancelled
> > > ```
> > >     public static boolean canBreak(Block block, Player player)
> > >     {
> > >         if(block.getType() == Material.AIR)
> > >             return false;
> > >         BlockBreakEvent b = new BlockBreakEvent(block, player);
> > >         Bukkit.getServer().getPluginManager().callEvent(b);
> > >         boolean can = false;
> > >         if (!b.isCancelled())
> > >             can = true;
> > >         b.setCancelled(true);
> > >         return can;
> > >     }
> > > ```
> > 
> > 
> > @Ghost-chu
> 
> It Already cancelled...........
> 
> https://github.com/Ghost-chu/QuickShop-Reremake/blob/2d675d23feaac1d9c73b86e8dc568bdbd55b28a6/src/main/java/org/maxgamer/quickshop/Util/PermissionChecker.java#L111

ok.................................................

lol.
