### ISSUE TITLE
[BUG] Shops deleted after reload

### ISSUE THREAD

**Issue by GamerDerock** [Ghost-chu/QuickShop-Reremake#278]
**Describe the bug**
Whenever the plugin is reloaded or restarted, it will lose all info about the chest shops; ergo all chest shops are disabled. I have found that it saves the shops to `shops.db` using the SQLite format, and after reading the file, all shops appear on the file, meaning it happens when loading the file. I have kept all database options default.

**To Reproduce**
1. Create a chest shop.
2. Do /qs reload or restart the server.
3. Try and use the shop.

**Expected behavior**
I expect, after a restart, for all the shops to still be functional.

**Screenshots**

**Paste link:**
_File was too large to upload to pastebin or hastebin (file: 2.5mb) so see attached file
[paste-f4ea133dd45346c9921a8f1c0e2b230d.txt](https://github.com/Ghost-chu/QuickShop-Reremake/files/4016104/paste-f4ea133dd45346c9921a8f1c0e2b230d.txt)
_
**Additional context**
nothing else : )

**Comment by Ghost-chu** [comment]
Can you execute `/qs paste` again after you execute `/qs reload`, so i can see details of loading shops?
Also please upload your `shops.db` file.

**Comment by GamerDerock** [comment]
After a restart and a `/qs reload`: [https://paste.enginehub.org/DW5tvvg4](https://paste.enginehub.org/DW5tvvg4)
`shops.db`: [https://drive.google.com/file/d/1uU_ewiCTBozzhfg6-0ky3HQr47U3Q8Z8/view?usp=sharing](https://drive.google.com/file/d/1uU_ewiCTBozzhfg6-0ky3HQr47U3Q8Z8/view?usp=sharing) _Couldn't upload file to GitHub, since it only supports GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX, or ZIP_

**Comment by GamerDerock** [comment]
**Issue Fixed**
**Steps to fix: **
    1. Delete (or rename) your `shops.db`
    2. Reload the plugin
_Somehow the `shops.db` file was broken_
