### ISSUE TITLE
[BUG] Console reports missing config strings

### ISSUE THREAD

**Issue by derMiepz** [Ghost-chu/QuickShop-Reremake#281]
**Describe the bug**
The console tells me that `use-decimal-format: false` is missing and that I could add `auto-fix-configuration: true` to automatically fix this. The first thing was already there, and even after adding the latter and restarting the server, the issue persists. (see screenshot)

**To Reproduce**
1. Install QS (in my case 3.0.0)
2. Restart the server
3. Add missing strings to config
4. Restart again
5. Check the console if the issue persists

**Expected behavior**
The warning should disappear after adding said strings

**Screenshots**
![](https://i.imgur.com/eOzsiNG.png)

**Paste link:**
 Execute command `/qs paste`, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/VYNqVs86QW/
(This is the original /qs paste output. I just removed my DB password)

**Additional context**

**Comment by Ghost-chu** [comment]
auto fixer fixed it but not saved... so it still here.

**Comment by Ghost-chu** [comment]
plugin require `use-decimal-format` but actually in config is `use-deciaml-format`

somebody pull request broken it.

**Comment by derMiepz** [comment]
Good catch! I completely skipped that :D 
I was about to say that I saved the config manually so it'd be weird that it's still happening ^^
