### ISSUE TITLE
[BUG] Tab Completer 

### ISSUE THREAD

**Issue by JamesBach93** [Ghost-chu/QuickShop-Reremake#282]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Hey, after the Update i get some errors in my Console and QS doesnt work.
When i used /qs, it checks after each Letter any Tab Completer. 

01:40:04 CONSOLE: ERROR]: Exception when James_Bach attempted to tab complete qshop
01:40:04 CONSOLE: exception during tab completion for command '/qshop ' in plugin QuickShop vReremake 3.0.0
01:40:04 CONSOLE: java.lang.IllegalStateException: zip file closed
01:40:05 CONSOLE: ERROR]: Exception when James_Bach attempted to tab complete qshop p
01:40:05 CONSOLE: exception during tab completion for command '/qshop p' in plugin QuickShop vReremake 3.0.0
01:40:05 CONSOLE: java.lang.IllegalStateException: zip file closed
01:40:05 CONSOLE: ERROR]: Exception when James_Bach attempted to tab complete qshop pa
01:40:05 CONSOLE: exception during tab completion for command '/qshop pa' in plugin QuickShop vReremake 3.0.0
01:40:06 CONSOLE: java.lang.IllegalStateException: zip file closed
01:40:06 CONSOLE: ERROR]: Exception when James_Bach attempted to tab complete qshop pas
01:40:06 CONSOLE: exception during tab completion for command '/qshop pas' in plugin QuickShop vReremake 3.0.0
01:40:06 CONSOLE: java.lang.IllegalStateException: zip file closed
01:40:06 CONSOLE: ERROR]: Exception when James_Bach attempted to tab complete qshop past
01:40:06 CONSOLE: exception during tab completion for command '/qshop past' in plugin QuickShop vReremake 3.0.0
01:40:06 CONSOLE: java.lang.IllegalStateException: zip file closed
01:40:06 CONSOLE: ERROR]: Exception when James_Bach attempted to tab complete qshop paste
01:40:06 CONSOLE: exception during tab completion for command '/qshop paste' in plugin QuickShop vReremake 3.0.0
01:40:07 CONSOLE: java.lang.IllegalStateException: zip file closed
01:40:07 CONSOLE: [INFO] James_Bach issued server command: /qshop paste
01:40:07 CONSOLE: ERROR]: null
01:40:07 CONSOLE: execute command 'qshop' in plugin QuickShop vReremake 3.0.0 - plugin is disabled.

**Screenshots**
https://i.imgur.com/sDBywE9.png

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【REPLACE ME TO PASTE LINK】<- I dont have a Paste Link. The Plugin is disabled :/ 

**Additional context**

**Comment by Ghost-chu** [comment]
jar broken, redownload and restart server



---Original---

**Comment by JamesBach93** [comment]
Thx, i have do this but after remove the Config file it works. :)
