### ISSUE TITLE
[BUG] /qs update throws an exception

### ISSUE THREAD

**Issue by derMiepz** [Ghost-chu/QuickShop-Reremake#283]
**Describe the bug**
QS told me ingame that there's an update available. After clicking on [OneKey Update], QS throws an exception: https://paste.enginehub.org/6UdNgxWE Same thing happens when using /qs update manually.

**To Reproduce**
1. Issue /qs update
2. Check the console

**Expected behavior**
QS should update normally. In case the the fails, it should at least inform the user that something gone wrong and that they should check the console for more information.

**Screenshots**
![](https://i.imgur.com/HnaJ8tz.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/ry9rB-D-

**Comment by Ghost-chu** [comment]
it's looks internet issue snd plugin didn't execute null check, please update by your self and i will fix it in next version.

**Comment by derMiepz** [comment]
Alright will do. :)
