### ISSUE TITLE
[BUG] QS throws a NullPointerException when issuing /ec

### ISSUE THREAD

**Issue by derMiepz** [Ghost-chu/QuickShop-Reremake#284]
Welp, it's me again...

**Describe the bug**
Title says it all. Error: https://paste.enginehub.org/lEh_Xs5P

**To Reproduce**
1. Start the server
2. Wait until it's fully started
3. Issue /ec
4. Check the console

**Expected behavior**
QS seems to work after the exception is thrown. It shouldn't throw an exception

**Screenshots**
No screenshots

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/xE1Psi1i

**Additional context**
Reproducible: Every time.
I'm using CMI instead of Essentials. Not sure if this is related to the problem.

**Comment by Ghost-chu** [comment]
Outdated quickshop, please update

**Comment by derMiepz** [comment]
Same thing happens with the newest version v3.0.1 https://paste.enginehub.org/s_RrnpNt

**Comment by Ghost-chu** [comment]
this not qs issue, please don't report to me, you should contact that plugin author


qs just hooked wrong throw, it actually not quickshop fault.



---Original---

**Comment by derMiepz** [comment]
Alright will do. But thanks for your time. :)
