### ISSUE TITLE
[BUG] The plugin does not translate into another language

### ISSUE THREAD

**Issue by Denias3** [Ghost-chu/QuickShop-Reremake#286]
**Describe the bug**
The plugin does not translate into another language

**To Reproduce**
1. Changed this line in configs
language: ru
2. Wrote a team
/qs reload
3. The plugin has not been translated into Russian

**Expected behavior**
The plugin should be in Russian

**Screenshots**
Not necessary

**Paste link:**
https://docs.google.com/document/d/1-fh46qB5EJXZIQmIFkBDcWSUbLgKBf13lKY49_E6JDM/edit?usp=sharing

**Additional context**
As far as I understand the translation does not work at all. Even to other languages

**Comment by Ghost-chu** [comment]
auto-saving language system broken, thanks for feedback
