### ISSUE TITLE
[Feature] Staffmember Feature

### ISSUE THREAD

**Issue by JamesBach93** [Ghost-chu/QuickShop-Reremake#289]
**Describe the Feature**
Some of my Players have some Shops (Chest) Together.
But they need ohne Feature that all Staffmembers from the Chest become
an message to when the Chest is Empty. 

**Screenshots**
If applicable, add screenshots to help explain your feature.

**Additional context**
Same Feature like /qs staff add Username. But when the Chest is Empty all Staffmembers get an Message that the Shop with "wool" or something got Empty.

**Comment by Ghost-chu** [comment]
use `shop.sending-stock-message-to-staffs`
