### ISSUE TITLE
[Suggestion] Towny support

### ISSUE THREAD

**Issue by LuisGVE** [Ghost-chu/QuickShop-Reremake#29]
Please add support for Towny (like sho plots, etc) like this: https://dev.bukkit.org/projects/quickshop-towny-interop

**Comment by LuisGVE** [comment]
You can add this?

**Comment by LuisGVE** [comment]
Some plugins allow to delete the players' files through commands, for example /ta delete Golvore ta (delete Towny data of Golvore)

**Comment by Ghost-chu** [comment]
No, It should make a addon by other developers not QSRR
