### ISSUE TITLE
[BUG] Hopper next to shop causes chat spam for OPs

### ISSUE THREAD

**Issue by Weasel-Beans** [Ghost-chu/QuickShop-Reremake#291]
This hopper is not connected to the shop chest, yet it still leads to very annoying chat spam for me.

https://i.imgur.com/6MYsPK9.png

**Comment by Ghost-chu** [comment]
It not steam shop item, is display item.
Also you can turn of that spam in config.yml "send-display-item-protection-alert: true" to false

**Comment by Weasel-Beans** [comment]
Yes I found that option. However that does not disable the spam in the console.

https://i.imgur.com/PsTPpIl.png

Also, the display items are disabled on my server, so this seems totally unnecessary.

**Comment by Weasel-Beans** [comment]
In-fact, I don't think that 

`send-display-item-protection-alert: false`

Works at all. I'm still seeing the spam in-game and on the console.
