### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NEIKI19914** [Ghost-chu/QuickShop-Reremake#293]
**Describe the bug**
Essentialsx-2.17.1.48 is not linked to the economic part of quickshop-remake.3.0.2, and vault is installed. It's like two wallets.

**To Reproduce**
At present, there are only 2 players, no abnormal operation. It happens after selling things.

**Expected behavior**
I hope there is a solution.

**Screenshots**
No screenshots.

**Paste link:**
https://paste.enginehub.org/oJpU14NM
- 【REPLACE ME TO PASTE LINK】

**Additional context**
Unknown at present

**Comment by Ghost-chu** [comment]
尝试更新到3.0.3，另外看到essentials economy报异常，建议检查essentials economy，我这边是正常的



---Original---

**Comment by NEIKI19914** [comment]
> 尝试更新到3.0.3，另外看到essentials economy报异常，建议检查essentials economy，我这边是正常的
> […](#)
> ---Original--- From: "NEIKI19914"<notifications@github.com&gt; Date: Sat, Jan 11, 2020 04:29 AM To: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [Ghost-chu/QuickShop-Reremake] [BUG] (#293) Describe the bug Essentialsx-2.17.1.48 is not linked to the economic part of quickshop-remake.3.0.2, and vault is installed. It's like two wallets. To Reproduce At present, there are only 2 players, no abnormal operation. It happens after selling things. Expected behavior I hope there is a solution. Screenshots No screenshots. Paste link: https://paste.enginehub.org/oJpU14NM 【REPLACE ME TO PASTE LINK】 Additional context Unknown at present — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

essentials economy报异常是因为BungeeTabListPlus的一个配置文件变量问题，在更新最新版本后那2名玩家还是如此。

**Comment by Ghost-chu** [comment]
问题无法复现

**Comment by cakoyo** [comment]
Tested with latest EssentialsX, Vault and unable to reproduce. Are you purchasing from a store that you own? Feel free to open a new issue if you got new information. Thanks.
