### ISSUE TITLE
Add Ongoing Fee to Having a Chest

### ISSUE THREAD

**Issue by WHiZSTA** [Ghost-chu/QuickShop-Reremake#3]
We have a fee for creating a shop chest, and for changing a price on one. I'd like one that would be a daily or monthly fee to keep those chests as a way we can expire unused or unwanted shops and not just have shops that arent maintained or used cluttering things.

**Comment by Ghost-chu** [comment]
Finished in 5e65427e6ef1b8cf0a6945d9442795520344f309
