### ISSUE TITLE
QuickShop-Reremake.1.3.0.5 warning in console

### ISSUE THREAD

**Issue by arboriginal** [Ghost-chu/QuickShop-Reremake#30]
I suppose it's because the Spigot page has moved...

Complete error here:
https://gist.github.com/arboriginal/b43d12db459e3c9dafe8f592495b94b7

(Sorry if fixed in very last updates but as I didn't receive Spigot notification, don't know if there are new public ones.)

**Comment by Ghost-chu** [comment]
Because we resource removed by SpigotMC, and we update checker use SpigotMCAPI, so you need update to new QSRR.
