### ISSUE TITLE
[BUG] 'auto-fix-configuration: true' breaks the plugin.

### ISSUE THREAD

**Issue by Weasel-Beans** [Ghost-chu/QuickShop-Reremake#301]
I added `auto-fix-configuration: true` to my plugin and reloaded it, and got these errors:

https://pastebin.com/xLszeuKf

This worked properly on a test server, but not on my live server for some reason. I had to restart with the string removed to fix it.

**Comment by cakoyo** [comment]
The feature was removed, though still unable to reproduce.
