### ISSUE TITLE
The plug-in fails, and the background keeps flashing errors 【插件失效，后台不停的刷报错】

### ISSUE THREAD

**Issue by 1425115471** [Ghost-chu/QuickShop-Reremake#303]
spigot1.14.4
QuickShop-Reremake.3.0.8.1

![2668JSM_MTFIQT6@UP}I1$S](https://user-images.githubusercontent.com/29402452/72613652-1d0e9400-396b-11ea-9784-aba02637ad26.png)

#=========================
Sorry, my English is not very good. I gave you a screenshot of this error report
After running for 3-4 days, there are only 1-2 error reports occasionally. This afternoon, the error reports suddenly continue to be swiped. Latest.log swipes a multig error file, and the plug-in cannot run. In the configuration file, I set update sign when inventory moving to false

Because the funnel of version 1.14.4 is too smooth.

The second error is that the previous versions also have some, that is, if someone else sells or buys something in his store when the store is not online, the owner of the store will not be prompted when it is online, and only when someone else sells or buys something in his store when the store owner is online will there be an information prompt.

Hope the author can repair it greatly
#======================中文
运行了3-4天只是偶尔出现了刷1-2个报错，今天下午突然不停的刷报错，latest.log刷了1个多G的报错文件，插件也无法运行。配置文件内我将update-sign-when-inventory-moving 设置为了 false
因为1.14.4版本漏斗过于影响流畅。

第二个错误是前几个版本也有的，就是如果商店不在线期间别人在他商店出售或者购买的东西，商店主人上线没有提示了，只有商店主人在线期间别人在他商店出售或者购买的东西才有信息提示。

希望作者大大修复~~感谢作者大大

**Comment by Ghost-chu** [comment]
Require **FULL** `latest.log` file and the link of  `/qs paste`

**Comment by 1425115471** [comment]
[latest.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/4077821/latest.zip)

**Comment by Ghost-chu** [comment]
我需要完整的latest.log，你自己不要删改。
直接重启一下服务器，看到报错第一次出现时立即关闭，然后 **整个latest.log文件** 完整发给我，不要做任何修改。
你这么一改丢失了大量关键信息，完全没有作用。

**Comment by cakoyo** [comment]
@Ghost-chu 我不认为他修改过，有时候确实会丢失原因字段，目前最好是检查一遍这个事件相关的代码。

**Comment by 1425115471** [comment]
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4079846/latest.log)

**Comment by 1425115471** [comment]
这是重启后的完整 log ,也出现了很多报错， 但是插件可以正常使用，除了还是有第二个错误
