### ISSUE TITLE
Remove lib and .idea folder from this repo

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#306]
**Describe the Feature**
I think it would beneficial to not have the `.idea` and `lib` folder removed for various reasons.
First of all would not everyone use IntelliJ when they fork and update this plugin (they might use eclipse or netbeans) and it's always better to let the IDE generate its own .idea folder.

Next do I believe that there *could* be conflicts in terms of license and such when you (re-)distribute the jars through the lib folder.
Not sure there.
You should also use maven dependencies where possible (Unless those jars are a result of using maven...)

**Screenshots**

**Additional context**
This is just a small suggestion.

**Comment by Ghost-chu** [comment]
* .idea folder only storage project encoding (in our country, project encoding always use GBK by default, this file will force ide use UTF8) and Copyright template to allow devs tobuse.

* lib folder contains jars and it used by Maven, because some plugin didn't have themself repo, so i storage them in local file system.

**Comment by cakoyo** [comment]
@Ghost-chu How about deploying the plugins in libs to your Github maven repo?

**Comment by Andre601** [comment]
> * .idea folder only storage project encoding (in our country, project encoding always use GBK by default, this file will force ide use UTF8) and Copyright template to allow devs tobuse.
> * lib folder contains jars and it used by Maven, because some plugin didn't have themself repo, so i storage them in local file system.

Neither `.idea` folder nor the `lib` folder need to be shared on GitHub. People that fork and import it into their IDE will automatically create their own folders and libs. And as long as you use maven as a dependency manager would it not require anyone to have local copies of the jar files.
I just suggest to remove them from your git push actions (and this repo) as again this isn't required here.

**Comment by Mgazul** [comment]
I agree to delete the .idea folder, I can try using Maven instead of lib
