### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skyrawr** [Ghost-chu/QuickShop-Reremake#307]
**Describe the bug**
Item Display Doesn't Spawn If Player Doesn't Click On The Shop And Sometimes Doesn't Despawn.

**To Reproduce**
1. See error. (you don't even have to be next to a shop for this, i dont know how to replicate this error, i think 1.15.2 is the problem but i'm not sure.)

**Expected behavior**
Item Display Should Spawn When Players Get Close.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/54551194/73070138-3f973480-3eb8-11ea-9ce8-19bd63c00a81.png)

**Paste link:**
- https://paste.ubuntu.com/p/KcQPGCcjpz/

**Additional context**
Paper-66
1.15.2
Essentials Economy

**Comment by Ghost-chu** [comment]
Please run test in clean server.

**Comment by skyrawr** [comment]
I tried in a clean server and the error does not reproduce, when i did /qs debug on the not clean server console got spammed with "[QuickShop] [DEBUG] [ShopManager] [getShopIncludeAttached_Classic] (1049) Not found shops use the attached util." thousands of times. do you know what this error means?

**Comment by cakoyo** [comment]
@Ghost-chu Threadsafe issue comes from AutoDespawn#checkDisplay.
@skyrawr Already fixed by recent commits, try the latest build.

**Comment by cakoyo** [comment]
Close as fixed.
