### ISSUE TITLE
[Feature] Improve version check

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#308]
**Describe the Feature**
Right now does the UpdateWatcher trigger even when the version on Spigot is lower than what you're using on your server (Probs due to caching or similar)
This is caused by the fact that the UpdateWatcher is checking if the version is equal to the one of the plugin, meaning that it returns false, when the version is higher OR lower.

https://github.com/Ghost-chu/QuickShop-Reremake/blob/b7c08c4fc465ff751a1b890cac4e85eab07654e3/src/main/java/org/maxgamer/quickshop/Watcher/UpdateWatcher.java#L63

My suggestion is to get the versions from Spigot and the plugin, split them at each dot, and check if major, minor or revision version of spigot are bigger than the one of the plugin.
That way would it only trigger when the version is actually greater than what the plugin currently is.

In addition would I also suggest to move from default Spigot to the Spiget API for better support with the Spigot API.

An example of a Update Checker with the Spiget API can be seen here:
https://github.com/Andre601/HelpGUI/blob/master/src/main/java/com/andre601/helpgui/util/UpdateCheck.java

**Screenshots**

**Additional context**

**Comment by Ghost-chu** [comment]
I think spiget awesome, but we still using SpigotMC api.
Think about to allow user or remote switch update checker source.

**Comment by sandtechnology** [comment]
Implemented:https://github.com/Ghost-chu/QuickShop-Reremake/compare/a1131f9765d805...210b0b9d2
