### ISSUE TITLE
[Feature] Change package names

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#309]
**Describe the Feature**
This is honestly quite a nitpicky thing, but I still want to mention and suggest it.
Right now are the package names (the folders) named in a First-uppercase way (f.e. Utils) which goes against general java conventions, where you name packages lowercase.

I suggest to actually update the packages to be all lowercase.

**Screenshots**

**Additional context**
In general Java coding are class names First upper-camelcase (QuickShop), packages completely lowercase (utils), methods lower camelcase (myMethod), final fields/variables all caps, etc.

The reason behind this is to distinguish the different types.
When I would only see the names, without knowing which is a package and which is a class could I not know if Utils is now a package or class because it is named in a similar way a class is named.
Meanwhile, when it is lowercase can I easily know that utils is a package since it is all lowercase.

**Comment by Ghost-chu** [comment]
Sadly it hard to do.
Yes, it pretty easy rename packages, but the first version of quickshop on bukkit, the author named packages begin with Uppercase.
If rename it, All addons will can't continue work.

So maybe you will wait a long time until v4 come out.

**Comment by Ghost-chu** [comment]
works done in v4 branch
