### ISSUE TITLE
Remove your local libraries especial your spigot builds.

### ISSUE THREAD

**Issue by yannicklamprecht** [Ghost-chu/QuickShop-Reremake#31]
Instead add the maven repositories and let maven do its thing.

Do you need any spigot implementation for your plugin or does the spigot API is enough for it?

**Comment by Ghost-chu** [comment]
We use special method in Spigot and it only include SpigotJAR not SpigotAPI

**Comment by yannicklamprecht** [comment]
The .spigot methods are available in Spigot-API already. No need for Spigot implementation.
The Brigadier API is added as provided dependency cause it's in the MinecraftServer itself.

See #32
