### ISSUE TITLE
Player login exception error quickshop ver. 3.1.3.1[BUG]

### ISSUE THREAD

**Issue by crispyklown81** [Ghost-chu/QuickShop-Reremake#312]
on player login on paper 1.13.2 with quickshop version 3.1.3.1 get this error.
https://pastebin.com/KF8LYaYH

**Comment by cakoyo** [comment]
Sorry for that, it's a version issue, and easy to fix.

**Comment by Ghost-chu** [comment]
Fixed in 3.1.3.3
