### ISSUE TITLE
[BUG] No Shops can be created

### ISSUE THREAD

**Issue by GeneralBibi** [Ghost-chu/QuickShop-Reremake#316]
**Describe the bug**
As an Admin with every permission i cant create shops with every command. 

**To Reproduce**
i dont know

**Expected behavior**
idk what that means

**Screenshots**
Sometimes i get this
![image](https://user-images.githubusercontent.com/54682507/73267151-b72ad380-41d8-11ea-950d-76ed413b8f7a.png)

AND MOST OF THE TIMES NOTHING HAPPENS, JUST NOTHING NO COMMAND

**Paste link:**
- 【https://paste.enginehub.org/NWLcs2cE】

**Additional context**
i think some plugins aint compatible

**Comment by Ghost-chu** [comment]
Some plugin cancelled shop creation, there is list for possible plugin.
UltraCustomizer，
BetterChairs，
EnchantmentSolution，
Graves，
SmoothTimber，
Minepacks，
BlockyLog，
WorldGuard，
ChestLockGui，
PublicCrafters，
Spartan，
Brewery，
CoreProtect，
BookShelf

Please remove these plugins one by one to find cause, and report to plugin author.

**Comment by GeneralBibi** [comment]
I did, but nothing worked

**Comment by Ghost-chu** [comment]
Could you create a clean server with only `Essentials, Vault, QuickShop` and test again?

**Comment by GeneralBibi** [comment]
But i dont use essentails

**Comment by GeneralBibi** [comment]
is the GoldBank Plugin compatible?

**Comment by Ghost-chu** [comment]
No, it not in list
**Make sure you have uninstalled all plugin in  above list** and test again.
If still, create a new paste

**Comment by GeneralBibi** [comment]
https://paste.enginehub.org/cgM2nNa1

**Comment by GeneralBibi** [comment]
uninstall all of em, this is the new paste

**Comment by Ghost-chu** [comment]
Still didn't work?

**Comment by GeneralBibi** [comment]
nop

**Comment by Ghost-chu** [comment]
[QuickShop-3.1.3.3.jar.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/4123018/QuickShop-3.1.3.3.jar.zip)
try this

**Comment by GeneralBibi** [comment]
![image](https://user-images.githubusercontent.com/54682507/73276177-8f436c00-41e8-11ea-8857-3ce260ff6d69.png)

PASTE: https://paste.enginehub.org/N5ZaEkJE

**Comment by GeneralBibi** [comment]
still somehow the same

**Comment by Ghost-chu** [comment]
Can confirm the reason is 3rd party plugin, Not quickshop fault.
Debug log shows everythings.

**Comment by Ghost-chu** [comment]
I can say the problem 100% caused by 3rdparty in above list.

**Comment by Ghost-chu** [comment]
If you can use command /qs supercreate , that mean the problem not caused by QuickShop.
I can't reproduce it on my test server
