### ISSUE TITLE
Being CC'd on QSRR list requests?

### ISSUE THREAD

**Issue by xSepticSidx** [Ghost-chu/QuickShop-Reremake#319]
Hi, I keep getting cc'd in on the requests by people to be added to the list of servers using QSRR.

You didn't put mine in the list so please stop CC'ng me others requests.
Cheers,
Septicsid

**Comment by cakoyo** [comment]
I guess you can just unsubscribe that thread.

**Comment by Ghost-chu** [comment]
unsubscribe that issue to solve your problem.
