### ISSUE TITLE
Sqlite to Mysql

### ISSUE THREAD

**Issue by ZagyMC** [Ghost-chu/QuickShop-Reremake#322]
When i change database sqlite to mysql the plugin conect to mysql but data from sqlite doesnt load. Or is there anyway to upload the data to my mysql database from shop.db file?

**Comment by Ghost-chu** [comment]
use database tool------------------ 原始邮件 ------------------
发件人: "ZagyMC"<notifications@github.com>
发送时间: 2020年1月31日(星期五) 上午9:03
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Ghost-chu/QuickShop-Reremake] Sqlite to Mysql (#322)



When i change database sqlite to mysql the plugin conect to mysql but data from sqlite doesnt load. Or is there anyway to upload the data to my mysql database from shop.db file?
 
&mdash;

**Comment by Ghost-chu** [comment]
E.g Navicat------------------ 原始邮件 ------------------
发件人: "ZagyMC"<notifications@github.com>
发送时间: 2020年1月31日(星期五) 上午9:03
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Ghost-chu/QuickShop-Reremake] Sqlite to Mysql (#322)



When i change database sqlite to mysql the plugin conect to mysql but data from sqlite doesnt load. Or is there anyway to upload the data to my mysql database from shop.db file?
 
&mdash;

**Comment by portlek** [comment]
It will be come with the refactor branch
