### ISSUE TITLE
[BUG] Cannot load QuickShop

### ISSUE THREAD

**Issue by Pix-00** [Ghost-chu/QuickShop-Reremake#327]
**Describe the bug**
I have install the eco plugins ( The New Economy and Reserve ), and correctly configured the database connections of those plugins (as there is no error message printed).
However, when I start the server, QuickShop still report that "No Economy plugin detected".

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Server

**Expected behaviour**
QuickShop can be loaded correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/15878537/73827059-d7dad500-4839-11ea-8ff1-2e1a0122993b.png)

**Paste link:**
_NOT AVALIABLE_

**Additional context**
Game Version: 1.15.2
Server: PaperMC
System: Arch Linux (64bit)
Database: MariaDB (MySQL)

**Comment by Ghost-chu** [comment]
Run command /vault-info and make sure your economy plugin appear in that list.

**Comment by Pix-00** [comment]
It seems that my server does not have this command (as I'm using Reserve rather than Vault).
However, I do use the similar command "/reserve loaded" to check that (shown in the screenshot above).
I guess this error is cause due to that TNE finish its loading process after QuikShop's.
Is there anyway to reload the QuickShop to solve the problem?

**Comment by Pix-00** [comment]
Thanks for helping, I found the file "example.config.yml".
I was tried hardly to find some kind of document.
