### ISSUE TITLE
[BUG] Cannot create shops inside a WorldGuard zone

### ISSUE THREAD

**Issue by Pix-00** [Ghost-chu/QuickShop-Reremake#333]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. enable WorldGuard integration from QuickShop's config
2. create a WorldGuard region
3. enable flags "quickshop-create" and "chest-access"
4. try to create a shop (both by hit the chest and the command)

**Expected behaviour**
A shop created successfully.

**Screenshots**
N/A

**Paste link:**
https://paste.enginehub.org/ikBCDpGl

**Additional context**
Server: PaperMC 1.15.2
QuickShop: 3.1.3.14
WorldGuard: 7.0.2
PermissionPlugin: LuckPerms
PermissionNode: default + quickshop.create.double:false

*players can trade successfully, but not create a new shop

**Comment by Pix-00** [comment]
Update:

I specific permission quickshop.create.sell, quickshop.create.buy and quickshop.create.changeprice to players explicitly. Than they seems have permission to "create shop", but WorldGuard report that they do not have permission to break blocks which I do not want them to in order to protect the market area. If I enable the "block-break" flag, they do can create shops finally, but also lost the protection from WorldGuard.

Is there any way to allow them to create shops while cannot break blocks?  
For example, using sneak + right click (use) the chest to create.

*I have to mention that even players does not have permission to break any blocks, they still can trade with existing shop by lift click (break).

**Comment by Ghost-chu** [comment]
Turn off protection-check and enable WG&nbsp;
support.

---Original---

**Comment by Pix-00** [comment]
Thank you, that helped a lot.
