### ISSUE TITLE
[Feature] Dynamic Pricing

### ISSUE THREAD

**Issue by Pix-00** [Ghost-chu/QuickShop-Reremake#335]
**Describe the Feature**
Items' pricing can be altered by QuickShop automatically when some item are purchased or sale in great amount.

A possible way may be let player to choose whether or not to enable this feature per shops.
And use a function to calculate a factor, this factor times the original price will be the real price.
To make sure it will not break any thing, a upper and lower limit of the factor will be needed.

This will makes the game much closer to the real world and with more fun.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by sandtechnology** [comment]
It's needed to find a proper algorithm to adjust price

**Comment by Ghost-chu** [comment]
closed due we had no plan to add that yet
