### ISSUE TITLE
[BUG] Entities are duplicating

### ISSUE THREAD

**Issue by TotallyNotKyle** [Ghost-chu/QuickShop-Reremake#337]
I have an area with AdminShop's that players can teleport to. Every time a player teleports to the area, new entities are created on the shops. I checked the amount of entities before and after someone teleports to the area, and it increases every time. The chunk now has over 10000 entities.

1. Create an AdminShop, note entity count
2. Teleport away (no one in AdminShop chunk)
3. Teleport to the AdminShop
4. See increased entity count

Shops should not be creating endless amounts of entities.

**Screenshots**
https://i.imgur.com/srghgh3.png

**Paste link:**
https://paste.ubuntu.com/p/fdCrRZqyFj/

**Comment by Ghost-chu** [comment]
Please set `disable-debuglogger: false` in your config before reporting.
Also, you should report to Paper also if you didn't actually see entity duplicating.
Most reports is number increaseing in some performance plugin, but we actually didn't see any duplicated entites.

**Comment by TotallyNotKyle** [comment]
Apologies. I've updated the paste link. I will also report this issue to Paper.

**Comment by TotallyNotKyle** [comment]
I've isolated the issue to Holographic Displays. This plugin remains flawless. Sorry for any inconvenience.
