### ISSUE TITLE
[BUG]Compatibility with plugin Survivalplus

### ISSUE THREAD

**Issue by BackWheel** [Ghost-chu/QuickShop-Reremake#338]
I found that Quickshop will conflict with Survivalplus plugin, mainly because of block break event.

This is a question I feedback in Survivalplus, which shows the details of the problem, hoping to provide some help:https://bitbucket.org/ShaneBeeStudios/survivalplus/issues/55/compatibility-issues-with-quickshop-plugin

**Comment by Ghost-chu** [comment]
Disable `protection-check` feature.
And enable any region protection integration if that plugin installed on your server to make sure you shops can be protected.

**Comment by maxsupermanhd** [comment]
Hi, still have this issue, protection-checking: false but now it's just stopped working.
Also have Towny installed, and set integrations enabled and all requirements set to false. Please help.
(Have Discord and server up and running)
