### ISSUE TITLE
It is recommended to add a detection item: check whether the items in the chest are consistent with the product

### ISSUE THREAD

**Issue by BackWheel** [Ghost-chu/QuickShop-Reremake#339]
I hope that the plugin can detect whether the items in the shop are consistent with the products displayed. Because some war uniform servers may use such plugins, if other items can be placed in the shop, players will use this problem to store their items from being stolen by others.

**Comment by Ghost-chu** [comment]
https://www.spigotmc.org/resources/quickshop-addon-shopitemonly.78669/
