### ISSUE TITLE
[BUG] Virtual item displays do not work on 1.13.2

### ISSUE THREAD

**Issue by galacticwarrior9** [Ghost-chu/QuickShop-Reremake#347]
**Describe the bug**
When using display-type: 2 (virtual item displays) with QuickShop 3.1.4.6, ProtocolLib 4.5.0 and the latest build of Paper 1.13.2, the plugin will have a startup error and new shops cannot be made. 

**To Reproduce**
1. Download QuickShop 3.1.4.6, ProtocolLib 4.5.0 and the latest build of Paper 1.13.2. Change display-type to 2. 
2. Start the server.
3. Look at the startup log to see the error which occurs when QuickShop enables. 
4. Try creating a shop. A shop will not be made after you type in the price in chat. Existing shops cannot be used. 

**Expected behavior**
The plugin enables without errors and shops can be created and used. 

**Screenshots**
N/A

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- [Startup error](https://pastebin.com/X6ytB948)
- [/qs paste](https://paste.ubuntu.com/p/ryzvvRKJRD/)

**Additional context**
N/A

**Comment by sandtechnology** [comment]
Is the problem solve in the latest version?
https://github.com/Ghost-chu/QuickShop-Reremake/releases

**Comment by galacticwarrior9** [comment]
It has been resolved. Thank you!
