### ISSUE TITLE
[Console Error related to Vault]

### ISSUE THREAD

**Issue by SteeltonMC** [Ghost-chu/QuickShop-Reremake#349]
**Describe the bug**
It seems Vault is throwing the following error while trying to fetch the players name.

**To Reproduce**
1. Have Vault
2. Have Essentials X
3. Have QuickShop
4. Make Shop: See error

**Expected behavior**
Upon creating a shop, you will get the following errors;

[21:41:30 WARN]: java.lang.RuntimeException: Economy username cannot be null

**Paste link:**
https://pastebin.com/PwfyzHTs

**Comment by sandtechnology** [comment]
please provide the pasebin link by  /qs paste

**Comment by cakoyo** [comment]
I have solved this issue on my fork, this was caused by trying to obtain a player by its UUID and when the player does not exist on the server (haven't played before) for offline servers or don't even have a Mojang account for online servers. Hope this information will help.

**Comment by cakoyo** [comment]
Actually, I think its caused by a non-exist 'tax' account XD

**Comment by Ghost-chu** [comment]
Vault will convert UUID to PlayerName when submit to Essentials.
READ VAULT SOURCE CODE.
@cakoyo

**Comment by cakoyo** [comment]
@Ghost-chu Yes, it will, but it's a user that never exists, you'd better check whether the tax account is existing before post to Vault or it's same as giving a null.
