### ISSUE TITLE
[Feature] Improvement to special-region-only

### ISSUE THREAD

**Issue by Kyrobi** [Ghost-chu/QuickShop-Reremake#351]
**Describe the Feature**
Instead of having the setting `shop.special-region-only` only be useful with AreaShop, have it also work with just WorldGuard. Don't have this setting be exclusively be limited to AreaShop.

**Screenshots**

![image](https://user-images.githubusercontent.com/20980266/75613188-66b4d780-5af0-11ea-8756-7f7cdf9bebc5.png)

**Additional context**

Since I'm using AdvancedRegionMarket and not AreaShop, I am unable to restrict players from creating shops outside of designated regions.

Both AreaShop and AdvancedRegionMarket requires setting up regions with WorldGuard to create the plot anyways.

**Comment by Ghost-chu** [comment]
Residual configuration file, actually useless。
Use AreaShop-Bridge
