### ISSUE TITLE
[BUG] Server - Crashing // MYSQL

### ISSUE THREAD

**Issue by sid-engel** [Ghost-chu/QuickShop-Reremake#352]
**Describe the bug**
Server gets hung up attempting to... From what I can assume, pull/place data in the mysql db.

**To Reproduce**
1. Have mysql enabled? I'd imagine that's all it takes.

**Expected behavior**
The plugin to access the mysql db, clean without causing the server to crash.

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/6tkKSrJM

**Additional context**
Here is the pastbin from our crash log - https://pastebin.com/3FeYTdS5

Any help is appreciated. I know that this bug report isn't as organized, and doesn't provide as much information as others have. Looking for any advice on how to navigate this issue.

Thanks!

**Comment by Ghost-chu** [comment]
You have connection trouble with your MySQL server, Java JDBC cannot transfer the data between Minecraft server and MySQL server.
SQLite is enough for QuickShop if you have less than 10,000 shops.

Try use SQLite or use local machine database.

**Comment by sid-engel** [comment]
Strange, considering the mysql db is hosted on the same machine as the game-server. Do you know of it potentially being anything else?

**Comment by sandtechnology** [comment]
> 
> 
> You have connection trouble with your MySQL server, Java JDBC cannot transfer the data between Minecraft server and MySQL server.
> SQLite is enough for QuickShop if you have less than 10,000 shops.
> 
> Try use SQLite or use local machine database.
May be we should move all the database operation to database manager, it look like is the connection unstable

**Comment by sid-engel** [comment]
I've just separated our quickshops to use a db that is only for quickshops. Before I had all of our plugin data going to one shared db. Hoping that this works out better. I'm thinking maybe the connection appears unstable, as the plugin has to fight for access to data among other requests from other plugins? Still hosting local to the game-server.

**Comment by sid-engel** [comment]
Update: Still seeing these hanging issues occur.

02.03 00:35:55 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-120 (MC: 1.15.2) ---
02.03 00:35:55 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
02.03 00:35:55 [Server] ERROR ------------------------------
02.03 00:35:55 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
02.03 00:35:55 [Server] ERROR ------------------------------
02.03 00:35:55 [Server] ERROR Current Thread: Server thread
02.03 00:35:55 [Server] ERROR PID: 23 | Suspended: false | Native: false | State: BLOCKED
02.03 00:35:55 [Server] ERROR Stack:
02.03 00:35:55 [Server] ERROR com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3395)
02.03 00:35:55 [Server] ERROR com.mysql.jdbc.PreparedStatement.setInt(PreparedStatement.java:3357)
02.03 00:35:55 [Server] ERROR org.maxgamer.quickshop.Database.DatabaseHelper.updateShop(DatabaseHelper.java:238)
02.03 00:35:55 [Server] ERROR org.maxgamer.quickshop.Shop.ContainerShop.update(ContainerShop.java:244)
02.03 00:35:55 [Server] ERROR org.maxgamer.quickshop.Shop.ContainerShop.onUnload(ContainerShop.java:942)
02.03 00:35:55 [Server] ERROR org.maxgamer.quickshop.Listeners.ChunkListener.onChunkUnload(ChunkListener.java:65)
02.03 00:35:55 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor797.execute(Unknown Source)
02.03 00:35:55 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
02.03 00:35:55 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$2812/2146984331.execute(Unknown Source)
02.03 00:35:55 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
02.03 00:35:55 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.03 00:35:55 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
02.03 00:35:55 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.unloadCallback(Chunk.java:691)
02.03 00:35:55 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:382)
02.03 00:35:55 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$4150/114172575.accept(Unknown Source)
02.03 00:35:55 [Server] ERROR com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43)
02.03 00:35:55 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:376)
02.03 00:35:55 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$4149/1521064798.accept(Unknown Source)
02.03 00:35:55 [Server] ERROR java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
02.03 00:35:55 [Server] ERROR java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
02.03 00:35:55 [Server] ERROR java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
02.03 00:35:55 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:103)

**Comment by sid-engel** [comment]
What "collation" should the DB be using. I went with the same one that all my other plugins are using, latin1_swedish_ci. Unsure if this is important to the functionality.

Image of the phpmyadmin server stats page -
![image](https://user-images.githubusercontent.com/1350776/75649681-dd052700-5c21-11ea-9395-0e55ff4c592c.png)

Top command from ssh into server -
![image](https://user-images.githubusercontent.com/1350776/75649728-045bf400-5c22-11ea-8fea-18677a7364f7.png)

**Comment by sandtechnology** [comment]
> 
> 
> What "collation" should the DB be using? I went with the same one that all my other plugins are using, latin1_swedish_ci. Unsure if this is important to the functionality.
> 
> Image of the phpmyadmin server stats page -
> ![image](https://user-images.githubusercontent.com/1350776/75649681-dd052700-5c21-11ea-9395-0e55ff4c592c.png)
> 
> Top command from ssh into server -
> ![image](https://user-images.githubusercontent.com/1350776/75649728-045bf400-5c22-11ea-8fea-18677a7364f7.png)
**Backup the database** and try this lab version:https://cdn.discordapp.com/attachments/645891684277944320/683920782119665666/QuickShop-3.1.4.12.jar

**Comment by sid-engel** [comment]
Plugin is installed with no issues. Testing now... Seems all it takes is some time of watching console to deem if the issue is fixed or not.

**Comment by Ghost-chu** [comment]
We moved some actions to queue async executor, it shouldn't stuck your server.
**Anyway you connection is really unstable, you should check your database even it running on same machine.**
Because if too many tasks cannot execute, some data may lost. or stuck the server when shutting down.

**Comment by sid-engel** [comment]
On the lab version, I am now seeing the following every time I attempt to create a new shop.

02.03 01:50:40 [Server] INFO Sid_Engel issued server command: /i chest
02.03 01:50:43 [Server] WARN [QuickShop] Shop create failed, trying to auto fix the database...

**Comment by sid-engel** [comment]
Do you have any suggestion as to why a local database is having issues keeping up? There's hardly anything on here. Perhaps some sort of setting within phpmyadmin/mysql?

**Comment by sandtechnology** [comment]
> 
> 
> Do you have any suggestion as to why a local database is having issues keeping up? There's hardly anything on here. Perhaps some sort of setting within phpmyadmin/mysql?

you can check log in mysql, it may point the issue in the database

**Comment by sid-engel** [comment]
I've made some changes to my mysql configuration, for example increasing max-connections. from 200(which should be enough) to 500. Still testing if these changes have helped.

**Comment by sid-engel** [comment]
Still having this same issue. Is there any way you can make the plugin not hang up the whole game-server when querying the mysql server?

**Comment by Ghost-chu** [comment]
sadly no, sqlite is enough.
if you mysql not stsble, you should switch back.

**Comment by sid-engel** [comment]
I don't want for our server to be relying on sqlite. Much easier for all of our plugin data to be centralized in our mysql server. I'm sure there's got to be some larger servers with more shops running the plugin using mysql. I'm surprised an issue hasn't been open on this before. I'm not sure how this doesn't indicate an issue with the plugin?

https://pastebin.com/v2TnaPYN

[01:15:37] [Paper Watchdog Thread/ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author

[01:15:37] [Paper Watchdog Thread/ERROR]:      *Especially* if it looks like HTTP or MySQL operations are occurring

**Comment by sandtechnology** [comment]
so 

> 
> 
> I don't want for our server to be relying on sqlite. Much easier for all of our plugin data to be centralized in our mysql server. I'm sure there's got to be some larger servers with more shops running the plugin using mysql. I'm surprised an issue hasn't been open on this before. I'm not sure how this doesn't indicate an issue with the plugin?
> 
> https://pastebin.com/v2TnaPYN
> 
> [01:15:37] [Paper Watchdog Thread/ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
> 
> [01:15:37] [Paper Watchdog Thread/ERROR]: _Especially_ if it looks like HTTP or MySQL operations are occurring

You can try this version:https://cdn.discordapp.com/attachments/645891684277944320/684637460478689288/QuickShop-3.1.4.14.jar, we fully async all the database operation after server started, but still need testing, **it may corrupt your database, make sure you have backup before trying beta build**

**Comment by sid-engel** [comment]
I have CoreProtect, CMI, VotingPlugin, and many other's using mysql. None of them have any similar issues. I'll try this build out, and let you know how it goes.

**Comment by sid-engel** [comment]
Plugin is now installed. Will report back with updates.

**Comment by Ghost-chu** [comment]
We have updated again to solve some database issues, please update.

**Comment by sid-engel** [comment]
Testing shows that we are no longer getting hung up on the same issue anymore.
