### ISSUE TITLE
[BUG] Players can create shops in protected regions

### ISSUE THREAD

**Issue by DrakePork** [Ghost-chu/QuickShop-Reremake#353]
**Describe the bug**
In the latest updates players can create shops in regions they cant open chests in.

**To Reproduce**
Download latest version
Install worldguard/worldedit (or another protection plugin)
Create a protected region
Place a chest
Either deop yourself so you cant open the chest or get someone who cant open it to create a shop at that chest either through /qs create or left clicking.

**Expected behavior**
It should block the players ability to create the shop.

**Paste link:**
https://paste.enginehub.org/8UPbm-PQ

**Comment by sandtechnology** [comment]
Emmm, currently you can use integration option in config.yml to fix it.
May be I could find a way to fix it normally:)

**Comment by sandtechnology** [comment]
Quickshop will detect whether you have permission by try to break the block, so it's not a issue when you can break the block...

**Comment by DrakePork** [comment]
In the regions tested the players did not have permission to break the block.

**Comment by DrakePork** [comment]
Also, after enabling worldguard integration it still happens.

**Comment by Ghost-chu** [comment]
Works on test server.

**Comment by sandtechnology** [comment]
> 
> 
> Also, after enabling worldguard integration it still happens.
https://github.com/Ghost-chu/QuickShop-Reremake/releases/tag/v3.1.4.13

**Comment by DrakePork** [comment]
eey its fixed. Thanks.
