### ISSUE TITLE
PlayerInteractEvent (again)

### ISSUE THREAD

**Issue by CaliDreams** [Ghost-chu/QuickShop-Reremake#36]
Still running into PlayerInteractEvent error :/

It happens when anyone opens up any kind of GUI seemingly. Their enderchest, the warps gui, any of the click menus

Console error:
https://pastebin.com/1HEs5JZW

Using QuickShop Reremake 1.3.1.3 on a (most recent) 1.13.2 Spigot build, along with CMI 8.2.0.2

**Comment by Ghost-chu** [comment]
Update to 1.3.1.4
