### ISSUE TITLE
[BUG]shops still exists even not seen in database

### ISSUE THREAD

**Issue by kafuuchino-desu** [Ghost-chu/QuickShop-Reremake#360]
we have several shops that we cannt find in database but Quickshop still see it as a shop, when admins open it and quickshop tells us that we have bypassed quickshop lock. /qs remove is not working for that block, we can create a shop but after we removed it and right click at the chest,quickshop again tells us that we have bypassed quickshop lock

we donnt know, but our server's players said that this bug appears after they used /qs remove on that shop. And more and more shops are failing like I said above

Expected behavior
shops should be removed

Screenshots
i typed /qs remove, then /qs create 1, and then /qs remove, finally right clicking on that chest
![image](https://user-images.githubusercontent.com/33673786/75966330-1d57f400-5f05-11ea-96b8-09ba8b463223.png)

Paste link:
- https://paste.enginehub.org/ak7zzSjj

**Comment by sandtechnology** [comment]
Could you provide full logs with debug mode enabled?

**Comment by Ghost-chu** [comment]
Please test with new update on SpigotMC page

**Comment by kafuuchino-desu** [comment]
we have tested with new release, but those failing chests still exists, I tried to /qs create and /qs removed again, but it still told me that I'm bypassing quickshop lock.
I talked with some players and they told me that this bug happens after they create a shop and removing it, then it starts to fail like I said.
we have further checked the paste link and the database, the failed block pos is not in either of these. This is very weird.
PS: the failed block pos is (x,y,z): (128, 73, 202) and (128, 73, 200).
and we somehow fixed 1 chest yesterday by creating and removing the shop again(with some random trys like placing a block at the original pos or using /setblock) which it haven't gliched again until now, its pos is (131, 73, 202)

**Comment by kafuuchino-desu** [comment]
we have tried restarting the server mutiple times and it doesn't help

**Comment by sandtechnology** [comment]
> 
> 
> we have tried restarting the server mutiple times and it doesn't help

Could you enable debug mode(/qs debug) ,and create and remove these strange shops, then provide a paste(get it by /qs paste)?

**Comment by kafuuchino-desu** [comment]
Update: we have multiple chests failing after the update, idk if the update caused it

**Comment by kafuuchino-desu** [comment]
> > we have tried restarting the server mutiple times and it doesn't help
> 
> Could you enable debug mode(/qs debug) ,and create and remove these strange shops, then provide a paste(get it by /qs paste)?

https://paste.enginehub.org/tssQnZdb

**Comment by sandtechnology** [comment]
> 
> 
> > > we have tried restarting the server mutiple times and it doesn't help
> > 
> > 
> > Could you enable debug mode(/qs debug) ,and create and remove these strange shops, then provide a paste(get it by /qs paste)?
> 
> https://paste.enginehub.org/tssQnZdb

emmmm,Is the strange shop can buy or sell, also changing the price by command?

**Comment by Aira-Sakuranomiya** [comment]
> > > > we have tried restarting the server mutiple times and it doesn't help
> > > 
> > > 
> > > Could you enable debug mode(/qs debug) ,and create and remove these strange shops, then provide a paste(get it by /qs paste)?
> > 
> > 
> > https://paste.enginehub.org/tssQnZdb
> 
> emmmm,Is the strange shop can buy or sell, and changing the price by command?

不能（我是服主）
都是中国人直接用中文交流吧

**Comment by Aira-Sakuranomiya** [comment]
自从几天前出现这个问题到现在已经有8个箱子出现这个问题了

**Comment by Ghost-chu** [comment]
先创建一个Paste，然后创建商店，接着再创建一个Paste，然后/qs reload重载，最后再/qs paste一次

**Comment by sandtechnology** [comment]
> 
> 
> 自从几天前出现这个问题到现在已经有8个箱子被锁住了

I review all the code again, it shouldn't happened, it's problem exist after using /qs reload command? I also notice you disable the verify in bytecode, may be it's the problem
我重新好好看了一遍代码，这种情况应该不会出现来着，你用/qs reload还是会出现这种情况吗？我发现你禁用了字节码验证，这个可能是问题所在

**Comment by sandtechnology** [comment]
另外 使用旧版本（3.1.4.12之前的版本）会出现这种情况吗？
Also, Is problem exist in old version (after 3.1.4.12)?

**Comment by Aira-Sakuranomiya** [comment]
> 先创建一个Paste，然后创建商店，接着再创建一个Paste，然后/qs reload重载，最后再/qs paste一次

按照这个顺序弄的
https://paste.enginehub.org/GyuHTSz4
https://paste.enginehub.org/IoeWqsrl
https://paste.enginehub.org/ie91NuJc

**Comment by Aira-Sakuranomiya** [comment]
再说个bug
每次重载downloading manifest的时候主线程都会卡住，Paper疯狂刷红字
而且还会下载错误，可能是下载服务器很难连接

**Comment by sandtechnology** [comment]
> 
> 
> 再说个bug
> 每次重载downloading manifest的时候主线程都会卡住，Paper疯狂刷红字
> 而且还会下载错误，可能是下载服务器很难连接

这个是连接到官方mojang服务器下载相关的物品翻译，所以可能会下载失败
请问能上传一下shop.db并提供那几个奇怪箱子的坐标吗 我具体看看是什么情况

**Comment by Aira-Sakuranomiya** [comment]
> > 再说个bug
> > 每次重载downloading manifest的时候主线程都会卡住，Paper疯狂刷红字
> > 而且还会下载错误，可能是下载服务器很难连接
> 
> 这个是连接到官方mojang服务器下载相关的物品翻译，所以可能会下载失败
> 请问能上传一下shop.db并提供那几个奇怪箱子的坐标吗 我具体看看是什么情况

db我之前用navicat打开看过了，根本就没这个坐标的箱子
我先列举三个这种奇怪的箱子吧 (以下坐标从左到右分别为 X Y Z)
128 73 200
128 73 202
128 73 204


[shops.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/4301962/shops.zip)

**Comment by Aira-Sakuranomiya** [comment]
关于下载能否不要占用主线程呢，现在这样每次reload服务器都得卡住半天，玩家都以为掉线了

**Comment by Ghost-chu** [comment]
默认只占用30秒，超过30秒转入后台下载避免卡崩服务器，这个过程只会下载一次文件
每次都下载那么就可能是下载失败了，你应该检查你的网络



---Original---

**Comment by sandtechnology** [comment]
> 
> 
> > > 再说个bug
> > > 每次重载downloading manifest的时候主线程都会卡住，Paper疯狂刷红字
> > > 而且还会下载错误，可能是下载服务器很难连接
> > 
> > 
> > 这个是连接到官方mojang服务器下载相关的物品翻译，所以可能会下载失败
> > 请问能上传一下shop.db并提供那几个奇怪箱子的坐标吗 我具体看看是什么情况
> 
> db我之前用navicat打开看过了，根本就没这个坐标的箱子
> 我先列举三个这种奇怪的箱子吧 (以下坐标从左到右分别为 X Y Z)
> 128 73 200
> 128 73 202
> 128 73 204
> 
> [shops.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/4301962/shops.zip)

请问能否给出这些商店的三视图呢（标出问题商店） 我怀疑和商店的放置位置有关

**Comment by sandtechnology** [comment]
问题原因已找到，为1.13+箱子可并排放置导致，是从上游传下来的代码没有做出更新的原因，在配置文件中将use-fast-shop-search-algorithm设置为true使用新的寻找算法即可
Okay I finally find the cause, it's cause by feature that can place chest side by side in 1.13+ ,but the old code from upstream don't change, please set use-fast-shop-search-algorithm to true in config.yml to resolve it.
