### ISSUE TITLE
[Feature] The ability to create admin shops with automatically adjusting prices based on the average market value of items

### ISSUE THREAD

**Issue by Weasel-Beans** [Ghost-chu/QuickShop-Reremake#361]
Economies can be very unstable on survival servers, so it can be very useful to have admin shops that reflect the real average value of items unique to a particular server.

I'm thinking there could be a way to have a set interval where the plugin will check the database files and generate an average price for particular items. So for example you could set up a shop which accepts or sells diamonds for the average price, and as a result the plugin would check the database and find the average price of diamonds to use in the shop. You could also have a setting that uses a multiplier to raise or lower the price of the admin-shop item to incentivise players to use normal shops instead. To reduce lag the plugin could only check the database to adjust prices at a set interval, rather than doing it in real-time.

Edit: There will also need to be measures to reduce/eliminate the possibility of players 'cheesing' the system by creating lots of shops with high/low prices to artificially change the average. Perhaps it could only count all of a players' shops for a particular item as one value, and leave out any of their shops from the calculation that deviate too far from the average value.

**Comment by Ghost-chu** [comment]
before v4 comes out, this feature should implement by an addon.

**Comment by Ghost-chu** [comment]
closed due we had no plan to add it yet
