### ISSUE TITLE
Towny and QuickShop bug

### ISSUE THREAD

**Issue by Dauwks** [Ghost-chu/QuickShop-Reremake#364]
Good morning, sir,

When I activate the towny and quickshop integration, it works in the sense that I get a message telling me that I can't create a shop in an area that I don't own but the problem is that when I'm in an area that I own I don't get a message but I can't create a shop. (see gif) https://imgur.com/VvLqngN

Thanks

**Comment by sandtechnology** [comment]
Please report with Bug report template, and you should offer the paste link by /qs paste

**Comment by Ghost-chu** [comment]
Too long time no response.
Issue will close.
