### ISSUE TITLE
[BUG] LiteBans and QuickShop issue

### ISSUE THREAD

**Issue by Blackyvk** [Ghost-chu/QuickShop-Reremake#368]
**Describe the bug**
If a player is muted, this player is unable to sell or buy from shops as litebans denies all chat

**To Reproduce**
1. Get muted
2. Try to sell

**Expected behavior**
Find a way to work with a muted player by litebans? (bungeecord mode) if possible

or add a command that you can use while you are muted, as commands arent muted

/qss amount

**Comment by sandtechnology** [comment]
you can use /qs amount [amount] instead
