### ISSUE TITLE
I keep getting an error message!

### ISSUE THREAD

**Issue by bbgun2821** [Ghost-chu/QuickShop-Reremake#369]
Every command attempt I make I'm getting a message that says "An internal error occurred while attempting to perform this command."  I've installed Vault as well as Bssentials, and unsure as to how to fix the issue.

**Comment by sandtechnology** [comment]
Any error while starting the server?

**Comment by bbgun2821** [comment]
No sir, when executing the command.  I've attempted multiple commands, all /qs <blah blah>  and it dings every time I try it.

**Comment by sandtechnology** [comment]
> 
> 
> No sir, when executing the command. I've attempted multiple commands, all /qs and it dings every time I try it.

please try to use /qs paste and reply with paste link, if it failed, you can provide the log in logs/latest.log

**Comment by bbgun2821** [comment]
16.03 23:49:43 [Server] Server thread/INFO BBGun2821 issued server command: /qs paste
16.03 23:49:43 [Server] Server thread/ERROR null
16.03 23:49:43 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'qs' in plugin QuickShop v3.1.4.22
16.03 23:49:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:702) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1607) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1461) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:36) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:876) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:869) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:853) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:793) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
16.03 23:49:43 [Server] INFO Caused by: java.lang.NullPointerException
16.03 23:49:43 [Server] INFO at org.maxgamer.quickshop.Command.CommandManager.onCommand(CommandManager.java:317) ~[?:?]
16.03 23:49:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
16.03 23:49:43 [Server] INFO ... 17 more

**Comment by sandtechnology** [comment]
> 
> 
> 16.03 23:49:43 [Server] Server thread/INFO BBGun2821 issued server command: /qs paste
> 16.03 23:49:43 [Server] Server thread/ERROR null
> 16.03 23:49:43 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'qs' in plugin QuickShop v3.1.4.22
> 16.03 23:49:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:702) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1607) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1461) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:36) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:876) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:869) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:853) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:793) [craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
> 16.03 23:49:43 [Server] INFO Caused by: java.lang.NullPointerException
> 16.03 23:49:43 [Server] INFO at org.maxgamer.quickshop.Command.CommandManager.onCommand(CommandManager.java:317) ~[?:?]
> 16.03 23:49:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit_1.15.2.jar:git-Bukkit-a6f8093]
> 16.03 23:49:43 [Server] INFO ... 17 more

 you can provide the log in logs/latest.log (as file

)

**Comment by bbgun2821** [comment]
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4341663/latest.log)

**Comment by sandtechnology** [comment]
> 
> 
> [latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4341663/latest.log)

Please switch to spigot or paper to make our plugin work, we don't support CraftBukkit

**Comment by bbgun2821** [comment]
I Switched to a Spigot server then I got a different error message, saying that it doesn't recognize an Economy plugin.  I have Best Essentials downloaded, and the eco commands work properly.  Any reason it wouldn't recognize it?

**Comment by sandtechnology** [comment]
> 
> 
> I Switched to a Spigot server then I got a different error message, saying that it doesn't recognize an Economy plugin. I have Best Essentials downloaded, and the eco commands work properly. Any reason it wouldn't recognize it?

The solution is already in the log:`[23:37:19] [Server thread/WARN]: [Bssentials] The EssentialsBridge plugin is not installed! Plugins that requrire the EssAPI will not function with Bssentials without this bridge, (ex ChestShop, Vault, etc)
[23:37:19] [Server thread/INFO]: [Bssentials] https://dev.bukkit.org/projects/essentialsapibridge`

**Comment by bbgun2821** [comment]
Gotcha, Thanks!  I'll get on that.
