### ISSUE TITLE
Error creating store

### ISSUE THREAD

**Issue by Exmeaning** [Ghost-chu/QuickShop-Reremake#372]
**Describe the bug**
I can't build a store anywhere in the world.

**To Reproduce**
When I put the box on the ground and click on it with the object. Although it displays text reminding me to enter the price, no matter how I type it, I can't create a store.Sometimes, about 1/100, it reminds me that it can't create a bulletin board. But there are no squares around the box, not even the squares at the bottom.Also,because the chance of it is so small that I can't take a screenshot.

**Expected behavior**
I hope the author can find the cause and fix this loophole, or find an alternative.

**Screenshots**
I'm not very good with github, so I may not know how to upload screenshots.Maybe it  #is
`[image]http://i1.fuimg.com/712960/c4780b03d6a98f8a.png`

I'm not sure what this option means, maybe it's an error report? But it doesn't have any misinformation about it.
However, to be sure, I have not modified any relevant configuration files, they are all default configurations, except for changing "en" to "zh-CN"

**Comment by sandtechnology** [comment]
兄弟你能用中文说一遍吗，机翻翻的我看不懂啊.....另外请用下/qs paste然后回复下paste的链接
另外，因为数据库异步的关系，牌子的创建是有一定延迟的，所以这个属于正常现象
Could you repeat it with chinese? look like you are using machine translation, I can't got it clearly, also, It's common that sign will create later when you created a shop, because database is full async.

**Comment by Exmeaning** [comment]
好的。
是这样的，我创建商店的时候，用物品点击箱子。虽然左下角显示请输入商店价格，但是输入价格后没有反应。
大概很低的几率，它会提醒我“没有一个足够的空间创建商店”（这张图我没有截取到），但是，我箱子旁边没有任何方块，包括箱子下面的方块。
![c4780b03d6a98f8a](https://user-images.githubusercontent.com/60350667/77158542-78314400-6ade-11ea-9f28-5f40af52509d.png)
（左下角一直显示这样的提示）
虽然商店创建有延迟，这个我是懂得的，但是我根本无法创建任何商店。
这是输入/qs paste后的错误报告
20.03 19:12:34 [Server] INFO /qs
20.03 19:12:34 [Server] INFO 位于 org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
20.03 19:12:34 [Server] INFO 位于 org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
20.03 19:12:34 [Server] INFO 位于 pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
20.03 19:12:34 [Server] INFO 位于 org.maxgamer.quickshop.Command.CommandManager.onCommand(CommandManager.java:333)
20.03 19:12:34 [Server] INFO 位于 org.maxgamer.quickshop.Command.SubCommands.SubCommand_Paste.onCommand(SubCommand_Paste.java:44)
20.03 19:12:34 [Server] INFO 简易错误信息如下:
20.03 19:12:34 [Server] INFO 异常说明: org/maxgamer/quickshop/Command/SubCommands/SubCommand_Paste$1
20.03 19:12:34 [Server] INFO 异常名称: java.lang.NoClassDefFoundError
20.03 19:12:34 [Server] INFO [Yum 命令监控] 玩家 CONSOLE 执行 QuickShop 插件 qs paste 命令时发生异常!
20.03 19:12:34 [Server] INFO 异常说明: org/maxgamer/quickshop/Command/SubCommands/SubCommand_Paste$1
20.03 19:12:34 [Server] INFO 异常名称: java.lang.NoClassDefFoundError
20.03 19:12:34 [Server] INFO 插件名称: QuickShop
20.03 19:12:34 [Server] INFO 命令执行异常 请反馈下列信息给腐竹!
关于配置文件的问题，我没有更改它，除了将en改为zh-CN

**Comment by sandtechnology** [comment]
> 
> 
> 好的。
> 是这样的，我创建商店的时候，用物品点击箱子。虽然左下角显示请输入商店价格，但是输入价格后没有反应。
> 大概很低的几率，它会提醒我“没有一个足够的空间创建商店”（这张图我没有截取到），但是，我箱子旁边没有任何方块，包括箱子下面的方块。
> ![c4780b03d6a98f8a](https://user-images.githubusercontent.com/60350667/77158542-78314400-6ade-11ea-9f28-5f40af52509d.png)
> （左下角一直显示这样的提示）
> 虽然商店创建有延迟，这个我是懂得的，但是我根本无法创建任何商店。
> 这是输入/qs paste后的错误报告
> 20.03 19:12:34 [Server] INFO /qs
> 20.03 19:12:34 [Server] INFO 位于 org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
> 20.03 19:12:34 [Server] INFO 位于 org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> 20.03 19:12:34 [Server] INFO 位于 pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
> 20.03 19:12:34 [Server] INFO 位于 org.maxgamer.quickshop.Command.CommandManager.onCommand(CommandManager.java:333)
> 20.03 19:12:34 [Server] INFO 位于 org.maxgamer.quickshop.Command.SubCommands.SubCommand_Paste.onCommand(SubCommand_Paste.java:44)
> 20.03 19:12:34 [Server] INFO 简易错误信息如下:
> 20.03 19:12:34 [Server] INFO 异常说明: org/maxgamer/quickshop/Command/SubCommands/SubCommand_Paste$1
> 20.03 19:12:34 [Server] INFO 异常名称: java.lang.NoClassDefFoundError
> 20.03 19:12:34 [Server] INFO [Yum 命令监控] 玩家 CONSOLE 执行 QuickShop 插件 qs paste 命令时发生异常!
> 20.03 19:12:34 [Server] INFO 异常说明: org/maxgamer/quickshop/Command/SubCommands/SubCommand_Paste$1
> 20.03 19:12:34 [Server] INFO 异常名称: java.lang.NoClassDefFoundError
> 20.03 19:12:34 [Server] INFO 插件名称: QuickShop
> 20.03 19:12:34 [Server] INFO 命令执行异常 请反馈下列信息给腐竹!
> 关于配置文件的问题，我没有更改它，除了将en改为zh-CN

可以试试最新版本，你这个文件貌似都损坏了233
You can try the latest version, plugin file look like is corrupted lol

**Comment by Exmeaning** [comment]
好的

**Comment by Exmeaning** [comment]
刚刚我删除了qs插件以及其文件夹，重新安装了新版本的，重启后发现还是不行。
问题和刚才的情况一样，不过这次输入指令后它回复了链接
20.03 19:42:22 [Server] INFO https://paste.enginehub.org/rr4Mioh9W
20.03 19:42:20 [Server] INFO Please wait, we're uploading the data to the pastebin...
并且，每次我创建商店输入价格后，监测到控制台的日志为：
20.03 19:41:39 [Server] WARN Task #2699 for QuickShop v3.1.4.26 generated an exception

**Comment by sandtechnology** [comment]
> 
> 
> 刚刚我删除了qs插件以及其文件夹，重新安装了新版本的，重启后发现还是不行。
> 问题和刚才的情况一样，不过这次输入指令后它回复了链接
> 20.03 19:42:22 [Server] INFO https://paste.enginehub.org/rr4Mioh9W
> 20.03 19:42:20 [Server] INFO Please wait, we're uploading the data to the pastebin...
> 并且，每次我创建商店输入价格后，监测到控制台的日志为：
> 20.03 19:41:39 [Server] WARN Task #2699 for QuickShop v3.1.4.26 generated an exception

可以提供下日志吗？logs/latest.log

**Comment by Exmeaning** [comment]
好的。
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4359414/latest.log)

**Comment by sandtechnology** [comment]
> 
> 
> 好的。
> [latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4359414/latest.log)

更新你的ProtocolLib：https://github.com/dmulloy2/ProtocolLib/releases

**Comment by Exmeaning** [comment]
好的，我一会儿试试。

**Comment by Exmeaning** [comment]
我删除了所有Protocol的相关文件，更新到Protocol为最新版（ProtocolLib v4.5.0）后，重启后，还是没法创建商店。
不过这次输入/qs paste指令后，他回复了另外一组链接：（与之前的不同）
21.03 07:53:02 [Server] INFO https://paste.enginehub.org/9sRqAqJRh
输入价格后显示的日志行为：（与之前的不同）
21.03 07:54:21 [Server] WARN Task #1026 for QuickShop v3.1.4.26 generated an exception
其余日志文件：
[latest (2).log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4362168/latest.2.log)

**Comment by sandtechnology** [comment]
> 
> 
> 我删除了所有Protocol的相关文件，更新到Protocol为最新版（ProtocolLib v4.5.0）后，重启后，还是没法创建商店。
> 不过这次输入/qs paste指令后，他回复了另外一组链接：（与之前的不同）
> 21.03 07:53:02 [Server] INFO https://paste.enginehub.org/9sRqAqJRh
> 输入价格后显示的日志行为：（与之前的不同）
> 21.03 07:54:21 [Server] WARN Task #1026 for QuickShop v3.1.4.26 generated an exception
> 其余日志文件：
> [latest (2).log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4362168/latest.2.log)

[07:48:18] [Server thread/ERROR]: Ambiguous plugin name `ProtocolLib' for files `plugins\[前置]ProtocolLib.jar' and `plugins\ProtocolLib (2).jar' in `plugins'
请删除多余的ProtocolLib

**Comment by Ghost-chu** [comment]
请删除多余的ProtocolLib并删除Yum

**Comment by Exmeaning** [comment]
感谢，已解决。
