### ISSUE TITLE
[Feature] Ability to sell stacks or multiple stacks. Instead of per item.

### ISSUE THREAD

**Issue by GliderCodes** [Ghost-chu/QuickShop-Reremake#374]
**Describe the Feature**
There should be a way a person can select the quantity of items they want to sell. Perhaps 2 stacks of quartz for $1. Instead of 1 quartz for $1. You can implement it by adding an extra step after it asks the player the price, perhaps ask how much would they like to sell.

**Comment by yntel** [comment]
Just wanted to add onto this - the ability to specify an amount of items to be bought in one transaction would be fantastic. Currently you only have the ability to set a price for 1 item - for example 1 Dirt for $X. It would be good to be able to change the amount you can sell - like selling 24 dirt for $X, or 40 dirt for $X, to allow flexibility for economy systems where only small amounts of money are moving around. I see that you're working on this - just wanted to add my bit. Thank you!
