### ISSUE TITLE
Unable To Create Shop

### ISSUE THREAD

**Issue by NicoChiGu** [Ghost-chu/QuickShop-Reremake#378]
When input amount ”Money". No response creating shop

Server: Spigot 1.14.4 QuickShop v3.1.4.26

Plugins: LuckPerms AncientGates Clearlag EssentialsX (AntiBuild Chat Protect Spawn) PixelVip ProtocolLib RifleChairs ultimatetimber Vault Frozen Passky

**Comment by NicoChiGu** [comment]
https://paste.enginehub.org/dPWMXDI2o

**Comment by sandtechnology** [comment]
> 
> 
> https://paste.enginehub.org/dPWMXDI2o

ProtocolLib@Enabled#4.4.0
Please update ProtocolLib to the latest version:https://www.spigotmc.org/resources/protocollib.1997/

**Comment by NicoChiGu** [comment]
> > https://paste.enginehub.org/dPWMXDI2o
> 
> ProtocolLib@Enabled#4.4.0
> Please update ProtocolLib to the latest version:https://www.spigotmc.org/resources/protocollib.1997/

Thanks!  It works.
