### ISSUE TITLE
[BUG]Compatibility issues with BlockLocker plugin

### ISSUE THREAD

**Issue by BackWheel** [Ghost-chu/QuickShop-Reremake#379]
**Describe the bug**
My server is equipped with BlockLocker and Quickshop plug-ins. BlockLocker is a chest lock plug-in. When I use a wooden sign to lock the chest, others can use QuickShop's store creation function to obtain the permissions of the boxes protected by the BlockLocker plug-in!

**To Reproduce**
1. Install BlockLocker and QuickShop plugin
2. Let a player use wooden cards to lock chest
3. Let another player create a store with QuickShop
4. The player who created the store gains permission to the locked chest

**Expected behavior**
Players cannot perform any operations on chests locked by other players

**Screenshots**
https://youtu.be/7xrBHQAiLA8

**Paste link:**
https://paste.enginehub.org/mHXoYdX3v

**Additional context**
No

**Comment by Ghost-chu** [comment]
/qs create command can bypass some protection, that is why i put that command permission in Admin Shop.

以及你为什么不找个其他网站传，两边都得让Y2B摧残一遍 :(

**Comment by Ghost-chu** [comment]
Please use click-create to create the shop not command.

**Comment by BackWheel** [comment]
Things don't seem so simple, even though I try to use click-create, the above problems still occur ..

**Comment by BackWheel** [comment]
If you need, you can give me a new video platform, and I will give you a demo video through this platform

**Comment by sandtechnology** [comment]
> 
> 
> If you need, you can give me a new video platform, and I will give you a demo video through this platform

Please enable protection-checking which in config.yml

**Comment by BackWheel** [comment]
Ok.thanks
