### ISSUE TITLE
[Feature] The ability to turn barrels into shops

### ISSUE THREAD

**Issue by Weasel-Beans** [Ghost-chu/QuickShop-Reremake#380]
Barrels can be more efficient storage, as you don't need space above them. It would be cool to have the ability to turn them into shops the same way that chests are in a future update.

**Comment by sandtechnology** [comment]
> 
> 
> Barrels can be more efficient storage, as you don't need space above them. It would be cool to have the ability to turn them into shops the same way that chests are in a future update.

Try to add Barrels in shop-blocks, our plugin support all the container :D
