### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Syrkulous** [Ghost-chu/QuickShop-Reremake#381]
**Describe the bug**
Chat shop information message breaks

**To Reproduce**
1. Was caused when transferring files to a new server
2. Happened from something else previously but had to delete files to fix

**Expected behavior**

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/P7rDHFWwbC/

**Additional context**
![image](https://user-images.githubusercontent.com/55862273/77727922-97394580-6fb8-11ea-9cee-282465d33f66.png)

**Comment by Ghost-chu** [comment]
Plugin failed to load messages.json and most parts in file was gone.
It may caused by your Transport Tools encoding issue or transport mode.



---Original---

**Comment by Ghost-chu** [comment]
in next version we may will check missing words and fix it.
but no eta promise.

**Comment by Syrkulous** [comment]
Thank you for the quick response. Am I able to have this fixed, or will I have to delete files again. Just curious
