### ISSUE TITLE
World Edit use breaks shops

### ISSUE THREAD

**Issue by xSepticSidx** [Ghost-chu/QuickShop-Reremake#382]
Hello, when moving an entire build that includes several Quickshop chest shops the items that float on top of the chests fall off and are left behind.
These cannot be picked up and will naturally despawn over time.

However, the moved chests no longer have items over top of them, nor can they be used/open the gui.
Restarting the server does not return them.

Although this is an issue bought about using another plugin, maybe there ought to be some way to reload the chests themselves as world edit is a very common admin tool on servers.

**Comment by sandtechnology** [comment]
Moving shop by worldedit is not supported, If you move all the shop, after /qs reload or server restart all the shop will be removed, may be it will be supported in the future.

**Comment by sandtechnology** [comment]
We could not identify shop after moving since we use loaction as identification, so this it's problem

**Comment by xSepticSidx** [comment]
Cheers folks,
It ink then that if someone needs/wants a shop building moving then they will have to accept that they need to redo all the shops.

Although this then brings about the question - what about the previous shops that are no longer there? Will a "/qs cleanghost" remove them?
This can be closed for me.
Thank you.

**Comment by sandtechnology** [comment]
emmm, currently it will be remove by "/qs cleanghost" when shop was moved, but if there still can be a shop(still having chest), it will not be removed.
And I got a idea to solve this, just store some information in shop chest (NBT works by worldedit API), and check it when it was placed, may be it will become feature shop identification

**Comment by sandtechnology** [comment]
And Look like it doesn't works, worldedit API just accept vanilla value, so could not implement like this.....
