### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OhNo2** [Ghost-chu/QuickShop-Reremake#387]
**Describe the bug**
Does not work on BUKKIT

**To Reproduce**
1. Load plugin onto bukkit server
2. attempt to use plugin

**Expected behavior**
plugin works as advertised

**Additional context**
The plugin is provided under the bukkit website, so it is expected to work on bukkit servers. I really want to use this plugin, but I cant switch to spigot because I will lose all of my player data including backpacks, inventories etc. (trust me, I've tried)

thanks for any help you can give!

**Comment by Ghost-chu** [comment]
QuickShop doesn't work with CraftBukkit.
You must use Spigot or Paper.

You can direct replace the jar to upgrade without any data losing.

**Comment by sandtechnology** [comment]
> 
> 
> **Describe the bug**
> Does not work on BUKKIT
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Load plugin onto bukkit server
> 
>     2. attempt to use plugin
> 
> 
> **Expected behavior**
> plugin works as advertised
> 
> **Additional context**
> The plugin is provided under the bukkit website, so it is expected to work on bukkit servers. I really want to use this plugin, but I cant switch to spigot because I will lose all of my player data including backpacks, inventories etc. (trust me, I've tried)
> 
> thanks for any help you can give!

emmmm, data loss never happened :D, but If you think spigot will bring data loss(old version?), may be paper will solve it? https://papermc.io/downloads
