### ISSUE TITLE
command to view purchased items

### ISSUE THREAD

**Issue by xX-Gigi-Xx** [Ghost-chu/QuickShop-Reremake#389]
Hi ... I asked for the possibility to add a command to view items bought by the players when I'm offline ... when I enter the server where I play, where your plugin is present, at the beginning of the chat I get the notification with items bought to mine shop ... but if due to the various spam in the chat, I do not read the notification immediately, I have no way of knowing what they bought ... so I am forced to check chest for chest to see what is missing ... here is the idea of being able to insert a command that shows the purchases made in my shop in the last 3-4 or 7 days, at your choice, where I can see, when I want, what they bought ... so that I immediately know which materials I have to replace .. I hope my translation is good ... greetings, Gigi

**Comment by sandtechnology** [comment]
Please set auto-fetch-shop-messages to false in config.yml, and use /qs fetchmessage to fetch shop  message
