### ISSUE TITLE
[BUG] Weird double-chest behaviour: You cannot break other players shops in creative mode. Use survival instead or use SuperTool ({0})", despite a shop hasn't been created yet (they are trying to create it) and being in survival mode (not creative)

### ISSUE THREAD

**Issue by quiquelhappy** [Ghost-chu/QuickShop-Reremake#390]
**Describe the bug**
Players cant create double-chest shops. The error message key is messages.json -> "no-double-chests"

**To Reproduce**
1. Go to 'A double chest'
2. Click on 'The chest'
3. See error

**Expected behavior**
Being able to create double chest shops

**Screenshots**
![secreenie](https://i.imgur.com/A7zNsDa.png)

**Paste link:**
- [paste](https://drive.google.com/file/d/1X5El-RNNW1aCHI50kpnkRGxcIEAazdEw/view?usp=sharing)

**Additional context**
Players get "You cannot break other players shops in creative mode. Use survival instead or use SuperTool ({0})", despite a shop hasn't been created yet (they are trying to create it) and being in survival mode (not creative)

**Comment by sandtechnology** [comment]
Could you reproduce this with this lab version?
https://cdn.discordapp.com/attachments/645891684277944320/694895433750675456/QuickShop-3.1.4.28-lab3.jar

**Comment by sandtechnology** [comment]
Closed for no response
