### ISSUE TITLE
[Feature] Shulker Box supported

### ISSUE THREAD

**Issue by jyhsu2000** [Ghost-chu/QuickShop-Reremake#394]
**Describe the Feature**
ItemMatcher in current version does not support checking contents in shulker box.
If I create a selling shop to sell shulker box with some items, shulker boxes with any items in will be consider as the same item and can be sold (even items in them are totally different).
It will be great if new feature added for compare contents of shulker boxes when matching items.

**Comment by sandtechnology** [comment]
Set work-type: 0 to 1 in config.yml will fix it temporay, may be it will be implemented in the future

**Comment by sandtechnology** [comment]
Implemented, If you want to use it now, download this lab version:https://cdn.discordapp.com/attachments/645891684277944320/696253511188480040/QuickShop-3.1.4.29-lab3.jar

**Comment by sandtechnology** [comment]
https://cdn.discordapp.com/attachments/645891684277944320/696399692145360906/QuickShop-3.1.4.29-lab4.jar
Fix several bugs in this lab version

**Comment by jyhsu2000** [comment]
Thanks for prompt reply .
I tested with lab4 version above, and it almost works fine.

But there is the only thing not works as my expectation.
If `work-type` is set to `0`, it cannot find the differences of item amount.
It can match contents of shulker boxes including item amount when only set `work-type` to `1`.
Is this in your plan? or something missing?

**Comment by sandtechnology** [comment]
> 
> 
> Thanks for prompt reply .
> I tested with lab4 version above, and it almost works fine.
> 
> But there is the only thing not works as my expectation.
> If `work-type` is set to `0`, it cannot find the differences of item amount.
> It can match contents of shulker boxes including item amount when only set `work-type` to `1`.
> Is this in your plan? or something missing?

Thanks for you testing! yes I forgot it, in lab5 it should be fixed:https://cdn.discordapp.com/attachments/645891684277944320/696418655533137950/QuickShop-3.1.4.29-lab5.jar

**Comment by jyhsu2000** [comment]
Awesome, it works fine as expected now.
