### ISSUE TITLE
[BUG] Creative can be used for non-admin created shops

### ISSUE THREAD

**Issue by Syrkulous** [Ghost-chu/QuickShop-Reremake#396]
**Describe the bug**
Players are able to sell/buy in creative mode to non-admin chest shops

**To Reproduce**
1. /gmc or /gamemode 1
2. left click sign with that selected item in creative inventory
3. type in amount to sell/buy

**Expected behavior**
1. A big message somewhere saying "You can not sell/buy in creative mode!"

**Screenshots**
https://cdn.discordapp.com/attachments/627620260643602530/696170676767293472/unknown.png

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
https://paste.enginehub.org/jAgbTEAav (Don't know if this is still needed but I'll post anyway)

**Additional context**

**Comment by sandtechnology** [comment]
Implemented, If you want to use it now, download this lab version:https://cdn.discordapp.com/attachments/645891684277944320/696253511188480040/QuickShop-3.1.4.29-lab3.jar

**Comment by Syrkulous** [comment]
Is that safe?

**Comment by Syrkulous** [comment]
It was not fixed

**Comment by sandtechnology** [comment]
> 
> 
> It was not fixed

`  #Should we disable trading for creative mode?
  disable-creative-mode-trading: false`
Please set disable-creative-mode-trading to true

**Comment by Syrkulous** [comment]
Wish it was set to true by default

**Comment by Syrkulous** [comment]
Still didn't work

**Comment by sandtechnology** [comment]
> 
> 
> Still didn't work

https://cdn.discordapp.com/attachments/645891684277944320/696399692145360906/QuickShop-3.1.4.29-lab4.jar
It fix it, now it enable by default

**Comment by Syrkulous** [comment]
It worked, thank you!
