### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by TNTUP** [Ghost-chu/QuickShop-Reremake#398]
**Describe the Feature**
Define minimum /maximum price for individual items.

eg: Min price for a diamond 5.0, max price for a diamond is 50.0. Players cannot set prices below 5 and above 50. 

The current config has the min/max but for ALL items, not INDIVIDUALLY

**Screenshots**
Old fork of QuickShop you might see here (old config for 1.12.2) https://i.qcfb.ca/20200405025353.png

**Additional context**

capped ALL and INDIVIDUALLY to better understanding this suggestion :)

**Comment by sandtechnology** [comment]
lol, Look like upsteam code have implemented and we forgot to add its options,
Please manually add it as you screenshots description to use it, we will re-add it next release

**Comment by TNTUP** [comment]
haha okie good to know the code is still present! *hugs*
