### ISSUE TITLE
Multiple Custom Item Matchers

### ISSUE THREAD

**Issue by Sn0wStorm** [Ghost-chu/QuickShop-Reremake#404]
**Describe the Feature**
Provide a way to register a custom item matcher implementation, in addition to the default item matcher.
This would allow other Plugins to provide an ItemMatcher for their custom items, while still keeping the default ItemMatcher for all other items.

**Additional context**
When a Plugin creates custom Items, they might not necessarily match each other with the default item matching. They might have additional nbt data etc.
So the Plugin could provide an item Matcher in that case, that would decide if two custom items match or not.
To implement this, you could add a registerItemMatcher() Method, which adds the ItemMatcher to a List. When Matching an item, ask every ItemMatcher in that list if they match.

**Comment by Ghost-chu** [comment]
alrealy impl in 3.2 but it not released yet



---Original---

**Comment by Sn0wStorm** [comment]
Nice, thank you
