### ISSUE TITLE
[Feature] Player shop teleporter

### ISSUE THREAD

**Issue by gbmv33** [Ghost-chu/QuickShop-Reremake#410]
**Describe the Feature**
Create a teleport function
When a person finishes building the shop, he will want other people to go to his shop

the person could use a command

ex: / qs setspawn - marks the spawn of the player's store.

another player uses: / shop < playername > he is teleported to the chosen player's shop.

**Comment by Ghost-chu** [comment]
setspawn not a good idea.

but if is shop indexer/finder, it's okay

**Comment by Ghost-chu** [comment]
indexer/finder already added into project long times ago so i will close this
