### ISSUE TITLE
[Feature] Find My Shop

### ISSUE THREAD

**Issue by ChatpKSK** [Ghost-chu/QuickShop-Reremake#411]
**Describe the Feature**
I have changed the limited amount of shops create.
A player is unable to create a new shop and he can't remember where the shop was created.

I would like to propose is search own shop in a database with the command `/qs list` or something.

- Show a list of the shop,
- Show detail of the shop when Hover that name.
- Show coordinates, name world, price, selling or buying
- Show the amount of shop/limit. (if operator limit it)

Like this screenshot

**Screenshots**
![Find My Shop](https://user-images.githubusercontent.com/11331536/79040783-3c892600-7c15-11ea-9843-a1a9b8a94f53.png)

**Additional context**
Admin, Operator or Who has permission may find another player shop.

**Comment by Ghost-chu** [comment]
![image](https://user-images.githubusercontent.com/30802565/87877401-b39e3980-ca10-11ea-9011-2ab90f905b80.png)
I have make a sample build for this feature.
It should will be a addon.

**Comment by Ghost-chu** [comment]
released https://www.spigotmc.org/resources/quickshop-addon-quickshoplist.82143/
