### ISSUE TITLE
[BUG] Tax account's player never played server before.

### ISSUE THREAD

**Issue by Baterka** [Ghost-chu/QuickShop-Reremake#412]
**Describe the bug**

> Warning: [QuickShop] Tax account's player never played server before, that may cause server lagg or economy system error, you should change that name.

I have not changes default tax account (`tax-account: tax`). 

**To Reproduce**
1. Put 'QuickShop-3.1.4.32.jar' into /plugins
2. Start server
3. Watch console
4. See warning

**Expected behavior**
Maybe consider adding option to disable tax-account?

**Comment by Binero** [comment]
I can reproduce this issue.

**Comment by Ghost-chu** [comment]
This nothing right, if tax system works without any issue, this alert can be ignored.
