### ISSUE TITLE
[BUG] Language not switching

### ISSUE THREAD

**Issue by Baterka** [Ghost-chu/QuickShop-Reremake#413]
**Describe the bug**
Language files downloaded from Mojang server are not dependent on `language: en, game-language: en-US` in `config.yml` file.
My server always downloading Czech translations even I clearly set English ones.

**To Reproduce**
1. Put 'QuickShop-3.1.4.32.jar' into /plugins
2. Start server
3. Edit config.yml (change `language` and/or `game-language`)
4. Delete old lang files `***i18n.yml`
5. Restart server
6. Downloaded language files are still in default language (In my case Czech language)

**Expected behavior**

**Screenshots**
Language downloader should follow config

**Comment by Baterka** [comment]
I found what is the problem. It's cache. Maybe clear cache when config changed?

**Comment by Ghost-chu** [comment]
Yes it should be clear, thanks for reporting
