### ISSUE TITLE
[BUG] Buying three items spawns in A LOT of free cash

### ISSUE THREAD

**Issue by Binero** [Ghost-chu/QuickShop-Reremake#414]
**Describe the bug**

Whenever anyone buys 3 items, and only three items, from a player shop, the seller gets an absurd and uncountable amount of money. It fills up their entire inventory and we just end up pooring lava over it because even when an item cost around 3 dollars the floor is littered with hundreds of dollars, all in cents. The bug does not occur when 1, 2 or 4 items are bought. The price of the product doesn't seem to have an impact. The log does not produce anything interesting. 

**To Reproduce**
1. Create a player shop
2. Buy 3 items from that player shop

**Expected behavior**
The player who created the shop receives 3 times the buy price minus taxes. 

**Screenshots**
https://imgur.com/053wVN6
https://imgur.com/ZkUcsuR
https://imgur.com/sj556gA

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/Jwm5fkYTsG/

**Additional context**

We are using The New Economy with Vault. We tried manually moving around money with the new economy plugin, to try and emulate a shop purchase, but it never failed. Quickshop fails consistently and always on three items, no matter the price, which is why I suspect it's a quick shop issue. We are using an item based currency. We have a dollar (Note) item and a cent (Centime) item. When we buy three items, it also gives us thousands of cents, not dollars.

**Comment by Binero** [comment]
I did some additional tests:

I have a tax set to 0.05%. I made a chest selling torches for $2 each. Someone bought three of them. My inventory and enderchest were filled with money and all the rest popped on the ground. I received nearly all the money in cents, and together I was able to pick up and count $1400 before it despawned. Needless to say, this is a lot more than the 5.7 I should have received. 

Before I thought the price didn't matter because the prices we tested with all had this issue and all when buying three items. However, if I sell three torches for $3 each, it does not spawn in a (near-?)infinite amount of money. 

To make sure it is not The New Economy, I gave myself 5.7 currency. It correctly gave me five full dollar notes, and 64+6 cents.

**Comment by Binero** [comment]
I found other amounts of items that trigger this:
3 torches 1 dollar each
12 torches 0.25 dollars each

The total amount received should be 2.85 in those cases (with 5% tax), but it's far more.

**Comment by sandtechnology** [comment]
So basically is the problem that float value will not counting accurately(Java followed IEEE 754), we will fix the problem by using BigDecimal.

**Comment by sandtechnology** [comment]
https://cdn.discordapp.com/attachments/645891684277944320/698732456551120908/QuickShop-3.2-lab6.jar
you can try this version to see if it fixed

**Comment by Binero** [comment]
This issue also occurred when BUYING 29 potatoes for 0.10 cents each, with tax set to 0.

https://imgur.com/CihuKkB

I installed that version and the issue appears to be fixed. Will post if issue re-appears.

**Comment by Binero** [comment]
The issue is not fixed! It is still happening!

**Comment by sandtechnology** [comment]
> 
> 
> The issue is not fixed! It is still happening!

Please provide more information about this
also, there is no way to count any float value accurately, machine itself only will get higher precision and close to real value infinitely

**Comment by Binero** [comment]
> > The issue is not fixed! It is still happening!
> 
> Please provide more information about this
> also, there is no way to count any float value accurately, machine itself only will get higher precision and close to real value infinitely

I gave some detailed examples above. The issue is hard to reproduce because the numbers where it causes the crash changed. We haven't tracked down a number yet on this video, we have just seem the after-effect: people having inventories, ender chests and houses full of currency after someone bought their item.

**Comment by sandtechnology** [comment]
> 
> 
> > > The issue is not fixed! It is still happening!
> > 
> > 
> > Please provide more information about this
> > also, there is no way to count any float value accurately, machine itself only will get higher precision and close to real value infinitely
> 
> I gave some detailed examples above. The issue is hard to reproduce because the numbers where it causes the crash changed. We haven't tracked down a number yet on this video, we have just seem the after-effect: people having inventories, ender chests and houses full of currency after someone bought their item.

you can upload qs.log in QuickShop folder, it will record what happened in trading

**Comment by Ghost-chu** [comment]
This is a issue both of economy plugin and quickshop.

Economy side have a wrong processor, they spilt the input with dot, like 25.13 to 25 and 13.
It works fine under normal, but when computer given a special number like 3.33333333333333333336(double digits issue) use spilt will cause player will get 3 dollar and 333333333333333336 cents.

This is an issue for both of plugins.
You should both report to Economy plugin author to ask fix.

Also we will find the solution ofcourse.

**Comment by Ghost-chu** [comment]
So we need you provide extra data, please upload qs.log file.

**Comment by Binero** [comment]
[qs.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4470570/qs.log)

**Comment by sandtechnology** [comment]
> 
> 
> [qs.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4470570/qs.log)
> The rotten flesh trade at the end is a broken one. I bought 3 rotten flesh for 0.33 with 0.05 tax. I had 64 cash before the transaction.

reproduce with different result, set money to 64 before trading and using essentials eco:

> [2020-04-14 01:07:49.133] Player sandtechnology bought CaptainHerbert shop Shop world(152, 63, 218) Owner: CaptainHerbert - 29355ffc-d088-3626-b80c-54e19bc85cc0 Price: 0.33 Item: ItemStack{ROTTEN_FLESH x 1} for items x3 for ￥0.94 (￥0.05 tax).
> [2020-04-14 01:07:49.133] Player sandtechnology had 62.960499999999996 after trading.

**Comment by Binero** [comment]
It's definitely a TheNewEconomy issue. I can reproduce the issue if I give myself small fractions of money.

**Comment by Ghost-chu** [comment]
This issue will closed and stop for tracking.
