### ISSUE TITLE
[Feature] Edit Admin shops made by other Admins.

### ISSUE THREAD

**Issue by RustyDagger** [Ghost-chu/QuickShop-Reremake#417]
**Describe the Feature**
Tried all the permissions and it seems the plugin refuses to let any player but the player that made the shop edit the shop. being an admin I should be able to EDIT any shop especially admin shops i should not have to break the shop and remake it. just dumb nothing quick about that.

**Screenshots**

**Additional context**

**Comment by RustyDagger** [comment]
only options that work currently is breaking it and making or useing the setowner command setting it to your self.

fun fact when setting the owner of an admin shop to your self the message in chat is wrong instead of saying it set it to your self it says the old owners name. ( wrong placeholder. )

**Comment by sandtechnology** [comment]
> 
> 
> only options that work currently is breaking it and making or useing the setowner command setting it to your self.
> 
> fun fact when setting the owner of an admin shop to your self the message in chat is wrong instead of saying it set it to your self it says the old owners name. ( wrong placeholder. )

The bug has been already fixed, thanks for reporting
