### ISSUE TITLE
[BUG] Item Matcher not checking displayname when set to true.

### ISSUE THREAD

**Issue by RustyDagger** [Ghost-chu/QuickShop-Reremake#418]
**Describe the bug**
I have nearly every option set to true in the item matcher section of my config However I am still able to sell Renamed ( with color ) cookies to the vanilla cookie shop.

**To Reproduce**
1. Create an admin shop buying cookies.
2. Rename a cookie
3. punch the sign to sell
4. observe it count your renamed cookies as sellable.
5. Sell your renamed cookies for proffit.

**Expected behavior**
Respect the config settings. and actually check the item name before letting it be sold. 

**Screenshots**
- https://gyazo.com/adc6d741f974ff16c1d2a708311a7667
observe I am holding &2Kelp Cookies. (26) and I have just clicked that normal cookie shop.

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.

- https://paste.enginehub.org/88F2VG4zN

**Additional context**
My server Has Many renamed items Due to having slimefun4 installed this issue poses a HUGE risk to my economy.

**Comment by sandtechnology** [comment]
There is the things, upstream code seems match a item in abstract mode: if trade item having something shop item don't have, it will matched, e.g an shop item which don't have custom name matched an trade item having custom name.
set work-type to 1 to use bukkit matcher will solve it

**Comment by RustyDagger** [comment]
that has to be the hardest thing iv had to read all month, its all good I understand English is not everyone's first language

**Comment by sandtechnology** [comment]
> 
> 
> that has to be the hardest thing iv had to read all month, its all good I understand English is not everyone's first language

Sorry for this, but QS matcher itself is very confused to me : D

**Comment by sandtechnology** [comment]
In other words, QS matcher will only compare shop item attributes (e.g custom name, book content...) with trade item, if shop item don't have some attributes and the trade item have, QS matcher regarded as matched, which means trade item may be not equals shop item.

May be it will more easy to understand

**Comment by RustyDagger** [comment]
my item thats being sold that should not be sold has NBT and a custom name. but its still being sold when it should not.

**Comment by sandtechnology** [comment]
> 
> 
> my item thats being sold that should not be sold has NBT and a custom name. but its still being sold when it should not.

Set work-type to 1 in config.yml to use bukkit matcher will solve it

**Comment by sandtechnology** [comment]
That's why I said QS matcher is very confused, its compare way is counterintuitive behavior

**Comment by RustyDagger** [comment]
then remove it, and change the default config to use bukkit.\
