### ISSUE TITLE
SpigotMC List of servers using QSRR request form

### ISSUE THREAD

**Issue by Ghost-chu** [Ghost-chu/QuickShop-Reremake#43]
Do you want show your server on our plugin page?

You can comment this issue with your server-name and server'swebsite url/minecraftservers.org's server page

I will check the server using QSRR and add them in plugin page when next edit plugin page.

**Comment by jordanwilliams1** [comment]
play.differentcraft.net 
https://differentcraft.net/ 

Thanks for updating Quickshop. I've been using it since 2014 and loved the fact you updated it. I'd never use another plugin other than Quickshop. It's super noob friendly <3

**Comment by Ghost-chu** [comment]
@jordanwilliams1 done

**Comment by kadika66** [comment]
I used to use Quickshop Shop on my old server I ran a couple years ago and it was always my favorite shop plugin I appreciate it very much that you were able to update the abandoned original. Celestial Realms: 162.244.166.50

**Comment by Ghost-chu** [comment]
@kadika66   Done

**Comment by alan67160** [comment]
play.amsserver.xyz
https://amsserver.xyz/

**Comment by Ghost-chu** [comment]
@alan67160 完成

**Comment by alan67160** [comment]
Requesting rename server AmsServer to 無名氏伺服器

**Comment by Ghost-chu** [comment]
@alan67160 Completed

**Comment by alan67160** [comment]
Thanks

**Comment by nitu2003** [comment]
Server Name: ParaDies  
Server Address: play.paradies.vip  
Server Website: https://paradies.vip  
*(The website is poorly made :| )*  
👍

**Comment by Ghost-chu** [comment]
@nitu2003  Done

**Comment by FizzleTits** [comment]
Tortuga Pirate Network
TPNET.GQ
TPNET.ENJIN.COM

**Comment by Jay9519** [comment]
Server Name: OzServerMC
Server Address: ozservermc.com.au
Server Website: http://ozservermc.com.au

**Comment by Ghost-chu** [comment]
@FizzleTits @Jay9519 done

**Comment by deadman96385** [comment]
Name: Oxidenetwork
IP: hub.oxidenetwork.com
Website: https://oxidenetwork.com

**Comment by korhox** [comment]
Finnish server: flosmine.fi
Website: https://flosmine.fi/

We are using the Finnish translation made by us.

**Comment by Ghost-chu** [comment]
@deadman96385 @korhox   Done

**Comment by snake0053** [comment]
Name: MCPlayNetwork
IP: mcplay.biz
Website: https://www.mcplay.biz/

**Comment by BZEagle** [comment]
Name: EagleCraft | 鹰界
IP: mc.bzeagle.com:25565
Website: http://mc.bzeagle.com:81/

**Comment by Ghost-chu** [comment]
@BZEagle done

**Comment by saladfingers** [comment]
Name: Saladcraft
IP: play.saladcraft.net
Website: www.saladcraft.net

**Comment by kallemarc** [comment]
Name: VaroxCraft
IP: play.varoxcraft.de
Website: https://varoxcraft.de/

**Comment by LoneDev6** [comment]
Name: OnePizza
IP: mc.matteodev.it

**Comment by AeSix** [comment]
Minecats Minecraft
play.minecats.com
https://forums.minecats.com

**Comment by Ghost-chu** [comment]
> Name: Saladcraft
> IP: play.saladcraft.net
> Website: [www.saladcraft.net](http://www.saladcraft.net)



> Name: VaroxCraft
> IP: play.varoxcraft.de
> Website: https://varoxcraft.de/



> Name: OnePizza
> IP: mc.matteodev.it



> Minecats Minecraft
> play.minecats.com
> https://forums.minecats.com

done

**Comment by Futurixel** [comment]
Name: ZenCraft
IP: play.zencraft.fr
Website: https://zencraft.fr/

**Comment by Angrydave1987** [comment]
Site: http://elitekamikazeteam.com/
IP: mc.elitekamikazeteam.com
Name: EKT

**Comment by gp-Airee** [comment]
Site: https://theseedmc.com
IP: theseedmc.com
Name: The Seed Minecraft Servers

**Comment by sid-engel** [comment]
We'd love for our server to be added!

Site: https://ottercraft.net
IP: play.ottercraft.net
Name: OtterCraft

Thank you!

**Comment by Ghost-chu** [comment]
> Name: ZenCraft
> IP: play.zencraft.fr
> Website: https://zencraft.fr/



> Site: http://elitekamikazeteam.com/
> IP: mc.elitekamikazeteam.com
> Name: EKT



> Site: https://theseedmc.com
> IP: theseedmc.com
> Name: The Seed Minecraft Servers



> We'd love for our server to be added!
> 
> Site: https://ottercraft.net
> IP: play.ottercraft.net
> Name: OtterCraft
> 
> Thank you!

Done

**Comment by xSepticSidx** [comment]
Can you add Narnia please?
I am using it with Areashop to allow player sales.
IP: NarniaMC.com 
name Narnia
Thank you
xSepticSidx

**Comment by Ghost-chu** [comment]
> Can you add Narnia please?
> I am using it with Areashop to allow player sales.
> IP: NarniaMC.com
> name Narnia
> Thank you
> xSepticSidx

No website avaliable

**Comment by xSepticSidx** [comment]
try narniamc.com:25964

Cheers,
Sid

**Comment by Meaqua233** [comment]
Name: Wolfx Survival
IP: arkmc.cc:25566
Website: https://wolfx.jp/

**Comment by LoneDev6** [comment]
> matteodev

change IP to onepizza.ga
thanks!

**Comment by Redstone-ray** [comment]
Imbox MC
imboxmc.org

**Comment by nokisenpai** [comment]
Hello !
Name : Lumen
Website : https://lumen.ovh/default.php?page=play

**Comment by LoneDev6** [comment]
> 
> 
> > Name: Saladcraft
> > IP: play.saladcraft.net
> > Website: [www.saladcraft.net](http://www.saladcraft.net)
> 
> > Name: VaroxCraft
> > IP: play.varoxcraft.de
> > Website: https://varoxcraft.de/
> 
> > Name: OnePizza
> > IP: ----
> 
> > Minecats Minecraft
> > play.minecats.com
> > https://forums.minecats.com
> 
> done


can you censor OnePizza IP from your comment and also remove it from quickshop?

Thanks

**Comment by Moikapy** [comment]
Moia MC
moia.ramshard.net

**Comment by sajjaadf** [comment]
**Maclab**
Website: _None yet._ 
Wiki [Link](https://99.145.196.175/wiki)
IP [99.145.196.175](https://99.145.196.175/)

**Comment by LoneDev6** [comment]
> 
> 
> > Name: Saladcraft
> > IP: play.saladcraft.net
> > Website: [www.saladcraft.net](http://www.saladcraft.net)
> 
> > Name: VaroxCraft
> > IP: play.varoxcraft.de
> > Website: https://varoxcraft.de/
> 
> > Name: OnePizza
> > IP: ----
> 
> > Minecats Minecraft
> > play.minecats.com
> > https://forums.minecats.com
> 
> done

@Ghost-chu 
can you censor OnePizza IP from your comment and also remove it from quickshop?

Thanks

**Comment by Ghost-chu** [comment]
> Imbox MC
> imboxmc.org



> Hello !
> Name : Lumen
> Website : https://lumen.ovh/default.php?page=play



> Moia MC
> Website/ Community Page: https://www.guilded.gg/moia
> IP: moia.ramshard.net



> **Maclab**
> Website: _Nothing Interesting there_ [Link](https://99.145.196.175)
> IP [99.145.196.175]

done

**Comment by Ghost-chu** [comment]
> > > Name: Saladcraft
> > > IP: play.saladcraft.net
> > > Website: [www.saladcraft.net](http://www.saladcraft.net)
> > 
> > 
> > > Name: VaroxCraft
> > > IP: play.varoxcraft.de
> > > Website: https://varoxcraft.de/
> > 
> > 
> > > Name: OnePizza
> > > IP: ----
> > 
> > 
> > > Minecats Minecraft
> > > play.minecats.com
> > > https://forums.minecats.com
> > 
> > 
> > done
> 
> @Ghost-chu
> can you censor OnePizza IP from your comment and also remove it from quickshop?
> 
> Thanks

reason..?

**Comment by LoneDev6** [comment]
> 
> 
> > > > Name: Saladcraft
> > > > IP: play.saladcraft.net
> > > > Website: [www.saladcraft.net](http://www.saladcraft.net)
> > > 
> > > 
> > > > Name: VaroxCraft
> > > > IP: play.varoxcraft.de
> > > > Website: https://varoxcraft.de/
> > > 
> > > 
> > > > Name: OnePizza
> > > > IP: ----
> > > 
> > > 
> > > > Minecats Minecraft
> > > > play.minecats.com
> > > > https://forums.minecats.com
> > > 
> > > 
> > > done
> > 
> > 
> > @Ghost-chu
> > can you censor OnePizza IP from your comment and also remove it from quickshop?
> > Thanks
> 
> reason..?

Server closed

**Comment by Nightwielder1** [comment]
Roshar MC
Discord is our website :) ~ discordapp.com/invite/HTKm88s

**Comment by LoneDev6** [comment]
@Ghost-chu
can you censor OnePizza IP from your comment? https://github.com/Ghost-chu/QuickShop-Reremake/issues/43#issuecomment-525621842
Thanks

**Comment by OhNo2** [comment]
SwunkCraft
swunkcraft.net

**Comment by Ghost-chu** [comment]
Busy for me now, list update may delay until i have time to access my account.
(now updating by @sandtechnology)

**Comment by Teyir** [comment]
Hello,

I use QuickShop and I love this amazing plugin.

My Minecraft SkyBlock 1.15.2 server Sky-Dream use QuickShop

Infos:

https://sky-dream.fr/
mc.sky-dream.fr


Thank you very much for this amazing plugin et the amazing support

Big love ♥

**Comment by Ghost-chu** [comment]
> Roshar MC
> Discord is our website :) ~ discordapp.com/invite/HTKm88s



> @Ghost-chu
> can you censor OnePizza IP from your comment? [#43 (comment)](https://github.com/Ghost-chu/QuickShop-Reremake/issues/43#issuecomment-525621842)
> Thanks



> SwunkCraft
> swunkcraft.net



> @Ghost-chu
> FruitLab.gg
> https://fruitlab.gg/
> 
> I fixxed a couple of bugs and errors with you and tested the plugin <3 Best plugin and best developer ;)



> Hello,
> 
> I use QuickShop and I love this amazing plugin.
> 
> My Minecraft SkyBlock 1.15.2 server Sky-Dream use QuickShop
> 
> Infos:
> 
> https://sky-dream.fr/
> mc.sky-dream.fr
> 
> Thank you very much for this amazing plugin et the amazing support
> 
> Big love

All is done

**Comment by HenrikoMagnifico** [comment]
Hi! Thanks for making this great plugin, our players are loving it! Here's our server description;

**BITCraft** - HermitCraft-like survival and creative with a large focus on the community! Massive world with terrain from Alpha to Modern. Whitelisted.

Server IP: backintime.yao.cl:25566

[Website](https://discord.gg/m7tVB6J)

**Comment by DumplingSaint** [comment]
MCVantage - Survival, Skyblock, Creative, Build Server

https://mcvantage.us/

Thanks! Great plugin!

**Comment by love4nut** [comment]
Pcampus Network - Survival 1.16.2

IP: play.pcampus.net

Website: [www.pcampus.net](url)

Thanks! Great plugin!

**Comment by adsa562** [comment]
Name: 開拓之都 Pioneercraft
IP: pioneercraft.pw
Website: [https://www.pioneercraft.pw/](https://www.pioneercraft.pw/)

**Comment by Ghost-chu** [comment]
> Hi! Thanks for making this great plugin, our players are loving it! Here's our server description;
> 
> **BITCraft** - HermitCraft-like survival and creative with a large focus on the community! Massive world with terrain from Alpha to Modern. Whitelisted.
> 
> Server IP: backintime.yao.cl:25566
> 
> [Website](https://discord.gg/m7tVB6J)



> MCVantage - Survival, Skyblock, Creative, Build Server
> 
> https://mcvantage.us/
> 
> Thanks! Great plugin!



> MCVantage - Survival, Skyblock, Creative, Build Server
> 
> https://mcvantage.us/
> 
> Thanks! Great plugin!



> Name: 開拓之都 Pioneercraft
> IP: pioneercraft.pw
> Website: https://www.pioneercraft.pw/

done

**Comment by itslukemango** [comment]
Name: CraftYourTown
IP: mc.craftyourtown.com
Website: https://craftyourtown.com/

**Comment by Ghost-chu** [comment]
> https://craftyourtown.com/

done

**Comment by Nightwielder1** [comment]
Please update **RosharMC's** website to https://rosharshop.com/

**Comment by Ghost-chu** [comment]
Closed due we no longer accept requests since it removed from the overview.
