### ISSUE TITLE
[BUG]Essentials max-money Incompatible

### ISSUE THREAD

**Issue by KingofAnomaly** [Ghost-chu/QuickShop-Reremake#431]
**Describe the bug**
shops allow players to sell items even when the money received will put them above the max money limit. As a result players will not receive any of the money from this transaction.

**To Reproduce**
1. Have Essentials Installed
2. Modify the max-money value in essentials config.yml
3. Sell items that will put your balance above the max money limit
4. See how it gives you none of the money

**Expected behavior**
Prevent players from doing this and give them a message saying that this transaction would put them above the money limit.

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【REPLACE ME TO PASTE LINK】

**Additional context**

**Comment by sandtechnology** [comment]
Vault itself not provide API for this, it seems "Works As Intended", max-money implementation is plugin indenpent

**Comment by sandtechnology** [comment]
Please report to essentials, max-money implementation is plugin independent, for this case is their fault which should return failed EconomyResponse [Check there](http://milkbowl.github.io/VaultAPI/net/milkbowl/vault/economy/EconomyResponse.ResponseType.html)
