### ISSUE TITLE
[BUG] qs size

### ISSUE THREAD

**Issue by MarkGovor** [Ghost-chu/QuickShop-Reremake#433]
The qs size command doesn't work.
After entering the command qs size 10 displays a list of commandы.
![image](https://user-images.githubusercontent.com/31222605/79909579-e5a9fa80-8425-11ea-85af-115e546a72ff.png)

https://paste.enginehub.org/9DuyeDP_3

**Comment by Ghost-chu** [comment]
Did you have enable allow stack shop?
If this is disabled, the commands won't register.

**Comment by sandtechnology** [comment]
> 
> 
> Did you have enable allow stack shop?
> If this is disabled, the commands won't register.

  allow-stacks: false
Please enable stack shop

**Comment by MarkGovor** [comment]
Thanks!!!
