### ISSUE TITLE
[BUG]商店收购无名字和LORE的物品时，可以将带名字和LORE的物品出售

### ISSUE THREAD

**Issue by w1O42O86726** [Ghost-chu/QuickShop-Reremake#435]
**Describe the bug**
商店收购无名字和LORE的物品时，可以将带名字和LORE的物品出售
这还造成了库存占用的bug
**To Reproduce**
1. 创建一个收购普通物品的商店（该物品无任何LORE和名字）
2. 将箱子库存填满，只留一格空间
3. 将相同材质的的物品重命名
4. 将重命名的物品放置在箱子库存剩下的一格
5. 将普通物品出售给商店，箱子将会无法正常存储该物品

**Expected behavior**
应判断手中出售的物品是否完全跟收购的物品相同
应正确判断箱子内不同的物品，计算出正确的库存

**Screenshots**
![q1](https://user-images.githubusercontent.com/59788198/80001103-92e94500-84f0-11ea-987a-8404a2c42a09.png)
![q2](https://user-images.githubusercontent.com/59788198/80001113-97156280-84f0-11ea-92ff-a6a4430bb33b.png)
![q3](https://user-images.githubusercontent.com/59788198/80001121-98df2600-84f0-11ea-81ae-e7b3beb8fcb4.png)

**Comment by sandtechnology** [comment]
#418 在配置文件中将work-type设置为1使用bukkit匹配即可修复
