### ISSUE TITLE
[BUG] Shop creation cancelled by Towny in worlds where Towny is disabled (or) Claiming is disabled

### ISSUE THREAD

**Issue by Rishabh-Raghunath** [Ghost-chu/QuickShop-Reremake#436]
**Describe the bug**
Shop creation is being canceled by Integrations(Towny) even though Towny is disabled in the world using the `/tw toggle usingtowny` command(should work when `/tw toggle claimable` is used too). Hence no plots can be created in this world.

**To Reproduce**
1. Install Towny & Enable Towny Integration in config.yml for QuickShop
2. Enable /qs debug
3. Use `/tw toggle usingtowny` or `/tw toggle claimable` command from any world you like to have towny disabled or claiming disabled in the world.
4. Try to create a shop.
5. You can see creation is canceled by Integrations - Towny

**Expected behavior**
Since Towny is disabled in the world, Towny should not cancel the creation of shops using QuickShop.
In this case, other checks other than Towny can be checked to allow creation.

**Screenshots**
- n/a

**Comment by Ghost-chu** [comment]
confirmed



---Original---
