### ISSUE TITLE
[BUG]大部分玩家无法创建商店

### ISSUE THREAD

**Issue by w1O42O86726** [Ghost-chu/QuickShop-Reremake#439]
**Describe the bug**
新版本的quickshop似乎存在residence权限的检测问题，有时，拥有该领地权限的玩家无法创建领地，提示：没有权限：第三方插件 [{0}]。
当我将integration.residence.create修改为true时，创建商店还是提示没有权限，并且，箱子上的悬浮物会出现，每次创建都会出现一个悬浮物，并且会叠加起来，但仍旧无法创建商店，其他人点击也没有反应。

**Screenshots**
![2020-04-25_09 58 30](https://user-images.githubusercontent.com/59788198/80268763-7c9fdc80-86dc-11ea-85e4-bfcd86ffabe4.png)
![2020-04-25_10 03 25](https://user-images.githubusercontent.com/59788198/80268765-7d387300-86dc-11ea-9aa3-847fe399a549.png)

**Comment by sandtechnology** [comment]
感谢你的反馈，请提供以下信息：
1.paste链接 通过/qs paste获得
2.创建过程中服务器后台是否有报错信息？如果有，烦请粘贴出来

**Comment by w1O42O86726** [comment]
https://paste.enginehub.org/phRviBo2g
似乎没有任何报错
另外，quickshop有时调用vault经济的depositPlayer函数似乎会传入一个null的String name值

**Comment by sandtechnology** [comment]
https://cdn.discordapp.com/attachments/645891684277944320/703540414434508800/QuickShop-4.0.2.3-lab1.jar
请问在这个版本中问题修复了吗

**Comment by w1O42O86726** [comment]
你好，还未修复此问题，后台也没有任何报错
![7HVS0~_NNNP~9@%( 86387B](https://user-images.githubusercontent.com/59788198/80281297-af79bd00-873c-11ea-99ff-dfff3dfd2a58.png)

**Comment by sandtechnology** [comment]
> 
> 
> 你好，还未修复此问题，后台也没有任何报错
> ![7HVS0~_NNNP~9@%( 86387B](https://user-images.githubusercontent.com/59788198/80281297-af79bd00-873c-11ea-99ff-dfff3dfd2a58.png)

https://c-t.work/s/020cbad9800245
使用这个版本再试试呢 这次提示信息应该会改变

**Comment by w1O42O86726** [comment]
![QQ图片20200426120312](https://user-images.githubusercontent.com/59788198/80297491-f1931500-87b5-11ea-8b6c-42ad5a1b4a32.png)
提示信息似乎还没有提示是什么插件的原因

**Comment by sandtechnology** [comment]
> 
> 
> ![QQ图片20200426120312](https://user-images.githubusercontent.com/59788198/80297491-f1931500-87b5-11ea-8b6c-42ad5a1b4a32.png)
> 提示信息似乎还没有提示是什么插件的原因，并且在领地外也无法创建商店，此问题在先前的v3版本是没有出现的，在升级过程中我也没有添加、修改其它插件。

4.0中对这个检查的部分并没有进行任何修改 建议是先关闭residence的integration再试试

**Comment by w1O42O86726** [comment]
在这几次的测试中，我都进行了residence的integration开启和关闭的测试，结果都是一样的。

**Comment by Ghost-chu** [comment]
仅在residence领地中才有此问题吗

**Comment by Ghost-chu** [comment]
> https://paste.enginehub.org/phRviBo2g
> 似乎没有任何报错
> 另外，quickshop有时调用vault经济的depositPlayer函数似乎会传入一个null的String name值

这是Vault自己的问题，QuickShop都是传入OfflinePlayer，不传String，是Vault内部自己处理糊了

**Comment by sandtechnology** [comment]
> 
> 
> 在这几次的测试中，我都进行了residence的integration开启和关闭的测试，结果都是一样的。

我感觉是有插件阻止了建造 但是追踪系统并没有追踪成功（奇怪，理论上应该是可以的）
https://c-t.work/s/6759f500cc5d4a
请安装这个版本，然后在尝试创建商店后使用/qs paste获取paste链接并回复

**Comment by w1O42O86726** [comment]
> 仅在residence领地中才有此问题吗

现在发现不仅仅是在领地中有此问题，任何地方都有可能出现这个问题。大部分用户会出现无法创建商店的问题（少数用户不受影响），而且插件无法正常追踪到是什么插件阻止了建造。
此问题在更换为v3的最后一个版本后没有发生。

**Comment by w1O42O86726** [comment]
> > 在这几次的测试中，我都进行了residence的integration开启和关闭的测试，结果都是一样的。
> 
> 我感觉是有插件阻止了建造 但是追踪系统并没有追踪成功（奇怪，理论上应该是可以的）
> https://c-t.work/s/6759f500cc5d4a
> 请安装这个版本，然后在尝试创建商店后使用/qs paste获取paste链接并回复

https://paste.enginehub.org/ShgbuuZ1C

**Comment by sandtechnology** [comment]
https://c-t.work/s/ab2f837fb76844
再使用这个版本 试试是否能够成功追踪？
同时请提供加载此插件的日志，我感觉是遇到类冲突的情况了

**Comment by w1O42O86726** [comment]
> https://c-t.work/s/ab2f837fb76844
> 再使用这个版本 试试是否能够成功追踪？
> 同时请提供加载此插件的日志，我感觉是遇到类冲突的情况了

依旧无法成功追踪
https://paste.ubuntu.com/p/FYdmpSxgtD/
[latest.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/4537538/latest.log)

**Comment by Ghost-chu** [comment]
您好，请问关闭protection-checking后还有此问题吗

**Comment by w1O42O86726** [comment]
> 您好，请问关闭protection-checking后还有此问题吗

关闭后就没有问题了

**Comment by Ghost-chu** [comment]
这个估计就是NoCheatPlus反作弊的问题了
把和方块破坏（例如fastbreak等）有关的检测选项关闭即可



---原始邮件---
发件人: "w1O42O86726"<notifications@github.com&gt;
发送时间: 2020年4月27日(周一) 中午1:36
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Ghost_chu"<wyf001912hp@gmail.com&gt;;
主题: Re: [Ghost-chu/QuickShop-Reremake] [BUG]大部分玩家无法创建商店 (#439)




  
您好，请问关闭protection-checking后还有此问题吗
  
关闭后就没有问题了

**Comment by sandtechnology** [comment]
https://c-t.work/s/649d19ac99034a
请禁用protection-checking，然后使用residence的integration并关闭里面的whitelist-mode来解决此问题

**Comment by w1O42O86726** [comment]
谢谢！已经解决该问题
