### ISSUE TITLE
[BUG]在商店的侧面放置告示牌的时候当玩家点击商店时告示牌会被替换成商店的牌子

### ISSUE THREAD

**Issue by Chinglem** [Ghost-chu/QuickShop-Reremake#441]
也许本来就是这样设计的？
但是这样会让牌子锁被quickshop商店替换掉
我希望能让玩家使用牌子锁来决定自己的商店是否可以用漏斗将物品漏下去
这样可以制作一个一边收购一边出售的自动商店

**Comment by Chinglem** [comment]
或者是否可以在使用大箱子商店时能让两个商店共享同一个箱子里的物品

**Comment by sandtechnology** [comment]
对于牌子锁，QS有专门的兼容方式，可以看看config.yml的lockette选项

**Comment by Chinglem** [comment]
我调整过了，但是依然会被替换，刚才偶然发现大箱子商店和商店牌子在同一个面的牌子锁不会被替换

**Comment by sandtechnology** [comment]
请问在牌子锁中是怎么设置漏斗的呢？
应该需要添加兼容支持

**Comment by Chinglem** [comment]
不是同侧，是大箱子商店没有上牌子的那半个箱子不会被替换

**Comment by Chinglem** [comment]
牌子锁默认是禁止漏斗的

**Comment by Chinglem** [comment]
我使用的牌子锁是LockettePro 游戏版本1.15.2
在配置中似乎没看到禁用漏斗的选项

**Comment by Chinglem** [comment]
![image](https://user-images.githubusercontent.com/52785276/80311391-00a7b080-8812-11ea-8582-b6dbd2235a42.png)

**Comment by Chinglem** [comment]
在这样的情况下是不会被替换的

**Comment by sandtechnology** [comment]
请不要把Github当作QQ....
你这样是会导致我们被邮件轰炸的
将会添加相关支持

**Comment by Chinglem** [comment]
奥！抱歉！我下次注意，感谢

**Comment by sandtechnology** [comment]
https://c-t.work/s/8d6da7e938ff46
在这个版本中已修复
