### ISSUE TITLE
[BUG] SHOP DOESN'T CHECK WHO WROTE THE BOOK, WHO SIGN IT AND WHAT IS WRITTEN IN IT

### ISSUE THREAD

**Issue by DJDaPa** [Ghost-chu/QuickShop-Reremake#448]
**Describe the bug**
Problem is that I sign book and name it for exemple "1k" from now the book is original "1k" made by ME. Issue is that when someone sign book also "1k" he could sell it to my shop, even his book is original by HIM and my book si original by ME. Also you can sell any written book, even that the name is different.

**Expected behavior**
I Expected that when the book is original by me, the shop will notice and when someone try to sell his book sign by him the shop will not make the trade happen.

**Additional context**
I should be repairable because other chestshops for lower versions can recognize who sign the book and what the name of the book is.

**Comment by sandtechnology** [comment]
It's already fixed in the latest lab version
https://cdn.discordapp.com/attachments/645891684277944320/704723164516581386/QuickShop-4.0.2.3-lab9.jar
