### ISSUE TITLE
Tax not being deposited into account

### ISSUE THREAD

**Issue by ThatGuyLoz** [Ghost-chu/QuickShop-Reremake#45]
With tax enabled, tax-account set to "tax" and an account exists named "tax" the tax amount is not deposited when transaction completes. tax account remains empty. User based transactions work fine.

**Comment by mopsistudios1** [comment]
Not working for me so here is my info.
Server Version: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Economy (EssentialsEco): Essentials version 2.16.1.0
Vault: Vault version 1.7.2-b107
@Ghost-chu

**Comment by Ghost-chu** [comment]
Make sure you not trading yourself shop.

**Comment by mopsistudios1** [comment]
Don't think that's the problem because a) It's an adminshop b) I set the owner as another player. @Ghost-chu

**Comment by Ghost-chu** [comment]
AdminShop still is you, In database, the owner UUID still is you so AdminShop just a name for unlimited shop.

**Comment by mopsistudios1** [comment]
I changed the owner using /qs setowner @Ghost-chu

**Comment by univerme** [comment]
Will this issue be resolved? I can provide steps to reproduce if necessary

**Comment by Ghost-chu** [comment]
this issue is low priority, I have more bugs ams other things need todo.
Don't worry, if issue not closed, i will fixed someday.

**Comment by Ghost-chu** [comment]
Can't reproduce, maybe economy system issue.
