### ISSUE TITLE
[Feature] Disable protection

### ISSUE THREAD

**Issue by Binero** [Ghost-chu/QuickShop-Reremake#452]
**Describe the Feature**
It would be nice to have a way to disable protection against breaking chest shops. Right now players can grief by placing chest shops out in the wilderness. Charging upkeep works, but it would punish well-intentioned players. 

The shop should still protect against opening-closing it though.

**Comment by Ghost-chu** [comment]
shop.protection-checking, set to false
read example.config.yml to get more details.

**Comment by sandtechnology** [comment]
It doesn't having any difference between prevent break chest shops and opening-closing it, ,you still can get item from chest, so both would be protected.

**Comment by Binero** [comment]
> shop.protection-checking, set to false
> read example.config.yml to get more details.

@Ghost-chu  How does `protection-checking` relate to the issue above? The [example config](https://github.com/Ghost-chu/QuickShop-Reremake/blob/3396f0132134540160900a2c9b60deb381bbb434/src/main/resources/config.yml#L304) seems to suggest that is for shop _creation_, while this issue is for shop destruction. 

> And, you can use white-list mode to prevent shop was created in the wilderness.

@sandtechnology  That doesn't solve the issue either. People claim a chunk, set up shops, get rid of the claim. Furthermore, the plugin integrations barely work and have so many caveats that they are simply not worth using.

**Comment by sandtechnology** [comment]
> 
> 
> > shop.protection-checking, set to false
> > read example.config.yml to get more details.
> 
> @Ghost-chu How does `protection-checking` relate to the issue above? The [example config](https://github.com/Ghost-chu/QuickShop-Reremake/blob/3396f0132134540160900a2c9b60deb381bbb434/src/main/resources/config.yml#L304) seems to suggest that is for shop _creation_, while this issue is for shop destruction.
> 
> > And, you can use white-list mode to prevent shop was created in the wilderness.
> 
> @sandtechnology That doesn't solve the issue either. People claim a chunk, set up shops, get rid of the claim. Furthermore, the plugin integrations barely work and have so many caveats that they are simply not worth using.

So what you need is remove shop when a player unclaim it?
It will be implement as Feature

**Comment by Binero** [comment]
> So what you need is remove shop when a player unclaim it?

Not even that much. If there is just an option in the config to disable protection checks for when someone tries to destroy a shop, that's sufficient. 

As long as people build in land they own, be it through towny or world guard, then all is good. If they ever lose their area, or build in the wilderness, then anyone can just remove their shops.

**Comment by sandtechnology** [comment]
just disable lock option and it solved

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Binero** [comment]
That does two things though:

1. Stops chest from being opened.
2. Stops chests from being destroyed.

I guess the issue boils down to, can we have a different config option for the two of these.

**Comment by sandtechnology** [comment]
> 
> 
> That does two things though:
> 
>     1. Stops chest from being opened.
> 
>     2. Stops chests from being destroyed.
> 
> 
> I guess the issue boils down to, can we have a different config option for the two of these.


But claim itself have its protection, I think just disable shop lock will be fine.
