### ISSUE TITLE
[BUG] No Displayitem

### ISSUE THREAD

**Issue by Spaex** [Ghost-chu/QuickShop-Reremake#456]
If you place a Shop and a half block above (on my screen Quartz Slabs) there will be no more Preview Item above the chest. Worked finde in older versions but since the last update it seems broken.

**To Reproduce**
1. Place a Chest and on the block above a slab in the higher half.
2. Create a Chest
3. The Chest wont have an item above.
/qs reload and /qs clean or a restart didn't fix the problem.

**Expected behavior**
To display an item above the chest like before
**Screenshots**
![2020-05-08_19 29 50](https://user-images.githubusercontent.com/46825907/81433344-afc67f00-9164-11ea-98b0-3494ac5c058f.png)

**Paste link:**
https://paste.enginehub.org/9EDX6DReh

**Comment by Ghost-chu** [comment]
Plugin won't spawn display above the chest if that block not AIR or SIGN anymore.
