### ISSUE TITLE
Currency not withdrawn from owners account for unlimited sell chest

### ISSUE THREAD

**Issue by ThatGuyLoz** [Ghost-chu/QuickShop-Reremake#46]
when a chest is created as a sell chest, and unlimited the admin that created it can buy an infinite amount as it does not deduct the cost from their account. The same does not occur for an unlimited buy chest. 

Current workaround is to set the owner to a non-user e.g. "qsadmin" after which the user that created the unlimited sell chest will have the cost deducted from their account.

**Comment by Ghost-chu** [comment]
Turn on pay-unlimited-shop-owners in config.yml
