### ISSUE TITLE
[BUG] Destory perm allows shops to be removed anywhere.

### ISSUE THREAD

**Issue by jordanwilliams1** [Ghost-chu/QuickShop-Reremake#463]
**Describe the bug**
QuickShop's CANT be destroyed by ANYONE unless they have quickshop.other.destroy permission but this allows players to remove shops EVERYWHERE even if they don't have build permissions. (Sometimes players can just remove shops with a high eff-axe's in a build protected zone too. Please make it so the sign gets fully destroyed before removing the shop, only dose this with the destory perm)

https://www.youtube.com/watch?v=mTPDLzYhoI0&feature=youtu.be

**To Reproduce**
go up to someone's player's shop who isn't yours and run /qs remove, or go to a world guard protected area with an efficiency 10 axe and destroy a shop where you don't have build perms. (quickshop.other.destroy permission required)

**Expected behavior**
quickshop.other.destroy (Only remove shops if the user has build rights in the area, or make a different perm.)

**Screenshots**

**Paste link:**
universal glitch, This is not needed. 

**Additional context**
This has been broken for so long. Please fix it.

**Comment by sandtechnology** [comment]
Please disable shop lock and it solved.(lock option in config.yml)

**Comment by jordanwilliams1** [comment]
@sandtechnology It is disabled

  lock: false

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology It is disabled
> 
> lock: false

If you disable lock, you won't need quickshop.other.destroy, because in this case, shop will be protect by other protection plugins

**Comment by jordanwilliams1** [comment]
@sandtechnology No, because without the perm people cant destroy the shops.

**Comment by Ghost-chu** [comment]
Paste link is require

**Comment by Ghost-chu** [comment]
@sandtechnology thanks sand, let me tracking this issue.

**Comment by jordanwilliams1** [comment]
Here's the video of when they don't have the permission: https://www.youtube.com/watch?v=DyZIpRaoWtM&feature=youtu.be


Here's the paste:
https://differentcraft.net/paste-cc88505b65914b36a6afc6a6eb684326.txt

@Ghost-chu

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology thanks sand, let me tracking this issue.

Just check build permission and it solved, but I'm worried about compatibility with other plugin, also the behavior change influence.

**Comment by Ghost-chu** [comment]
reading the paste

**Comment by Ghost-chu** [comment]
okay, I got this:
so the player can create shop EVERYWHERE and NOBODY can remove it by destroy the block right?

**Comment by jordanwilliams1** [comment]
@Ghost-chu Correct. And if you give them the permission then they can destroy all shops with just /qs remove

**Comment by jordanwilliams1** [comment]
@Ghost-chu Players can only create shops in areas they're allowed to build in, But other players cant destroy the shops they've created even if they have build perms

**Comment by Ghost-chu** [comment]
Yes because plugin is designed for who creating, who destorying.

**Comment by Ghost-chu** [comment]
For solve the public share region cannot break other player's shop issue.
Try AdvancedMarketRegion and the QuickShop bridge

**Comment by Ghost-chu** [comment]
ARM will reset the region and also delete shops in this region to ready for next player to use.

**Comment by jordanwilliams1** [comment]
@Ghost-chu But then I will have the same problem in people's towns? Players can rent plots of the town owner. Then when the player leaves how will the mayor remove their shops?

**Comment by Ghost-chu** [comment]
so you can disable `shop-lock`, the plugin will no longer try to prevent shop breaking by others.
but still will prevent remove the shop through the command.

**Comment by jordanwilliams1** [comment]
@Ghost-chu lock is set to false, Surely if this is set to false it should only allow players to destroy ANYONE's shop as long as they have BUILD PERM's in the area?

**Comment by Ghost-chu** [comment]
If they can destroy the block in the area. They will destroy any shops in this area.
But still cannot remove it by the command `/qs remove` or any commands.

If player no perms destroy the block in the area. Both destroy and command won't work.

**Comment by sandtechnology** [comment]
> 
> 
> If they can destroy the block in the area. They will destroy any shops in this area.
> But still cannot remove it by the command `/qs remove` or any commands.
> 
> If player no perms destroy the block in the area. Both destroy and command won't work.
I check the code and found /qs remove can be used when you have quickshop.other.destroy permission, so may be we need a sub permission for this, quickshop.other.destroy.command and quickshop.other.destroy.build will be OK

**Comment by Ghost-chu** [comment]
[QuickShop-4.0.2.9-lab1.jar.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/4619364/QuickShop-4.0.2.9-lab1.jar.zip)
try this build

**Comment by Ghost-chu** [comment]
also need a new paste if you still failed in new build

**Comment by Ghost-chu** [comment]
[QuickShop-4.0.2.9-lab2.jar.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/4619424/QuickShop-4.0.2.9-lab2.jar.zip)
Try this one

**Comment by jordanwilliams1** [comment]
@Ghost-chu Thanks you. That jar fixed it.

**Comment by Ghost-chu** [comment]
Fixed confirmed. Close.
