### ISSUE TITLE
Taxe Error

### ISSUE THREAD

**Issue by Bossbirdyman51** [Ghost-chu/QuickShop-Reremake#468]
Hi,
I have this error when i buy an item in a player shop :
[QuickShop]: Deposit Failed and player name is NULL, you should check if your tax account in config.yml or shop owner is haven't played before. Provider (XConomy)

When is player is offline only

When is online the player don't have taxe

**Comment by sandtechnology** [comment]
Could you provide the paste link (Obtain by /qs paste?)

**Comment by sandtechnology** [comment]
Closed for no response for a week or longer.
