### ISSUE TITLE
[BUG] Blocked off double chests only recognize one half as stock

### ISSUE THREAD

**Issue by SydMontague** [Ghost-chu/QuickShop-Reremake#470]
**Description** 
When you create a shop at a double chest an block one side off (e.g. to protect it in your private claim) the shop will only recognize inventory in one side of the chest (probably the one with the sign).

**Steps**
1. Build a double chest
2. Create a shop at it
3. Put stock in it on all inventory slots
4. Update the sign, notice the correct amount of stock
5. put a solid block on top of the chest
6. Update the sign (e.g. hitting it once), notice the incorrect amount of stock

**Expected behavior**
The stock shouldn't change regardless of whether the chest is blocked off or not.

**Paste link:**
https://paste.enginehub.org/-QH26U_pf

**Comment by sandtechnology** [comment]
Such behavior was defined by Bukkit API, nothing we can do with it.
