### ISSUE TITLE
[BUG] Shops and /qs price display fake price

### ISSUE THREAD

**Issue by almandoro** [Ghost-chu/QuickShop-Reremake#473]
**Describe the bug**
Hello,

## left click on shop
I've found a bug, where after left click on shop price is fixed to 0.0 always.
Shop's price is changed for whole server.

If player A left click on shop, player B,C,X ... will always see bugged informations on sign.

Also:

## /qs price
After /qsprice 69.000 shop :
1) Chat displays, that price is set to 9.000
2) Shop displays, that price is 9000

**To Reproduce**
/qs price 1 -> should display 1, but displays nothing
/qs price 69000 -> should display 69000, but displays 9000
Left click on shop should not change display of price  actual (69000) to bugged (9000)

**Expected behavior**
Price is displayed properly.

**Screenshots**

## left click on shop
![image](https://user-images.githubusercontent.com/49877673/82960683-7773cd00-9fbb-11ea-811c-1d1280f1519f.png)
![image](https://user-images.githubusercontent.com/49877673/82960720-91151480-9fbb-11ea-9617-ab12b591229d.png)

## /qs price
![image](https://user-images.githubusercontent.com/49877673/82960926-2c0dee80-9fbc-11ea-95e0-83cb2d85f00a.png)
![image](https://user-images.githubusercontent.com/49877673/82960995-58c20600-9fbc-11ea-995d-072a745d0086.png)

 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【https://paste.enginehub.org/KnAtmzqLf】

**Comment by sandtechnology** [comment]
Cannot reproduce, It look like is eco plugin issue, try to enable disable-vault-format in config.yml to use built-in formatter solve this.

**Comment by almandoro** [comment]
As You said, QuickShop's String formatting resolved this issue.

Thanks!
