### ISSUE TITLE
[BUG] Maven Import Not Working

### ISSUE THREAD

**Issue by AbhikCodes2019** [Ghost-chu/QuickShop-Reremake#475]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【REPLACE ME TO PASTE LINK】

**Additional context**

**Comment by sandtechnology** [comment]
Please give more details about this, such as the log, screenshot and description.
