### ISSUE TITLE
[Feature/Question] EpicHoppers integration

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Ghost-chu/QuickShop-Reremake#476]
**Describe the Feature**
I'm using EpicHoppers and when hoppers from there put items into shops itemcount on sign doesnt refresh (hopper event is cancelled).

So:
My feature request is to add support for this plugin
OR
My question is that I cant find proper method in QS api to refresh shop sign/quantinity of items inside, so I would make an addon bridge within these two plugins myself. If someone would help me with that one I'll be gratefull

**Comment by sandtechnology** [comment]
You can check this:
https://github.com/Ghost-chu/QuickShop-Reremake/blob/c61b78fe0736a05ca52a0176298afe844d329214/src/main/java/org/maxgamer/quickshop/listener/BlockListener.java#L180-L197
or you can just turn off hopper protection in config.yml:

> protect:
>   explode: true
>   hopper: true
>   entity: true
