### ISSUE TITLE
[BUG] Jackson gives java.lang.VerifyError when separate plugin has newer/older version as (passthrough) dependency

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#479]
A full and detailed explanation of this bug can be found on the PaperMC issue tracker:
https://github.com/PaperMC/Paper/issues/3502

Currently used QuickShop version: 4.0.2.12
Server: PaperMC 334 (MC 1.15.2)

**Comment by sandtechnology** [comment]
https://cdn.discordapp.com/attachments/645891684277944320/718695951174467594/QuickShop-4.0.2.12-lab2.jar
Please check if it fixed.
