### ISSUE TITLE
Can't purchase items because QS falsely claims insufficient funds

### ISSUE THREAD

**Issue by jordankothe9** [Ghost-chu/QuickShop-Reremake#486]
The error goes:

"That costs (small amount of money) but you only have (very large amount of money)"

I am running the lastest version of The New Economy, the lastest version of quickshop (as of 6-27, 7pm est) and spigot 1.16.1

If any logs are required to track down the issue please let me know so I can provide you with that information. There weren't any obvious console logs as far as I'm aware.

![2020-06-27_15 31 05](https://user-images.githubusercontent.com/48492460/85933850-bb533e00-b8a9-11ea-8134-ae730fc6d068.png)

**Comment by sandtechnology** [comment]
Please give reproduce step and a paste (can obtain by /qs paste) after reproduce, also server log(if having any error)

**Comment by jordankothe9** [comment]
https://paste.enginehub.org/00-bVSVQO

https://imgur.com/a/yi0JULg

This happens at any shop at any time with any balance. Not sure what other steps you need

**Comment by sandtechnology** [comment]
You install two economy bridge plugin(Reserve and vault), please remove Reserve and try again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jordankothe9** [comment]
I will be unable to do extensive troubleshooting until later today, as I am away from my computer but disabling Vault did not resolve the issue and disabling TNE gave the "you don't have an Economy plugin installed" message.

I believe there is an issue with how I setup my Economy plugins to start with and 1.15 let me do it.

Thanks for all your help despite the limited information I'm providing. I will be more complete with my big reports in a few hours.

**Comment by Ghost-chu** [comment]
I think TNE may have an error to process the purchase.
Because if an internal error cuts down the process, the same error message will sent to the player.
![image](https://user-images.githubusercontent.com/30802565/85947326-98458e80-b97c-11ea-9a7f-714c95280a63.png)

Try Essentials Economy or other Economy plugin.

**Comment by jordankothe9** [comment]
I resolved the issue by deleting Reserve from my plugin folder. It wasn't even loaded fully (in /plugins) and I didn't think to try updating/disabling it. 

Reserve hasn't been updated since 1.14 and was working ok in 1.15 but 1.16 broke the plugin fully.
