### ISSUE TITLE
Change the variable

### ISSUE THREAD

**Issue by DjeyMute** [Ghost-chu/QuickShop-Reremake#49]
Hey i would like to change the variable [0] [1] [2]
Because i'm french and my money it's not '$' but '€' and in the sign they are this variable [0]
Can you do that?

**Comment by Ghost-chu** [comment]
The symbol is given by Vault, you should check your Economy plugin.

Of course, if QS not get symbol from Vault, they will use alternative-economy-symbol in config.yml for QS.
