### ISSUE TITLE
[Bug] Hopper minecarts can remove items from chest shops

### ISSUE THREAD

**Issue by EnderGal** [Ghost-chu/QuickShop-Reremake#492]
**Describe the Bug**
Hopper Minecarts can take items out of chest shops

**To Reproduce**
Steps to reproduce the bug**
1. Place a rail of any kind 1 block below the chest shop
2. Place a hopper minecart on top of the rail
4. See that the items flow out of the chest into the hopper, making stealing very easy.

**Expected behaviour**
The items shouldn’t be able to flow out of the chest, but instead say “That shop is locked” like when you try it with a normal hopper.

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【https://paste.enginehub.org/rONW1hDmP】

**Additional context**

**Comment by EnderGal** [comment]
https://youtu.be/FpR3Fgtzaws Here’s a video of the bug taking place, i thought videos would be better instead of screenshots

**Comment by sandtechnology** [comment]
paper.yml:

>     hopper:
>       cooldown-when-full: true
>       disable-move-event: true
this is not a bug, you chose disable-move-event, so we won't detect the steal behavior.
