### ISSUE TITLE
[BUG] Stack Size is bugged, doesn't work. Has no functionality.

### ISSUE THREAD

**Issue by MrAmos123** [Ghost-chu/QuickShop-Reremake#494]
**Describe the bug**
Right-clicking a shop to change the stack size doesn't work. It auto fills the command, the command itself does nothing.
Checking help for the plugin doesn't even show the size command there.

Maybe you forgot to code that specific command in?

**To Reproduce**
Right-click Shop
Click Stack Size
Change Value
<Nothing happens>

**Expected behavior**
Stack size to change and sign to update with new info.

https://paste.ubuntu.com/p/P3GNmpb47D/

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/issues/453
