### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by charlieisjesus** [Ghost-chu/QuickShop-Reremake#496]
**Describe the bug**
Randomly, /bal shows a blank text bar.

**To Reproduce**
1. Use this plugin
2. Buy something from a shop
3. Do /bal
4. Nothing shows, console doesnt send errors either

**Expected behavior**
It's supposed to tell you your balance, obviously.

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- Im not paying for pastebin just for this

**Additional context**

**Comment by Ghost-chu** [comment]
No quickshop issue, please ask for support to economy system author.
