### ISSUE TITLE
Shop doesnt removing [BUG]

### ISSUE THREAD

**Issue by VozikCZE** [Ghost-chu/QuickShop-Reremake#499]
**Describe the bug**

We use [AdvancedRegionMarket](https://www.curseforge.com/minecraft/bukkit-plugins/advancedregionmarket) for players markets, where they have own chest shops. But if the market expire and the plugin set a schematic in market, shops doesnt remove.

**To Reproduce**
1. Create shop in any region selling plugin.
2. Create shop.
3. Reset area in region.

**Expected behavior**
The shop should remove.

**Screenshots**
![2020-07-25_19 52 04](https://user-images.githubusercontent.com/48393384/88463063-5d1d7900-ceb0-11ea-87b0-f5d1fc26fe5d.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/scmPCghMXq/

**Additional context**
-

**Comment by sandtechnology** [comment]
Please use this addon: https://www.spigotmc.org/resources/advancedregionmarket-shop-bridge.77484
