### ISSUE TITLE
[Feature] Add ability to disable Item Showcase on top of the Chest

### ISSUE THREAD

**Issue by MrAmos123** [Ghost-chu/QuickShop-Reremake#500]
**Describe the Feature**
Add a toggleable ability to disable the Item Showcase from the top of the chest as some player-shops have MASSIVE shops and people with not so quite good PC's get HUGE performance hits.

I have a decent PC, but I go from 200 FPS to 60-90 in one of my player shops.

I am aware there's an option in the configuration, but I don't want to disable it for everyone. Just shops where they're very big.

The despawn range isn't much use as too small and it's pointless. 16 is a good range but still isn't small enough for these large shops. 

An option to disable showcase needs to be made available in the owner-shop-settings when right-clicking the sign.

**Screenshots**
https://i.imgur.com/lyIcZ2W.png

**Comment by sandtechnology** [comment]
What about using `display-auto-despawn` in config.yml?

**Comment by MrAmos123** [comment]
@sandtechnology Not good enough still kills people's PCs when there are multi-floor compact shops.

Unless I put the update time to 1 second (20 ticks) and the radius really small, like 4-6 blocks. But that seems like a really dumb way of doing it.

A better way would be to give the user the option to disable the item showcase.

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology Not good enough still kills people's PCs when there are multi-floor compact shops.
> 
> Unless I put the update time to 1 second (20 ticks) and the radius really small, like 4-6 blocks. But that seems like a really dumb way of doing it.
> 
> A better way would be to give the user the option to disable the item showcase.

I find is not the showcase causing lag but colored sign(by just disable item-display), I will focus on changing sign display logic

**Comment by sandtechnology** [comment]
> 
> 
> > @sandtechnology Not good enough still kills people's PCs when there are multi-floor compact shops.
> > Unless I put the update time to 1 second (20 ticks) and the radius really small, like 4-6 blocks. But that seems like a really dumb way of doing it.
> > A better way would be to give the user the option to disable the item showcase.
> 
> I found is not the showcase causing lag but colored sign(by just disable item-display), I will focus on changing sign display logic

And ends with a mojang bug, I have trying with no display item and no text on sign, still low tps, then I find this bug: https://bugs.mojang.com/browse/MC-5169
So....there are no way to fix this except not use signs...
