### ISSUE TITLE
Sponge版有吗XD

### ISSUE THREAD

**Issue by zsn741656478** [Ghost-chu/QuickShop-Reremake#52]
不知道有没有，来问下 XD

**Comment by Ghost-chu** [comment]
有计划，但是由于对SpongeAPI不熟悉，所以目前弃坑了

**Comment by MrRobotVPN** [comment]
I know I am not the only one that wants a SpongeAPI 7 version of this. It is an amazing plugin!
https://docs.spongepowered.org/master/en/

https://github.com/KaiKikuchi/QuickShop/issues/101

**Comment by Ghost-chu** [comment]
No plan before Sponge support 1.13 or 1.13+



---原始邮件---
发件人: "MrRobotVPN"<notifications@github.com&gt;
发送时间: 2019年11月19日(星期二) 晚上7:41
收件人: "Ghost-chu/QuickShop-Reremake"<QuickShop-Reremake@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Ghost_chu"<wyf001912hp@gmail.com&gt;;
主题: Re: [Ghost-chu/QuickShop-Reremake] Sponge版有吗XD (#52)



I know I am not the only one that wants a SpongeAPI 7 version of this. It is an amazing plugin!
 https://docs.spongepowered.org/master/en/
 
KaiKikuchi/QuickShop#101
