### ISSUE TITLE
[BUG] Seller has not received money for transaction

### ISSUE THREAD

**Issue by Bloodlex** [Ghost-chu/QuickShop-Reremake#521]
**Describe the bug**
A player has not received money for transaction.

**To Reproduce**
Log:
[2020-07-31 08:35:34.93] Player John bought Alex shop Shop world(222, 63, 187) Owner: Alex - 674068a8-1e47-3b3f-b9e8-7000f1b75ebc Price: 200.0 for items x54 for $10.260,00 ($0,05 tax).
[2020-07-31 08:35:34.93] Player John had 141566.72513564478 after trading.

Player Alex hasn't received his money for this transaction.

**Expected behavior**
Player Alex should receive money.

**Screenshots**
No screenshots.

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
https://paste.enginehub.org/B1DwQciQG

**Additional context**
No other information relevant.

**Comment by Ghost-chu** [comment]
Cannot found `John` and `Alex` purchase logs in the paste. **Don't mask the username because we need that to debug.**
If you mean is AdminShop -- The player won't receive money if `pay-shop-owner ` disabled in the configuration.
Also please download the latest snapshot and test it: 
**BACKUP**
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/lastSuccessfulBuild

**Comment by Ghost-chu** [comment]
![image](https://user-images.githubusercontent.com/30802565/89053765-4aacaf00-d38a-11ea-8d75-83dc9987d0a7.png)
It works for me, the base balance is `10000`

**Comment by Bloodlex** [comment]
I'm sorry I thought it would be easier for you and I totally forgot that you see that in logs.
John - **Barti1234567897** - buyer
Alex - **Kubcio** - seller

New log after updating to last developer version
https://paste.enginehub.org/hzw2AcWVj

Here also this case:

> [2020-07-31 20:16:11.449] Player Kubcio bought Barti1234567897 shop Shop world(213, 63, 178) Owner: Barti1234567897 - e26f06a7-f7ea-3350-92b7-2efb9307a1a0 Price: 1000.0 for items x1 for $950,00 ($0,05 tax).
> [2020-07-31 20:16:11.449] Player Kubcio had 22933.567211409823 after trading.

Tax was deducted, but the cash didn't arrive. By the way, maybe it would be beneficial to log the balance of both sides of a transaction before and after the transaction? And why it says only 0,05$ task when the price was 1000 but in reality 50 so 0,05% rather than 0,05$?

These are not admin shops, but regular ones.

It doesn't happen all the time, only from time to time. And it started today. Please help 😢

**Comment by sandtechnology** [comment]
> 
> 
> I'm sorry I thought it would be easier for you and I totally forgot that you see that in logs.
> John - **Barti1234567897** - buyer
> Alex - **Kubcio** - seller
> 
> New log after updating to last developer version
> https://paste.enginehub.org/hzw2AcWVj
> 
> Here also this case:
> 
> > [2020-07-31 20:16:11.449] Player Kubcio bought Barti1234567897 shop Shop world(213, 63, 178) Owner: Barti1234567897 - e26f06a7-f7ea-3350-92b7-2efb9307a1a0 Price: 1000.0 for items x1 for $950,00 ($0,05 tax).
> > [2020-07-31 20:16:11.449] Player Kubcio had 22933.567211409823 after trading.
> 
> Tax was deducted, but the cash didn't arrive. By the way, maybe it would be beneficial to log the balance of both sides of a transaction before and after the transaction? And why it says only 0,05$ task when the price was 1000 but in reality 50 so 0,05% rather than 0,05$?
> 
> These are not admin shops, but regular ones.
> 
> It doesn't happen all the time, only from time to time. And it started today. Please help 😢
> 
> Maybe some other plugin is messing with that? Quickshoplist, Plan, LastLoginAPI, OreAnnouncer I think these are plugins I updated last time.

https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/lastSuccessfulBuild
How about the latest version?

**Comment by Bloodlex** [comment]
> > I'm sorry I thought it would be easier for you and I totally forgot that you see that in logs.
> > John - **Barti1234567897** - buyer
> > Alex - **Kubcio** - seller
> > New log after updating to last developer version
> > https://paste.enginehub.org/hzw2AcWVj
> > Here also this case:
> > > [2020-07-31 20:16:11.449] Player Kubcio bought Barti1234567897 shop Shop world(213, 63, 178) Owner: Barti1234567897 - e26f06a7-f7ea-3350-92b7-2efb9307a1a0 Price: 1000.0 for items x1 for $950,00 ($0,05 tax).
> > > [2020-07-31 20:16:11.449] Player Kubcio had 22933.567211409823 after trading.
> > 
> > 
> > Tax was deducted, but the cash didn't arrive. By the way, maybe it would be beneficial to log the balance of both sides of a transaction before and after the transaction? And why it says only 0,05$ task when the price was 1000 but in reality 50 so 0,05% rather than 0,05$?
> > These are not admin shops, but regular ones.
> > It doesn't happen all the time, only from time to time. And it started today. Please help 😢
> > Maybe some other plugin is messing with that? Quickshoplist, Plan, LastLoginAPI, OreAnnouncer I think these are plugins I updated last time.
> 
> https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/lastSuccessfulBuild
> How about the latest version?

Yes, I tried. Didn't help unfortunately :(

**Comment by sandtechnology** [comment]
> 
> 
> > > I'm sorry I thought it would be easier for you and I totally forgot that you see that in logs.
> > > John - **Barti1234567897** - buyer
> > > Alex - **Kubcio** - seller
> > > New log after updating to last developer version
> > > https://paste.enginehub.org/hzw2AcWVj
> > > Here also this case:
> > > > [2020-07-31 20:16:11.449] Player Kubcio bought Barti1234567897 shop Shop world(213, 63, 178) Owner: Barti1234567897 - e26f06a7-f7ea-3350-92b7-2efb9307a1a0 Price: 1000.0 for items x1 for $950,00 ($0,05 tax).
> > > > [2020-07-31 20:16:11.449] Player Kubcio had 22933.567211409823 after trading.
> > > 
> > > 
> > > Tax was deducted, but the cash didn't arrive. By the way, maybe it would be beneficial to log the balance of both sides of a transaction before and after the transaction? And why it says only 0,05$ task when the price was 1000 but in reality 50 so 0,05% rather than 0,05$?
> > > These are not admin shops, but regular ones.
> > > It doesn't happen all the time, only from time to time. And it started today. Please help 😢
> > > Maybe some other plugin is messing with that? Quickshoplist, Plan, LastLoginAPI, OreAnnouncer I think these are plugins I updated last time.
> > 
> > 
> > https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/lastSuccessfulBuild
> > How about the latest version?
> 
> Yes, I tried. Didn't help unfortunately :(

I have update this, this build will update after a commit pushed, so you need to re-download the latest build :D.

**Comment by Bloodlex** [comment]
Aaaa okay, I'll do it now 👍

**Comment by Bloodlex** [comment]
By the way, have something been changed about the shop control panel with right-click? My players complain they couldn't change price for instance because the panel treated them as buyers not owners in this build before this latest build 😄

**Comment by sandtechnology** [comment]
> 
> 
> By the way, has something been changed about the shop control panel with right-click? My players complain they couldn't change price for instance because the panel treated them as buyers not owners in this build before this latest build 😄

Yes it's a another bug which I have fixed in the latest commit, the latest build will fix it.
By the way, it's this bug happened again since switch to Build #85/84?

**Comment by Bloodlex** [comment]
> > By the way, has something been changed about the shop control panel with right-click? My players complain they couldn't change price for instance because the panel treated them as buyers not owners in this build before this latest build 😄
> 
> Yes it's a another bug which I have fixed in the latest commit, the latest build will fix it.
> By the way, it's this bug happened again since switch to Build #85/84?

This bug with not paying happened already on the last public build from Spigot resources. We noticed it today.

**Comment by sandtechnology** [comment]
If this issue still appeared in the latest SNAPSHOT build, please rollback to 4.0.3.3 until a new version released:https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/download?version=345790

**Comment by Bloodlex** [comment]
> If this issue still appeared in the latest SNAPSHOT build, please rollback to 4.0.3.3 until a new version released:https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/download?version=345790

Thanks I'll revert to that for now and check (4.0.3.3). I think it was all right back then yet, but I'm not sure, will test it.

Could you please add to logs the balance of both sides, buyer and seller before and after transaction?

**Comment by sandtechnology** [comment]
Added, Is the issue still persisted in this build? 
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/94/

**Comment by Bloodlex** [comment]
> Added, Is the issue still persisted in this build?
> https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/94/

Thanks, I'll check that and let you know 👍

**Comment by Bloodlex** [comment]
> Added, Is the issue still persisted in this build?
> https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/94/

I think Seller balance is missing from the log, I see only Buyer, could you also add Seller balance? It's important in this case, because this kind behavior affected the Seller not receiving money.

`[2020-08-02 16:13:13.547] Player Bloodlex had 559.6939097557864 before trading.
[2020-08-02 16:13:13.553] Player Bloodlex bought wthr shop Shop world(203, 64, 214) Owner: wthr - 9627e194-2a02-317a-a916-b2cc55f30a01 Price: 15.0 for items x1 for $15,00 ($0,00 tax).
**Owner balance before trading:**
**Owner balance after trading:**
[2020-08-02 16:13:13.553] Player Bloodlex had 544.6939097557864 after trading.`

**Comment by sandtechnology** [comment]
> 
> 
> > Added, Is the issue still persisted in this build?
> > https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/94/
> 
> I think Seller balance is missing from the log, I see only Buyer, could you also add Seller balance? It's important in this case, because this kind behavior affected the Seller not receiving money.
> 
> [2020-08-02 16:13:13.547] Player Bloodlex had 559.6939097557864 before trading.
> [2020-08-02 16:13:13.553] Player Bloodlex bought wthr shop Shop world(203, 64, 214) Owner: wthr - 9627e194-2a02-317a-a916-b2cc55f30a01 Price: 15.0 for items x1 for $15,00 ($0,00 tax).
> **Owner balance before trading:**
> **Owner balance after trading:**
> [2020-08-02 16:13:13.553] Player Bloodlex had 544.6939097557864 after trading.

Added: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/95/

**Comment by Bloodlex** [comment]
> > > Added, Is the issue still persisted in this build?
> > > https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/94/
> > 
> > 
> > I think Seller balance is missing from the log, I see only Buyer, could you also add Seller balance? It's important in this case, because this kind behavior affected the Seller not receiving money.
> > [2020-08-02 16:13:13.547] Player Bloodlex had 559.6939097557864 before trading.
> > [2020-08-02 16:13:13.553] Player Bloodlex bought wthr shop Shop world(203, 64, 214) Owner: wthr - 9627e194-2a02-317a-a916-b2cc55f30a01 Price: 15.0 for items x1 for $15,00 ($0,00 tax).
> > **Owner balance before trading:**
> > **Owner balance after trading:**
> > [2020-08-02 16:13:13.553] Player Bloodlex had 544.6939097557864 after trading.
> 
> Added: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/95/

Thanks, that's exactly what I meant 👍 I have to test it now, but meanwhile there is a little typo:

[2020-08-02 17:35:59.005] Player Bloodlex had 696.6035097557864 before trading.
[2020-08-02 17:35:59.006] Shop Owner Miro_PL had 122590.602225 before trading.
[2020-08-02 17:35:59.016] Player Bloodlex bought Miro_PL shop Shop world(231, 63, 178) Owner: Miro_PL - efb7e784-35aa-3316-9040-30eb87b0c492 Price: 5.6 for items x10 for $56,00 ($0,00 tax).
[2020-08-02 17:35:59.016] Player Bloodlex had 640.6035097557864 after trading.
[2020-08-02 17:35:59.017] Shop Owner Miro_PL had 122646.602225 **before** trading.

It should be "**after**" not before here.

One more thought on that: Is it doable to add item name that has been bought to this log too? Would be beneficial if I look up for a specific trade, players often remember what they bought, so it would be easier to track it.

**Comment by sandtechnology** [comment]
Tanks for testing! Added and fixed: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/96/

**Comment by Bloodlex** [comment]
> Thanks for testing! Added and fixed: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/96/

Thanks! It's great now 👍 Let me check that with my players and see it it's all right already.

**Comment by Bloodlex** [comment]
I've found a bug, but I guess it's only related to the message shown to player:

"player-bought-from-your-store-tax": "&c{0} purchased {1} {2} from your shop, and you paid {3} in taxes.",

{3} is the amount earned, not the tax. Could you please include earned amount and also in brackets maybe amount in tax like _earned_ (in tax: _tax_)?

**Comment by sandtechnology** [comment]
This release will fix it: https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/download?version=348611
Due to the string changing, such change will delay to next release.

**Comment by Bloodlex** [comment]
> This release will fix it: https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/download?version=348611
> Due to the string changing, such change will delay to next release.

Okay, thanks, should I create an separate issue for that?

**Comment by sandtechnology** [comment]
Sorry for late reply, but if the issue didn't solved, please reopen this issue.
