### ISSUE TITLE
Command/Feature /qs size not working

### ISSUE THREAD

**Issue by supawiz6991** [Ghost-chu/QuickShop-Reremake#533]
Hi:
Running MC Paper 1.16
Latest Version of the plugin.

Players are able to create a shop but when trying to adjust the quantity by either right clicking the sign and clicking change next to "per bulk amount" or doing /qs size <amount>, the plugin responds with the help text acting as though the command was entered incorrectly.

I see no errors in console, only the commands being auto run by the sign and manually.
Screen shot of the output.
![qs_bug](https://user-images.githubusercontent.com/5490300/89391123-c0d84b00-d6d5-11ea-8a12-7d543d3449f9.png)

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/issues/453

**Comment by supawiz6991** [comment]
Thanks for linking that. Sorry I missed it. I did look back through the issues to see if one existed but apparently didn't go back far enough.
