### ISSUE TITLE
[BUG] Not showing enchantment levels of books in shop panel

### ISSUE THREAD

**Issue by Bloodlex** [Ghost-chu/QuickShop-Reremake#535]
**Describe the bug**
Not showing enchantment levels for enchanted books when on sale in shop panel.

**To Reproduce**
1. Create chest shop with enchanted books with higher levels.
2. As buyer click on a chest shop to open shop panel.
3. You cannot see what enchantment levels a book has.

**Expected behavior**
You should see the enchantment levels on books.

**Screenshots**
![notshowing](https://user-images.githubusercontent.com/1086720/89644200-b07fc600-d8b7-11ea-949a-0c6a61cfbdaf.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
https://paste.enginehub.org/Pcny3eXj9

**Additional context**
None.

**Comment by sandtechnology** [comment]
This version should fix it: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/115/
