### ISSUE TITLE
[BUG]Written Book Shops have to be updated every server reload

### ISSUE THREAD

**Issue by Littledanno** [Ghost-chu/QuickShop-Reremake#537]
Whenever the minecraft server I am on reloads, the written books change ID and therefore the quickshops don't work for any written books until the shop is reset, merely stating there are "o" to sell even though the shop contains them. Is there a workaround for this?

**To Reproduce**
Place a written book into a quickshop, reload the server.

**Paste link:**
I cannot do this as I am not the server owner :/

**Comment by sandtechnology** [comment]
Yes we have a workaround, just change the work-mode to 0 to using QS matcher will solve it.
