### ISSUE TITLE
QS Matcher didn't solve Written Book Shop Issue

### ISSUE THREAD

**Issue by Littledanno** [Ghost-chu/QuickShop-Reremake#539]
"Yes we have a workaround, just change the work-type to 0 in config.yml to use QS matcher will solve it.
_Originally posted by @sandtechnology in https://github.com/Ghost-chu/QuickShop-Reremake/issues/537#issuecomment-671896348_"

UPDATE:
Unfortunately this did not solve the situation, but instead made it a little worse. Now, any written book can be sold to any quickshop that is buying a specific written book. 
For example, some of the server users have created gambling redstone circuits, whereby when a player wins they get a certain named book, with text inside the book to prove that it's valid and not a copy when they sell it to get the prize money. 
Now, anyone can sell any written book to this shop and gain the prize money.

Unsure if this helps, but the server runs a version of the slimefun plugin - could this be causing the issues? Whenever a player write clicks a written book slimefun runs an event to check if its a slimefun book.

**Comment by Ghost-chu** [comment]
We save the items as Yaml, so bukkit will convert item to Yaml and load it from Yaml to ItemStack.
But sadly, Bukkit serializer is not perfact, some NBTs won't save into the Yaml string such as Clickable Event.
So this maybe is reason that why matcher cannot correctly match it.

Althrough it works for most items, but unfortunately some items not.

Bukkit not given other better way to serialize and deserialize, so this might cannot to fix or we need use NMS to load and save datas and that's is we didn't want, because it will harm plugin cross-version compatibility.

**Comment by sandtechnology** [comment]
Could you give the book shop position and the paste link which obtained by /qs paste?

**Comment by Littledanno** [comment]
It's weird, because I've just added a few different written books into my inventory, and some of them it will let me sell and some not... even though they are all different to the one the shop is buying.
Sadly, I can't do the command /qs paste on the server as I do not have permission :(

**Comment by Ghost-chu** [comment]
Some works, some not, because `Bukkit serializer is not perfact,, some NBTs won't save into the Yaml string`

**Comment by Littledanno** [comment]
After trying to do a quick test (I have screen recorded this) it only appears to effect written books that have been signed and closed and/or copied.
If you rename the written book in an anvil to add colour to the title of the book, the issue no longer occurs.

**Comment by sandtechnology** [comment]
> 
> 
> After trying to do a quick test (I have screen recorded this) it only appears to effect written books that have been signed and closed and/or copied.
> If you rename the written book in an anvil to add colour to the title of the book, the issue no longer occurs. Which is very odd.
> 
> YouTube Video link here; https://youtu.be/b3FUpl2uERA (however, if you create two books with the same coloured name and different contents, it still has the same issue)

And I found the issue is a typo lol, I will fix it soon.

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/123/
How about this version?

**Comment by Littledanno** [comment]
I will send this to server admin and let you know :)

**Comment by Ghost-chu** [comment]
> I will send this to server admin and let you know :)
> 
> UPDATE: Admin will reload the server and try this fix tonight. Should be able to give feedback tonight or tomorrow morning :)

Server admin can use PlugMan to reload the QuickShop.

**Comment by Littledanno** [comment]
Unfortunately it did not work. The original issue still exists where when the server reloads, the shops no longer recogonise the books as the ID of the books have changed somehow :( sad times

**Comment by sandtechnology** [comment]
> 
> 
> Unfortunately it did not work. The original issue still exists where when the server reloads, the shops no longer recognise the books as the ID of the books have changed somehow :( sad times
How about re-create the shop? it's still happening like in video?

**Comment by Littledanno** [comment]
> How about re-create the shop? it's still happening like in video?

When creating a shop, the plugin works and is able to tell the difference between the books :)

**Comment by sandtechnology** [comment]
> 
> 
> > How about re-create the shop? it's still happening like in video?
> 
> When creating a shop, the plugin works and is able to tell the difference between the books :)

so this issue solved?

**Comment by Littledanno** [comment]
Yeah, just the original issue of the shop no longer recognise the books as the ID of the books have changed, but no idea how or why

**Comment by sandtechnology** [comment]
> 
> 
> Yeah, just the original issue of the shop no longer recognise the books as the ID of the books have changed, but no idea how or why

Bukkit will handle books with different way, which raised the another bug: https://github.com/PaperMC/Paper/issues/198
So may be is the problem.
