### ISSUE TITLE
[Feature] Add money earned to message after purchase

### ISSUE THREAD

**Issue by Bloodlex** [Ghost-chu/QuickShop-Reremake#548]
**Describe the Feature**
Message after someone bought from a player's shop:
"player-bought-from-your-store-tax": "&c{0} purchased {1} {2} from your shop, and you paid {3} in taxes.",

Could you please include also the amount earned by the player?

For instance:

"player-bought-from-your-store-tax": "&c{0} purchased {1} {2} from your shop, **you earned {3}** (paid {4} in taxes)."

where {3} is the amount earned and {4} is the amount paid in taxes

My players would love to see this feature 😃

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/198/
