### ISSUE TITLE
Additional config node for maximum sell price.

### ISSUE THREAD

**Issue by CodeByCam** [Ghost-chu/QuickShop-Reremake#55]
**Version:** Minecraft 1.13.2 | Paper Build 565
**Quickshop:** 1.3.6 Beta 1

Currently, there is no maximum price, so players can define whatever (ridiculous) price they want which breaks the sign output and could cause other issues with economy plugins:

![](https://i.imgur.com/bPKyU8x.jpg)
![](https://i.imgur.com/T6WRs6s.png)

**Comment by Ghost-chu** [comment]
added in 1.3.6
