### ISSUE TITLE
[BUG] Item preview remains after shop is removed

### ISSUE THREAD

**Issue by vox4455** [Ghost-chu/QuickShop-Reremake#554]
After removing my players shops the item preview entity remains just sitting on the ground. happens when shop is removed by either braking the chest in creative or using world edit to clear out an area.

I even removed the plugin jar and rebooted the server and the entities remain. for a few min but eventually disappear.

I can't remove the plugin jar to clear them when ever this happens.

**Comment by sandtechnology** [comment]
1.Please remove the shop by a correct way (/qs remove)
2.In this case, you can do /qs reload to fix it
3.Missing issue template, please report with it
