### ISSUE TITLE
[BUG] Update checks reports a new version "[31]" while latest release is used.

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#556]
**Describe the bug**
Using 4.0.4.9 will QuickShop constantly print this Update notification:
```
[15:03:46 INFO]: [QuickShop] A new version of QuickShop has been released! [31]
[15:03:46 INFO]: [QuickShop] Update here: https://www.spigotmc.org/resources/62575/
```

**To Reproduce**
1. Use latest version (4.0.4.9)
2. Have update checks enabled

**Expected behavior**
The plugin should only notify about actual new releases

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.enginehub.org/8SqVbJhxe

**Additional context**
This is most likely the cause of the new update check system checking against latest Jenkins build, seeing a difference and reporting it as a "new" version even tho the release on Spigot hasn't changed.

The Check system should imo return to checking the Spigot release, using their [XenforoResourceManagerAPI](https://github.com/SpigotMC/XenforoResourceManagerAPI)

**Comment by sandtechnology** [comment]
We now using Jenkins build id to check update and no longer use spigot version.
And I upload wrong version which from snapshot channel : (
Please use this version, I will change it later : https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake/lastSuccessfulBuild/
