### ISSUE TITLE
Written Books shops break after reload [BUG]

### ISSUE THREAD

**Issue by jordanwilliams1** [Ghost-chu/QuickShop-Reremake#557]
**Describe the bug**

**To Reproduce**
Create a written book and sell it in a shop, Restart the server and the shop will say it has 0 in stock and no longer recognise it. 

**Expected behavior**
To recognise the item after a server restart and not have to re-create the shop everytime.

**Paste link:**
https://paste.enginehub.org/240Mug5Xf

Test Server download:

http://differentcraft.net/QuickShop-Server.zip

(Files updated to dev builds on 26/08/2020)

**Comment by sandtechnology** [comment]
what about change work-type to 0?

**Comment by jordanwilliams1** [comment]
@sandtechnology This seems to fix it, Any reason why it wouldn't be set to 0 by default?

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology This seems to fix it, Any reason why it wouldn't be set to 0 by default?

To support more accurate comparing, but look like is a good idea to set to 0 by default.
