### ISSUE TITLE
[BUG] Shops no longer work

### ISSUE THREAD

**Issue by StenaCS** [Ghost-chu/QuickShop-Reremake#558]
**Describe the bug**
The chestshops no longer work

**To Reproduce**
Just try and buy or sell

**Expected behavior**
They worked fined before the update

**Screenshots**
There no error just nothing happens

**Paste link:**
https://paste.enginehub.org/trfaS92gt

**Comment by sandtechnology** [comment]
How did you update the plugin, from which version?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by StenaCS** [comment]
| QuickShop-4.0.4.9.jar
-- | --

**Comment by sandtechnology** [comment]
> 
>   	QuickShop-4.0.4.9.jar

It's not the latest version....
what about previous version?
and how do you update the plugin?

**Comment by StenaCS** [comment]
I just had my players delete everything and reinstalled latest version, much easier than trying to figure out which version it was in between.
