### ISSUE TITLE
Shop Owner Doesn't Recieve Gold

### ISSUE THREAD

**Issue by xCptSpiffyx** [Ghost-chu/QuickShop-Reremake#559]
**Describe the bug**
When someone buys from the shop, the money will be taken from the customers account but will not transfer to the shop owners account.

**To Reproduce**
1. Create chest shop with a price and items to sell
2. Get someone to purchase from store
3. See error

**Expected behavior**
Expecting the gold to go from the buyers account into the shop owners account.

**Screenshots**
[https://cdn.discordapp.com/attachments/698335371645288518/749039887503851623/2020-08-28_23.49.56.png](url)

**Additional context**
Won't show up in inventory, ender chest, on ground or town bank. Economy plugins that I have are Vault, TheNewEconomy and Towny.

**Comment by Ghost-chu** [comment]
We can't offer supporting without required paste file.

**Comment by xCptSpiffyx** [comment]
How do I send paste file? I think I originally posted if you look at edit history

**Comment by xCptSpiffyx** [comment]
https://paste.enginehub.org/Aq_cC_x_l

Here you go

**Comment by sandtechnology** [comment]
It should be a eco plugin issue, you should report this to them (TheNewEconomy)
