### ISSUE TITLE
Player can not see the Buy&sell log![BUG]

### ISSUE THREAD

**Issue by Hypocisy** [Ghost-chu/QuickShop-Reremake#560]
**Describe the bug**
When Player login to server,Quckshop dose not sending sell&buy log to players.
**To Reproduce**
1. After a period of time, Player has login to server.
2. And Console having reported the error.

**Expected behavior**
Player can not see their buy&sell log when login to server.

**Screenshots**
![I7HV2B3T4JB_7OJ` `102$X](https://user-images.githubusercontent.com/43266516/91642098-1f85b000-ea5b-11ea-83b4-a9d2f1aa7094.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
- https://paste.enginehub.org/qj52dBwOV
- ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

**Additional context**
Please help me, your plugin are aways useful to me.Hope your plugin keeping healthy and more useful!!

**Comment by Ghost-chu** [comment]
Bug confirmed. @sandtechnology

**Comment by Ghost-chu** [comment]
Seems class not loaded correctly for some reason.

**Comment by sandtechnology** [comment]
> 
> 
> Seems class not loaded correctly for some reason.

It's strange, look like a enchantment level return NULL......
I will add a null check in RomanNumber

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/142/
It should fix it
