### ISSUE TITLE
[BUG] Custom items not recognized after server restart

### ISSUE THREAD

**Issue by Bloodlex** [Ghost-chu/QuickShop-Reremake#562]
**Describe the bug**
Some plugins add items with custom name and lore. Until this time it was not a problem to sell or buy them from shop, but now it seems that they only work until the server is restarted. After restart they are not recognized. They cannot be bought, although they are in chest, and the number of items in chest is not calculated.

This example is based on Disease plugin ([https://www.spigotmc.org/resources/disease.3911/](https://www.spigotmc.org/resources/disease.3911/)) and affects disease remedies. The version of the plugin haven't changed since it worked for the last time.

Other plugins just in case they could affect this behavior: 

> Plugins (67): AcoWorth, ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuctionHouse, AuthMe, BetterBees, BottledExp, ChatItemDisplay, ColoredSigns*, CommandHelper, CommandPanels, ConsoleSpamFix, CraftBook, CustomHeads*, Disease, DragonSlayer, dynmap*, Dynmap-WorldGuard*, EasyCarts, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts*, FogusCore, GoldenEnchants, GSit, Harbor, HolographicDisplays, InteractiveBooks, JetsAntiAFKPro, Jobs, LangUtils, Lasso, LastLoginAPI, LeaderHeadsRevamped, LogBlock, LuckPerms, LWC, MoneyNote*, NBTAPI, OpenInv, OreAnnouncer, Pingas*, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, QuickShopList, RegionRaid, SAML, SkinsRestorer, Spartan, SuperVanish, Thirst, TitleManager, TurnstilePlus, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

I already tried to remove NBTAPI plugin, thought it may have impact on that but it didn't help.

**To Reproduce**
1. Create a shop with custom item with custom name and lore (for instance Disease remedies).
2. See the number of items is calculated properly and they can be bought.
3. Restart server.
4. The number of items in chest is set to 0, although there are some items and they cannot be bought (are not recognized are the item that is traded).

**Expected behavior**
As before, I should be able to buy the items I set to be sold.

**Screenshots**

Before restart (working):

![2020-09-05_05 07 06](https://user-images.githubusercontent.com/1086720/92296634-f1124400-ef36-11ea-8ec3-7fb41fe9fff9.png)
![2020-09-05_05 07 12](https://user-images.githubusercontent.com/1086720/92296635-f8395200-ef36-11ea-9a46-f1a42b33ad05.png)

After restart (not working):

![2020-09-05_05 09 06](https://user-images.githubusercontent.com/1086720/92296637-0a1af500-ef37-11ea-968d-46d917c03d66.png)

Items in chest have not been touched before restart.

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- [https://paste.enginehub.org/bH8FQl3qv](https://paste.enginehub.org/bH8FQl3qv)

**Additional context**

**Comment by sandtechnology** [comment]
It's a spigot bug: https://hub.spigotmc.org/jira/browse/SPIGOT-5964 and you can set `work-type` to 0 to use QS Matcher as a workaround.
Next version we will force using QS Matcher on 1.16 server.

**Comment by Bloodlex** [comment]
Awesome, now it works! Thanks for fast and effective response 👍
