### ISSUE TITLE
[BUG]物品预览的text不显示(Item Preview Broken) 

### ISSUE THREAD

**Issue by 2173204318** [Ghost-chu/QuickShop-Reremake#565]
**Describe the bug**
text不显示

**To Reproduce**
出售,收购是列表显示的物品预览无法正常显示,显示为text

**Expected behavior**
尝试了最新版本(4.0.4.9 Hotfix #1)和4.0.4.8,均是此情况,.
中文英文都不行..
服务端核心:Paper 1.16.2

**Screenshots**
![avatar](https://s1.ax1x.com/2020/09/06/weiGQA.png)

**Comment by sandtechnology** [comment]
请提供paste链接（/qs paste），不然我们无法帮助你。

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by 2173204318** [comment]
[paste-8b8c45063d96424b8b6086c2d4870461.txt](https://github.com/Ghost-chu/QuickShop-Reremake/files/5179089/paste-8b8c45063d96424b8b6086c2d4870461.txt)
抱歉没办法上传到ubu,502了

**Comment by Ghost-chu** [comment]
请尝试更新服务端核心构建

**Comment by sandtechnology** [comment]
请问使用的客户端是？
无法在paper上重现这个问题，猜测是客户端问题导致无法正常解析

**Comment by silent-mobious** [comment]
I'm also seeing this with Paper 1.16.2 185 and the 4.0.4.9 hotfix.  Occurs when client is vanilla and with optifine:

![image](https://user-images.githubusercontent.com/12705402/92416496-d0f7a600-f12b-11ea-9df8-591c2e7529c4.png)

Thanks!

**Comment by sandtechnology** [comment]
> 
> 
> I'm also seeing this with Paper 1.16.2 185 and the 4.0.4.9 hotfix. Occurs when client is vanilla and with optifine:
> 
> ![image](https://user-images.githubusercontent.com/12705402/92416496-d0f7a600-f12b-11ea-9df8-591c2e7529c4.png)
> 
> Thanks!
I still could not reproduce this, how about disable PlaceholderAPI support in config.yml?

**Comment by silent-mobious** [comment]
I tried setting it to false in the config, and then removing the placeholder plugin completely, but no change with either.  I'll start one by one with the other plugins to see where else it could be coming from.  Thanks!

**Comment by sandtechnology** [comment]
> 
> 
> I tried setting it to false in the config, and then removing the placeholder plugin completely, but no change with either. I'll start one by one with the other plugins to see where else it could be coming from. Thanks!

Could you provde a paste (obtained by /qs paste) to compare plugin list with this user?
I think it will faster to figure out what plugin caused this.

**Comment by silent-mobious** [comment]
It was an outdated ProtocolSupport build dated 8/27, #545 from https://build.true-games.org/job/ProtocolSupport/.  I updated to the latest #555 it's working now.  Sorry, I should done the one at a time thing first...

Thanks a lot!
