### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tauses** [Ghost-chu/QuickShop-Reremake#567]
**Describe the bug**
I get this Error in console, I don't know what it means or what it does.

**To Reproduce**
I get the error when I restart my server.

**Expected behavior**
I don't know how it affects anything in the game yet, I haven't tested it.

**Screenshots**

**Paste link:**
- https://paste.enginehub.org/n3C3NjJmU

**Additional context**

**Comment by sandtechnology** [comment]
Any screenshots?

**Comment by Tauses** [comment]
I haven't really done anything with it in game, there's only the error in console, nothing else.

**Comment by sandtechnology** [comment]
Please, provide the error in console, otherwise we can't help you.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Tauses** [comment]
My bad
https://paste.gg/p/anonymous/e3f5854188dd4c55af8c90c799247111

**Comment by sandtechnology** [comment]
> 
> 
> My bad
> https://paste.gg/p/anonymous/e3f5854188dd4c55af8c90c799247111

emmmm, you can safely ignore this, it does make any difference expect a paste create failed.
To fix this, we need to change connection provide method.

**Comment by Tauses** [comment]
Alright, thank you!

**Comment by Tauses** [comment]
I've just gotten this huge error
https://paste.gg/p/anonymous/cd77040fd3744e0c882a3243ec51a872

**Comment by sandtechnology** [comment]
> 12.09 11:35:12 [Server] INFO because it saved from higher Minecraft server version, the action will fail and you will receive a exception, PLELASE DON'T REPORT TO QUICKSHOP!
--
> 12.09 11:35:12 [Server] WARN [QuickShop] You can try force load this ItemStack by our hacked ItemStack read util(shop.force-load-downgrade-items), but beware, the data may damaged if you load on this lower Minecraft server version, Please backup your world and database before enable!

look like you create a shop on the higher minecraft version, and try to load in lower version, please read tips above and enable force-load-downgrade-items in config.yml.

**Comment by Tauses** [comment]
Thanks, it works now 👍
