### ISSUE TITLE
[BUG] Incompatible with Spartan Anti-Cheat

### ISSUE THREAD

**Issue by marvinej** [Ghost-chu/QuickShop-Reremake#568]
**Describe the bug**
When trying to setup quick shops Spartan plugin denies my permissions to create a shop. After trying enough, I get kicked for using nuker hacks.

**To Reproduce**
Install Spartan Anti Cheat and Quick Shop. 
Try to setup a shop as a non administrative user.

**Expected behavior**
Spartan and QuickShops should be compatible.

**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【https://paste.enginehub.org/wMyEKRTAp】

**Additional context**
Please work with Evan over at https://discord.me/spartan to see if he can help you sort this incompatibility.

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/149/
How about this version?

**Comment by marvinej** [comment]
seems to be working now. Thanks!
