### ISSUE TITLE
[Feature] ShopSuccessPurchaseEvent modify

### ISSUE THREAD

**Issue by Avankziar** [Ghost-chu/QuickShop-Reremake#573]
Hello,

I would like to suggest to modify the event a bit.

First I would split the event into 2 events. Once a buy and sell event.

I would also suggest that you enter the ItemStack for both events in the event itself.

I want this to be able to access it with my Economy Plugin. So I can write a better transferlog.

Thanks,
Avan

**Comment by sandtechnology** [comment]
But you can access shop type and item by the shop object...and, why we should split an event to two? You can just handle all shop purchase in an event.

**Comment by Avankziar** [comment]
I am aware that I can access the Shopobject, but this object or event does not tell me whether it was sold or bought. Or am I wrong there?

**Comment by sandtechnology** [comment]
`Shop#isSelling` should be fine

**Comment by Avankziar** [comment]
Ok, thanks. I assume Shop#getItem give the handling Item?

But what is with Shop#isSelling and Shop#isBuying both true?

**Comment by sandtechnology** [comment]
Yes, Shop#getItem is the item trading, and Shop#isSelling and Shop#isBuying never have the same value, it was used in our code.

**Comment by Avankziar** [comment]
Ok, than thanks for your answers^^

I will than implement your plugin in my Economylog system^^
Have a nice day^^
