### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by cb12438** [Ghost-chu/QuickShop-Reremake#576]
what economy plugin do i need for this to work i have Essentials plugin right now what it says "Economy system not loaded, type /qs main to get details. that's what i do and it brings up the help list

**Comment by cb12438** [comment]
i am on a 1.16.3 server as well

**Comment by sandtechnology** [comment]
Please install vault: https://dev.bukkit.org/projects/vault/

**Comment by cb12438** [comment]
I do have vault

**Comment by cb12438** [comment]
does it need to be the bukkit one? cause i have the spigot one

**Comment by sandtechnology** [comment]
No, both provide the same file.
Could you provide the paste by /qs paste?

**Comment by cb12438** [comment]
Nope i got it i needed to have the bukkit vault plugin installed not the spigot maybe a bug thier?

**Comment by cb12438** [comment]
its either a bug on vaults side on spigot or its ur guys

**Comment by Ghost-chu** [comment]
To execute command `/qs paste` to create debug report to allow us check the problem.
Also please execute `/vault-info` command to get vault infomations.
