### ISSUE TITLE
[Feature] Command to delete all Shops from Database from a specifiec World

### ISSUE THREAD

**Issue by Pyario** [Ghost-chu/QuickShop-Reremake#580]
**Describe the Feature**I 
I have already written with @Ghost-chu  as "Sandi" in SpigotMc. But I'll write it here again: One command to delete all shops from the database of one world. I think its not hard to implement.

Best Regards, 

~Pyario.

**Comment by Ghost-chu** [comment]
Added in the lastest dev build: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/193/
