### ISSUE TITLE
Everybody can open chests

### ISSUE THREAD

**Issue by guillian77** [Ghost-chu/QuickShop-Reremake#59]
I am running server in spigot 1.13.2, I just update QuickShop version from 1.3.5.8 to 1.3.7.

The main reason I do the update is the chests was displaying the bad items on the chest when server reload.

Now in 1.3.7 everybody can open the chest and take out his content.

How to fix that.

Sorry for my bad english, regards

**Comment by Ghost-chu** [comment]
This is a bug and will fix in 1.3.7.1, thanks for report!

**Comment by Ghost-chu** [comment]
fixed in 1.3.7.2

**Comment by guillian77** [comment]
Thanks for your and your work
