### ISSUE TITLE
[BUG] qs supercreate does not work with lands

### ISSUE THREAD

**Issue by ArtamaMeyer** [Ghost-chu/QuickShop-Reremake#592]
**Describe the bug**
When using (/qs supercreate) I can not create a shop when the config is set to only allow shops in lands and not wilderness
I get this message: Intergration Lands denied the shop-creation

**To Reproduce**
Set it up so you can only create shops inside land
use: /qs supercreate

**Expected behavior**
A shop should be created

**Screenshots**

**Paste link:**
https://paste.enginehub.org/ob5WOZVBi

**Additional context**

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/197/
This version will fix it.
