### ISSUE TITLE
[BUG] Crashing server and disconnecting players

### ISSUE THREAD

**Issue by EkonC** [Ghost-chu/QuickShop-Reremake#594]
**Describe the bug**
When I issued any /qs .. command, it kicked me with an error and it crashed the server

**To Reproduce**
It happened only once and I don't have any logs or screenshots.
Just use /qs and see what happens

Paper-189 (1.16.2)

**Comment by sandtechnology** [comment]
Please give the error screenshots or the part of client and server log about it, otherwise we can't resolve it.

**Comment by EkonC** [comment]
> Please give the error screenshots or the part of client and server log about it, otherwise we can't resolve it

[Sat, 10. Oct 2020 14:23:59 CEST INFO] Leluer issued server command: /qs
[Sat, 10. Oct 2020 14:23:59 CEST ERROR] java.lang.StackOverflowError
[Sat, 10. Oct 2020 14:23:59 CEST WARN] java.lang.StackOverflowError
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at java.lang.reflect.Field.get(Field.java:393)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.writeField(ReflectiveTypeAdapterFactory.java:136)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:241)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)

>

**Comment by EkonC** [comment]
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[Sat, 10. Oct 2020 14:23:59 CEST WARN] at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)

And then it crashed

**Comment by sandtechnology** [comment]
/qs paste?
Look like is the gson fault

**Comment by EkonC** [comment]
/qs paste doesn't do anything for me. Just this: https://paste.enginehub.org/undefined

**Comment by sandtechnology** [comment]
The latest version should solve paste issue, what about now?
It's still having this issue?

**Comment by EkonC** [comment]
Thank you for the support. This hasn't happened since when I reported it so I guess it is okay now.
