### ISSUE TITLE
[BUG] Shops not being loaded on start

### ISSUE THREAD

**Issue by dig** [Ghost-chu/QuickShop-Reremake#596]
**Describe the bug**
Shops not being loaded after reboot.
Error from your plugin on startup: https://pastebin.com/ES2nef9U

**To Reproduce**
- Create a shop
- Reboot server
- Shop no longer works

**Expected behavior**
Shops should continue to work after reboot.

**Screenshots**
N/A

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- https://paste.ubuntu.com/p/bjpbw4fr5p/

**Additional context**
N/A

**Comment by sandtechnology** [comment]
what about this version?
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/201/

**Comment by dig** [comment]
Seems to be working fine after using that version.
