### ISSUE TITLE
[BUG] Players cannot create shops with keys from CrateReloaded using /qs create

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Ghost-chu/QuickShop-Reremake#597]
**Describe the bug**
When players try to sell a Crate Key with /qs create, they get this error.

![image](https://user-images.githubusercontent.com/29821149/96161437-e6a37c80-0edc-11eb-9787-a8bcaa32280a.png)

And using /lp verbose, I cannot find any associated permissions that would allow them to do it.

**To Reproduce**
1. Download CrateReloaded: [FREE](https://www.spigotmc.org/resources/free-crate-reloaded-mystery-crate-1-8-1-16-x.861/) [PRO](https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-16-x.3663/updates)
2. Install CrateReloaded and QuickShop on your server
3. Give yourself one of the keys from CrateReloaded by doing /crate give to (playerName) FoodKey 1
4. Hold the FoodKey and try to create a shop with it by doing /qs create (price)

**Expected behavior**
Create a chest shop that sells the keys.

**Screenshots**

![image](https://user-images.githubusercontent.com/29821149/96161437-e6a37c80-0edc-11eb-9787-a8bcaa32280a.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- [paste-89737d120045448b8c69c01e316fde6c.txt](https://github.com/Ghost-chu/QuickShop-Reremake/files/5386583/paste-89737d120045448b8c69c01e316fde6c.txt)

**Additional context**
N/A

**Comment by sandtechnology** [comment]
Please disable `protection-checking` option and use integration options below to check build permission.
