### ISSUE TITLE
More than one owner for a shop

### ISSUE THREAD

**Issue by guillian77** [Ghost-chu/QuickShop-Reremake#60]
My players ask him how to put more than one owner on the same chest shop. Because they play as a couple. (same house, same shop ...).

I try to change pay-unlimited-shop-owners: false to 
I try:
/qs setowner Player1 Player2
/qs setowner Player1, Player2

Maybe there is not the feature in the plugin.

If there is not the feature to do it, can you implement it ?

**Comment by Ghost-chu** [comment]
QuickShop is design for single owner for one shop.  So yes, no this feature in the pluign.

But is possible to be a feature add to plugin, but this may need LONG time, so anyway, i will keep this issue open, but i can't promise a ETA for this issue.

Thanks for advice :)

**Comment by guillian77** [comment]
Maybe you can just display the fist owner can be display on the sign.

**Comment by Ghost-chu** [comment]
> Maybe you can just display the fist owner can be display on the sign.
> 
> Take your time your work is great !

I mean, database and shop core

**Comment by Ghost-chu** [comment]
So if have multiowner, who should get rewards from shop, and tax and other things.

So i think might can add `Moderators`, monderators have permissions to change price, open chest, and other same with owner permissions, but moderators will got nothing in trades and can't break/delete shop.

**Comment by Ghost-chu** [comment]
Done! It will avaliable in next version
