### ISSUE TITLE
[Feature] Display amount and item name as hologram above item.

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#600]
**Describe the Feature**
It would be nice to have QuickShop display the amount of items and the name of the item itself (Custom name if set or just item name) above the displayed item.
This would help a lot in cases where the name of the item is too long to display on the sign alone.

**Screenshots**

**Additional context**

**Comment by Ghost-chu** [comment]
Maybe this?
```yaml
  #Add display name to the spawned DisplayItem entity?
  display-item-use-name: false
```
But it can hurt client performance if there have too many shops in view distance.

**Comment by Andre601** [comment]
Exactly. Thanks
