### ISSUE TITLE
[Feature Request] AdminShop with system account

### ISSUE THREAD

**Issue by SuneR-what** [Ghost-chu/QuickShop-Reremake#601]
Hey,
I have set up some admin shops, where players can sell some stuff. But I cant sell my self, even if I set myself to deop. It's like it thinks the shop is mine, and not an admin shop.
Is it a bug, or have I missed something in the config file?

Thanks in advance.
Sune

**Comment by Ghost-chu** [comment]
Even shop shown AdminShop but the shop owner still belong creator.

**Comment by SuneR-what** [comment]
So I can not set up a server, with this plugin, and enjoy the game my self? There is no way to set op admin shops, so it isnt owned by anyone?

**Comment by Ghost-chu** [comment]
Well, usually you can transfer to a player that joined the server before (even cracked player).

We will offer an option to allow set AdminShop to a REAL AdminShop.

**Comment by sandtechnology** [comment]
> 
> 
> Well, usually you can transfer to a player that joined the server before (even cracked player).
> 
> We will offer an option to allow set AdminShop to a REAL AdminShop.

The implementation is quite simple: just extend UUID class and identify by instance-of operator

**Comment by Ghost-chu** [comment]
> > Well, usually you can transfer to a player that joined the server before (even cracked player).
> > We will offer an option to allow set AdminShop to a REAL AdminShop.
> 
> The implementation is quite simple: just extend UUID class and identify by instance-of operator

Full zero uuid maybe more easily

**Comment by SuneR-what** [comment]
> > > Well, usually you can transfer to a player that joined the server before (even cracked player).
> > > We will offer an option to allow set AdminShop to a REAL AdminShop.
> > 
> > 
> > The implementation is quite simple: just extend UUID class and identify by instance-of operator
> 
> Full zero uuid maybe more easily

Is that something I can do? Im not fully understanding what you mean with the "just extend UUID class and identify by instance-of operator" og the Full zero uuid?

But do you have a eta for the 4.0.5.0?

**Comment by Ghost-chu** [comment]
> > > > Well, usually you can transfer to a player that joined the server before (even cracked player).
> > > > We will offer an option to allow set AdminShop to a REAL AdminShop.
> > > 
> > > 
> > > The implementation is quite simple: just extend UUID class and identify by instance-of operator
> > 
> > 
> > Full zero uuid maybe more easily
> 
> Is that something I can do? Im not fully understanding what you mean with the "just extend UUID class and identify by instance-of operator" og the Full zero uuid?
> 
> But do you have a eta for the 4.0.5.0?

We didn't have ETA for releasing, but this issue priority already set to Major.
So snapshot shouldn't cost too long time.

We have three priority:
①Major, usually it should finish before next release.
②Minor, usually it should finish before next big update.
③Low, nobody knows it will cost how long time, maybe some years.
