### ISSUE TITLE
[BUG] Server kicks player when they try to buy something

### ISSUE THREAD

**Issue by EkonC** [Ghost-chu/QuickShop-Reremake#635]
**Describe the bug**
Server kicks player with this message when they try to buy something

**To Reproduce**
1. Go to someones shop
2. Left click on the shop sign (to buy)
3. Server kicks you

**Expected behavior**
Just a normal purchase at a store

**Screenshots**
![Snímka obrazovky (44)](https://user-images.githubusercontent.com/62595403/98168251-9a9b9480-1eea-11eb-8a39-3bd698de2ae9.png)

**Paste link:**
It didn't quite work 
- 【https://paste.enginehub.org/undefined】

**Comment by EkonC** [comment]
Okay, server restart solved it (for now) but that shouldn't happen at all

**Comment by sandtechnology** [comment]
Duplicate with #622
