### ISSUE TITLE
[Feature] Spartan compatibility integration

### ISSUE THREAD

**Issue by Baterka** [Ghost-chu/QuickShop-Reremake#653]
**Describe the Feature**
When Spartan is installed and enabled everything works fine, but when you disable it (by for example PlugMan) the QuickShop is unresponsive due to newly added compatibility integration.

I made small commit where we checking for plugin enable/disable events and based on this we toggle compatibility integration.

**Comment by sandtechnology** [comment]
Thanks for your PR and Feature Request, I will done this recently, but for all plugin which integrated.
