### ISSUE TITLE
Wrong description in ShopUpdateSignEvent

### ISSUE THREAD

**Issue by Hugo5000** [Ghost-chu/QuickShop-Reremake#655]
/**
     * Will call when shop price was changed.
     *
     * @param shop Target shop
     * @param sign Updated sign
     */
    public ShopSignUpdatedEvent(@NotNull Shop shop, @NotNull Sign sign) {
        this.shop = shop;
        this.sign = sign;
    }

and also a quick question, will this be called when the item changes aswell, because there is no event for that?

**Comment by sandtechnology** [comment]
ShopSignUpdatedEvent is even not being called by our plugin......However is existed for a long time.
I will add missing calling and create ShopItemChangedEvent
