### ISSUE TITLE
Chest removed issue

### ISSUE THREAD

**Issue by Dgretty** [Ghost-chu/QuickShop-Reremake#71]
When i remove a chest, via break or the removal option. And try to place a new chest in its place. It is still showing this as the old shop, without a sign. Making it so players cannot change what they are selling, or being able to remove a shop permanently.

**Comment by Ghost-chu** [comment]
plugin version pls

**Comment by Dgretty** [comment]
1.4.2.3

**Comment by Ghost-chu** [comment]
Please comment your server ip, result of /qs paste, and upload your shops.db file.

If you have whitelist, make sure you add player Ghost_chu in whitelist.

**Comment by Ghost-chu** [comment]
fixed
