### ISSUE TITLE
[Feature] Event for when shop type changes

### ISSUE THREAD

**Issue by Hugo5000** [Ghost-chu/QuickShop-Reremake#716]
**Describe the Feature**
An event for when the type of a shop changes from selling to buying or the other way around

**Additional context**
example name ShopTypeChangeEvent

**Comment by Ghost-chu** [comment]
Maybe you can try ShopUpdateEvent to check the type.



---Original---

**Comment by Hugo5000** [comment]
but I wont know if the type changed?, will I? There is no previous type. And also the same with when the Item changes and also if the store gets restocked. Also wont this also trigger when anything unrelated about the shop changes?
