### ISSUE TITLE
QuickShop log's to MySQL

### ISSUE THREAD

**Issue by rudipratm** [Ghost-chu/QuickShop-Reremake#718]
**Describe the Feature**
The QuickShop log go to the database with settings on it's config's file. Since I'm using integrated database to my web, I wish QS can make this. So I can manage & see the log from my web panel with live-change on it.

**Comment by sandtechnology** [comment]
Checking log through database seems is more complex way for user, so is a low priority feature.
And just a quick question, what's the format of log if it was putted in to database?

**Comment by rudipratm** [comment]
What's in my head is:
Every trading activity carried out by players in the game will be recorded automatically per-row and saved into the qs_log table.

**Comment by Unyxos** [comment]
Hey there, found this issue after Ghost_chu shared the link on Discord.
Another option might be to add unique id to shops created (as they're saved in database), and have the qs_history this way :

| id | shop_id | action | player_uuid | quantity | total_price | timestamp |
|-|-|-|-|-|-|-|
| unique id for each transaction | shop's id | 1 = buy event 2 = sell event | buyer/seller uuid | integer | float (saved here as shop owner could change price later, and would change the  history if computing is based  on qs_shops price) | timestamp of event |

this way, one don't need to parse a sentence like "<PLAYER> bought <ITEM> for <AMOUNT> on <TIMESTAMP> or things like that that would be saved in db
this would also make it easy to build shop history interface on websites etc... 
Just my 2 cents!

**Comment by Ghost-chu** [comment]
Shop have no unique id.
We use coord in world to read shops. The UUID is only for runtime, it will changes when shop restarting.



---Original---

**Comment by Unyxos** [comment]
Hmm ships not having unique IDs could theorically be an issue at some point in case one wants to build an history for all shops/orders as there wouldn't be a good way to bind transactions to a shop :(

**Comment by redXpanda** [comment]
log module init fail in OpenJDK 11. 
[15:55:35] [Server thread/INFO]: [QuickShop] Chat processor selected: BUNGEECHAT
[15:55:35] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[15:55:35] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[15:55:35] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[15:55:35] [Server thread/INFO]: [QuickShop] Loading plugin translations files...

Same time I use JDK8, it's all OK.

**Comment by sandtechnology** [comment]
> 
> 
> log module init fail in OpenJDK 11.
> [15:55:35] [Server thread/INFO]: [QuickShop] Chat processor selected: BUNGEECHAT
> [15:55:35] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> [15:55:35] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
> [15:55:35] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [15:55:35] [Server thread/INFO]: [QuickShop] Loading plugin translations files...
> 
> Same time I use JDK8, it's all OK.

We are not using log4j, so is ok for ignoring this, also it should be a new issue.
