### ISSUE TITLE
Spigot and QS crashing server?

### ISSUE THREAD

**Issue by cheesepufftyler** [Ghost-chu/QuickShop-Reremake#72]
https://pastebin.com/2rC6yKAJ
When some players rejoin the server, the server freezes and crashes, then displays this error. now i cant even join the server, but other players can.

**Comment by Ghost-chu** [comment]
Known issues, this problem only happend on Spigot 1.14 dev build.
I'm already fight with this issue many days, but i think this is a Spigot bug, so i need wait md_5 fix that.

**Comment by Ghost-chu** [comment]
Try delay load shop in latest build, try it, if they fixed this issue, you can close this issue.

**Comment by Ghost-chu** [comment]
no more crashing reports, issue close
