### ISSUE TITLE
[Feature] Event for when a Shop get refilled/emptied

### ISSUE THREAD

**Issue by Hugo5000** [Ghost-chu/QuickShop-Reremake#721]
**Describe the Feature**
An event that gets fired when the stock of a shop changes

**Additional context**
This would be useful because the ShopUpdateEvent doesnt fire when the stock changes.

**Comment by sandtechnology** [comment]
Stock changes could be in multiple ways, I recommended listen to ShopSignUpdateEvent and compare whether the stock has changed

**Comment by Hugo5000** [comment]
oh alright, I forgot that the sign has the current Stock on it 👍

**Comment by Ghost-chu** [comment]
···
    /**
     * Returns the number of free spots in the chest for the particular item.
     *
     * @return remaining space
     */
    @Override
    public int getRemainingSpace() {
        if (this.unlimited) {
            return -1;
        }
        return Util.countSpace(this.getInventory(), this.getItem());
    }

    /**
     * Returns the number of items this shop has in stock.
     *
     * @return The number of items available for purchase.
     */
    @Override
    public int getRemainingStock() {
        if (this.unlimited) {
            return -1;
        }
        return Util.countItems(this.getInventory(), this.getItem());
    }
···
