### ISSUE TITLE
[Feature]  An Event for when a shop is completely removed

### ISSUE THREAD

**Issue by Hugo5000** [Ghost-chu/QuickShop-Reremake#722]
**Describe the Feature**
An ShopSuccessDeleteEvent that gets fired after the shop has been completely removed from the Plugin, i.e. after the last ShopUpdateEvent for the shop has fired.

This would be useful, for when an extension saves a list of all shops, so it doesnt get added again if the plugin listens to the ShopUpdateEvent.

**Comment by sandtechnology** [comment]
ShopDeleteEvent would be ok
