### ISSUE TITLE
Crash report :p Shop Container

### ISSUE THREAD

**Issue by WittleRain** [Ghost-chu/QuickShop-Reremake#73]
1.14 spigot https://hastebin.com/alivehewat.md

**Comment by HyperlyBola** [comment]
Okay here's how it goes, I somehow got this plugin working just fine on Paper Spigot, but on spigot 1.14 dev versions it breaks horribly, and crashes after a while. Lookup Yives PaperMC and you should find paper spigot 1.14 there.

**Comment by Ghost-chu** [comment]
I can't fix this bug cause this is a server bug. Nolonger accept 1.14 errors report until Spigot fixed that.

**Comment by WittleRain** [comment]
got it

**Comment by Ghost-chu** [comment]
Try delay load shop in latest build, try it, if they fixed this issue, you can close this issue.

**Comment by Ghost-chu** [comment]
no more crashing reports, issue close
