### ISSUE TITLE
server quickshop break when i restart my server

### ISSUE THREAD

**Issue by MIGHTYMIKEY8** [Ghost-chu/QuickShop-Reremake#730]
when i restart my server and when i try to buy things from the chestshops it doesnt work and the item thats suppose to apear above the chestshop doesnt apear either this is my paste: https://paste.enginehub.org/Iq-PcrgjZ

**Comment by Ghost-chu** [comment]
```
[DEBUG] WARNING: DataVersion not matched with ItemStack: item:
  ==: org.bukkit.inventory.ItemStack
  v: 2580
  type: FLINT_AND_STEEL
```
downgrading server is unsupported.
any shop created before downgrading will cannot be loaded.

if you still want forcing load the shops that dataversion missing matches, try use `force-load-downgrade-items` option
