### ISSUE TITLE
[BUG] QS not showing chat messages.

### ISSUE THREAD

**Issue by Trixxxie** [Ghost-chu/QuickShop-Reremake#744]
**Describe the bug**
So after a while QuickShop on my server just stops showing any messages on chat when you click the shop. It does play the sound and if you enter amount in chat it will purchase/sell that amount of the item, but no messages are being sent to player's chat. I tried to reload the plugin with /qs reload but it did not help. I then rebooted the server and the issue got fixed, but after a while it again stopped sending messages.

**To Reproduce**
1. Install plugin like you would usually
2. Play on server normally and occasionally check the shop, shop messages for me at least will disappear suddently..

**Expected behavior**
Normal shop messages to show in chat or at least error on console but could not find one..

**Screenshots**
https://imgur.com/EvQQQ9Q

**Paste link:**
https://paste.enginehub.org/vy9Eda5yg

**Additional context**
-

**Comment by Ghost-chu** [comment]
could you try turn off PlaceHolderAPI 3rd supports?
set `plugins.PlaceHolderAPI` to `false` and try again.

**Comment by sandtechnology** [comment]
Considering adventure bug, Investigating

**Comment by sandtechnology** [comment]
How about this version?
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/405/

**Comment by Trixxxie** [comment]
Uhm, I did not try any of those fixes yet but it seems to be working now, and has been working for few days now... I get back to this issue if this comes up once again, but so far all good! Keep up the good work lads!
