### ISSUE TITLE
[BUG] Item Preview error (/qs silentpreview)

### ISSUE THREAD

**Issue by SrBedrock** [Ghost-chu/QuickShop-Reremake#746]
**Describe the bug**

![image](https://user-images.githubusercontent.com/51332006/101994245-bb9c9580-3c9f-11eb-9b41-c983fe7b6b24.png)

Console error:
https://gist.github.com/SrBedrock/2393ddc7aad2ac2a12fde1dce11ea871

**To Reproduce**
1. Left click on the store selling enchanted books
2. Click on Preview Items

**Expected behavior**
Preview item and no erros on console.

**Paste link:**
- https://gist.github.com/SrBedrock/cf3fd39c5046f516c0f2ddc7c5812219

**Comment by Ghost-chu** [comment]
already fixed in e095f92

**Comment by sandtechnology** [comment]
Please try out this build: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/410
