### ISSUE TITLE
[Feature] Improve resource page

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#775]
**Describe the Feature**
I would like to help to improve the Resource page in both grammar and overall look.
I went ahead and quickly designed a new version that may be a bit more clean and easy to look at.

**Screenshots**
Yes I know it's a lot of images. I just wanted to show the full preview of how it may look like.

![image](https://user-images.githubusercontent.com/11576465/103221201-5a70f500-4922-11eb-8b3a-5a513fa4f524.png)
![image](https://user-images.githubusercontent.com/11576465/103221240-6e1c5b80-4922-11eb-97b0-ed048db433ff.png)
![image](https://user-images.githubusercontent.com/11576465/103221250-76749680-4922-11eb-9384-765df8b58fba.png)
![image](https://user-images.githubusercontent.com/11576465/103221307-9ad07300-4922-11eb-8b3e-5e9a7361cddc.png)
![image](https://user-images.githubusercontent.com/11576465/103221341-ae7bd980-4922-11eb-815e-a24b4539db40.png)
![image](https://user-images.githubusercontent.com/11576465/103221369-bcc9f580-4922-11eb-8c55-c84d669f2275.png)
![image](https://user-images.githubusercontent.com/11576465/103221376-c3586d00-4922-11eb-8e8f-5f66e0d611ee.png)
![image](https://user-images.githubusercontent.com/11576465/103221413-d9fec400-4922-11eb-94ad-1bba063cc3d5.png)
![image](https://user-images.githubusercontent.com/11576465/103221427-e256ff00-4922-11eb-8c3f-c1fc41685182.png)
![image](https://user-images.githubusercontent.com/11576465/103221438-e7b44980-4922-11eb-8fe3-8caba96453fe.png)

**Additional context**
You can find a gist with the raw BB Code for the resource page here:
https://gist.github.com/Andre601/d0c182d4b2a09b6f992fb6969d79ef97

Please read the notes on the gist as they contain important things like about the images.

**Comment by Ghost-chu** [comment]
Really helpful ^ ^
