### ISSUE TITLE
[Feature] artificially increased/infinite storage space for potions and other nonstackables

### ISSUE THREAD

**Issue by tnttony1998** [Ghost-chu/QuickShop-Reremake#778]
Hello
Sorry in advance. I have no coding experience at all, and this is my first post on github so no clue how to approach this.

In short, I had a potion shop and a music disk shop on a server who used to have a shop plugin where storage wasn't a factor. I'm worried about only having an inventory of 27 items when this plugin gets implemented. Is there a way to stack nonstackables inside the chest? maybe let hoppers feed into the chest? Any other way to circumvent this problem of storage space? 

Idk whether this would come down to UI, a setting that lets hoppers interact with the shop, i have no clue.
I hope this was of use.

**Comment by sandtechnology** [comment]
Since nonstackables items is the vanilla limitation, the only way we can do is handle ALL item input and stack it by a lazy way, but it can be do by other plugin, for example https://www.spigotmc.org/resources/zitemstacker-stack-yours-items.85531/, so is low priority.

**Comment by Ghost-chu** [comment]
QuickShop can't do that, but you can use other plugin and set max stacksize in quickshop configuration to stacking items
