### ISSUE TITLE
Error while creating a shop

### ISSUE THREAD

**Issue by quiquelhappy** [Ghost-chu/QuickShop-Reremake#78]
Video and error:
[https://imgur.com/a/ClZsmd2](https://imgur.com/a/ClZsmd2)

Config:
[https://hastebin.com/zefadomeve.coffeescript](https://hastebin.com/zefadomeve.coffeescript)

Version: 
1.4.3.8

More info:
I'm using the last version on my 1.13 server, we have ViaVersion for forwarding compatibility with 1.14. The material id is set to WALL_SIGN. Floating items are disabled (display-items).

**Comment by Ghost-chu** [comment]
update version
