### ISSUE TITLE
[BUG] Shulker Box Shops Can Be Used To Store Shulker Boxes Within Shulker Boxes

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Ghost-chu/QuickShop-Reremake#788]
**Describe the bug**
You can create a shulker box that is a buy shop and sell it shulker boxes, then destroy the shop and you will have shulker boxes within shulker boxes, which is not possible in vanilla.

**To Reproduce**
1. Create a buy shop that is a shulker box
2. Sell it a shulker box
3. Break the shop

**Expected behavior**
I don't know what would be the ideal solution here. Perhaps a config option that disallows selling shulker boxes to shulker box shops.

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- 【I wasn't been able to get /qs paste to work for some reason, but I don't think this issue is exclusive to my setup】

**Comment by sandtechnology** [comment]
Snapshot: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/546/
