### ISSUE TITLE
changed sign is not updated.

### ISSUE THREAD

**Issue by kotarobo** [Ghost-chu/QuickShop-Reremake#79]
I rewritten the form of the signboard in the config and reloaded.
The newly created shop will be replaced by a signboard, but the already created shop will remain an old signboard.

**Comment by Ghost-chu** [comment]
break the old sign and put new on it, and click it

**Comment by kotarobo** [comment]
Oh, I thought it was a bug because the original one was updated by reloading. understood.

**Comment by kotarobo** [comment]
I could not break it because the shop function was working.
Do I have to erase it and install it again?

**Comment by Ghost-chu** [comment]
If you have worldedit, directly replace it with air and re-put the sign
