### ISSUE TITLE
[BUG] /qs paste is no longer working

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#790]
**Describe the bug**
The `qs paste` command doesn't give any responses, while `qs` itself does and also lists the paste command as a valid option

**To Reproduce**
1. Run `/qs paste` (in-game) or `qs paste` (console)

**Expected behavior**
The command should provide a generated Paste URL or at the very least report issues with doing so.

**Screenshots**

**Paste link:**
Can't provide because it doesn't work lul.

**Additional context**
Using QuickShop 4.0.6.3 (Latest SpigotMC release) on a PaperMC 1.16.5 Server (Build 427).

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/553/ should fix it, thanks for reporting!
