### ISSUE TITLE
[BUG] no one, not even my admins can left click on the signs to buy

### ISSUE THREAD

**Issue by NikNikYT** [Ghost-chu/QuickShop-Reremake#795]
**Describe the bug**
i've set an admin shop up and i can left click no problem but my admin nor anyone else can

**To Reproduce**
1. Make an admin shop
2. left click with an alt account

**Expected behavior**
The shop should work and people can buy stuff

**Screenshots**
Little hard since nothing comes up on their end

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
- Nothing happends in chat and no paste file is created

**Additional context**

**Comment by sandtechnology** [comment]
Please make sure you have the right permission setup, it was on our plugin page: https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-say-hello-with-rgb.62575/

**Comment by NikNikYT** [comment]
the problem is even my co owner who has the exact same permissions as me cant see it either

**Comment by NikNikYT** [comment]
but i've given them use and preview

**Comment by sandtechnology** [comment]
What permission plugin you are using?
Also could you provide the permission setup?

**Comment by NikNikYT** [comment]
im using luckperms

and setup i guess you mean what permissions people have right?

**Comment by sandtechnology** [comment]
Yes

**Comment by NikNikYT** [comment]
one sec and i'll compile a list for you

**Comment by NikNikYT** [comment]
here is the luckperms editor link: https://luckperms.net/editor/2rrLamrCJi

**Comment by NikNikYT** [comment]
hope its good enough

**Comment by sandtechnology** [comment]
look like head-admin and admin doesn't have any quickshop permission, how about give the permissions?

**Comment by NikNikYT** [comment]
well i don't know if that will fix it because people with default group still can't access it but i can try and see if it helps

**Comment by NikNikYT** [comment]
i've tried and it still doesn't work

**Comment by sandtechnology** [comment]
I could not reproduce it, look like is the permission calculate issue, how about re-join the server or update luckperms?

**Comment by NikNikYT** [comment]
rejoin doesent work, but ill try and update luckperms

**Comment by NikNikYT** [comment]
it finally worked, thanks for your help :D

**Comment by sandtechnology** [comment]
It's OK, if you have any questions/problems feel free to create a new issue :D
