### ISSUE TITLE
[BUG] Items above shop is beeing sucked by Hoppers plugins

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Ghost-chu/QuickShop-Reremake#796]
**Describe the bug**
Items above shop is beeing sucked by Hoppers plugins

Could you add to DisplayItem spawn huih pickupdelay? It'll avoid situations, when its beeing sucked :/

**Comment by sandtechnology** [comment]
Please install protocol-lib and use the virtual item to avoid such issue
