### ISSUE TITLE
Another person can take out the item

### ISSUE THREAD

**Issue by kotarobo** [Ghost-chu/QuickShop-Reremake#80]
Others can line up the chests of the shop.
The side-by-side chests have access to the chests so you can retrieve items.

**Comment by Ghost-chu** [comment]
Knowned bug, this bug might from legacy version.
But i'm not at home these days, can't publish update.
Please disable double-chest first.

**Comment by kotarobo** [comment]
I did not know how to prevent the double chest, so I would like to disable the protection. Tell the player to protect with LWC.
Thank you for reply!
