### ISSUE TITLE
[Feature] Allow players to selectively toggle holograms for floating shop items.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#805]
**Describe the Feature**
Would it be possible to allow players to individually toggle the display name hologram on floating items above their shop? You may not want to have holograms on by default to keep visual clutter to a minimum but you might have a special named item you want to sell or a specific enchanted book you want to advertise by its name instead of only a generic floating item.

**Alternatively**, could you add an option to display the nametag / hologram only when you hover over the shop? This is how the ShopChest plugin currently displays holograms to prevent visual clutter.

**Comment by icarapovic** [comment]
A static hologram would be nice since some servers have dedicated shop areas, and with a lot of dynamic holograms floating and rotating the FPS drops are quite noticable.

**Comment by sandtechnology** [comment]
We have already investigated the FPS drop problem, the conclusion is the chests and signs cause it:
https://bugs.mojang.com/browse/MC-5417
https://bugs.mojang.com/browse/MC-5169

https://github.com/Ghost-chu/QuickShop-Reremake/issues/500#issuecomment-688425021
> And ends with a mojang bug, I have trying with no display item and no text on sign, still low tps, then I find this bug: https://bugs.mojang.com/browse/MC-5169
So....there are no way to fix this except not use signs or use a mod to fix it.
