### ISSUE TITLE
[Feature] Store shop locations so you can locate all shops that sell a specific item more easily.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#808]
**Describe the Feature**
Would it be possible to store shop locations in the database on creation / update so you can use the command to search for all existing shops that sell a specific item and list prices + stock? Primarily a replacement for ``/shop find`` instead of only checking in a 3 chunk radius.

**Comment by Ghost-chu** [comment]
We have API to do that:
ShopManager#getAllShops
ShopManager#getLoadedShop
etc.

/qs search command only scan loaded shops by default. But you can config it to scan all shops(include not-loaded).

**Comment by mibby** [comment]
Is there no native implementation for it or an addon already existing? Only API support? The finding config section doesn't seem to have options for checking all shops globally.
