### ISSUE TITLE
[Feature] Option to both buy & sell on a single shop location

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#809]
**Describe the Feature**
Would it be possible to allow both buying & selling of an item for a single shop?

**Additional context**
Migrating from the plugin ShopChest, this is probably one of the biggest disparities since it means players now have to double up on the amount of shops they have for both buying & selling for each item.

**Comment by Ghost-chu** [comment]
https://github.com/Ghost-chu/QuickShop-Reremake/issues/265

**Comment by Ghost-chu** [comment]
pretty hard cause qs internal using per block per shop

**Comment by mibby** [comment]
Ah sorry, didn't find that ticket. 

Bit sad to hear it's hard but hopefully one day possible. :(
