### ISSUE TITLE
[BUG] Per bulk stack changing does not work.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#810]
QuickShop-Remake-SNAPSHOT dev 564

**Describe the bug**
Per bulk amount change button does not work.

**To Reproduce**
1. Right click a shop sign.
2. Click on the ``Per bulk amount: # [Change]`` button.
3. It auto-fills the command ``/qs size ``
4. Try to add a number and hit enter.
5. Nothing happens. Help menu outputs. 

**Expected behavior**
Being able to change stack size.

**Paste link:**
- https://pastebin.com/raw/A550mbcZ

Edit: The permission node ``quickshop.create.changeamount`` is not on the wiki permissions page, only in the plugin.yml. So perhaps functionality was planned to be removed but it wasn't removed entirely? Same with the ``quickshop.create.changeitem`` permission existing but no command / functionality?

``quickshop.create.stacks`` is also not on the wiki.

**Comment by Ghost-chu** [comment]
wiki is outdated long time cause i had no time to update lol.
check spigotmc overview and that is up-to-date.

**Comment by Ghost-chu** [comment]
and this is answer about your question: https://github.com/Ghost-chu/QuickShop-Reremake/issues/453
will optimize it soon, sorry for confused

**Comment by mibby** [comment]
``allow-stacks`` is already set to true, but the command ``/qs size`` doesn't work. Same with ``display-allow-stacks`` also being set true. I wouldn't have opened the ticket otherwise. :(

I see ``/qs item`` does work fine, just not part of the sign shop menu.

**Comment by Ghost-chu** [comment]
could you type /qs size <amount> command again and create another paste to generate some logs so I can debug it?

**Comment by mibby** [comment]
Sure. I think I found the problem though. 
https://pastebin.com/raw/hzzzRz8V

The function must not be getting initialized during server start-up. When I force a ``/qs reload``, the command works. When I don't reload QS and just let it start up normally during a server start, the command doesn't work.

**Comment by mibby** [comment]
Is there anything else you'd like me to do? Having to reload qs every server restart so the command works is a bit wild.

**Comment by Ghost-chu** [comment]
Could you try this build and see if it works.
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/568/

**Comment by mibby** [comment]
Seems to be working now as of dev 648, thanks! No longer need to reload qs.
