### ISSUE TITLE
[BUG] Ender chest shop isn't using a virtual inventory.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#811]
QuickShop-Remake-SNAPSHOT dev 564
OpenInv 4.1.5

**Describe the bug**
A shop ender chest doesn't actually seem to be a fake chest.

**To Reproduce**
1. Place ender chest.
2. Setup a shop on it.
3. Right click the ender chest to try and stock the shop.
4. It opens your actual ender chest, not the fake virtual shop one.

**Expected behavior**
Fake ender chest storage for the shop.

**Paste link:**
- https://pastebin.com/raw/0HEt6cuS

**Comment by Ghost-chu** [comment]
Maybe I should call it "Share Inventory Shop" will better.
EChest shop feature is "sharing inventory between shops"
It makes player selling in nether and auto-fill overworld shops stock possible.
So nothing wrong here.



---Original---

**Comment by mibby** [comment]
I'm not sure I follow. How are you suppose to stock it when interacting with the ender_chest shop opens your vanilla ender chest instead of the shop inventory?

**Comment by Ghost-chu** [comment]
Containers use their self Inventory, So EChest use player's echest inventory.
And they're sharing inventory, that is why I design EChest shop feature.



---Original---

**Comment by mibby** [comment]
Oh, I think I understand. So an ender chest shop will always read from the player's echest inventory and use that as a type of global storage. In other words, you could have 5 ender chests selling the same item scattered throughout the world or multiple shops selling different items but all from a shared container.
