### ISSUE TITLE
[PERFORMANCE] ProtectionListenerBase.getShopRedstone() is bad on performance

### ISSUE THREAD

**Issue by dig** [Ghost-chu/QuickShop-Reremake#823]
**Describe the issue**
ProtectionListenerBase.getShopRedstone() used in various places such as BlockListener#onInventoryMove() and ShopProtectionListener#onInventoryMove() is causing bad performance, using up to 10% of each tick on some sparks! This is extremely poor performance. I can see that you have tried to cache the shop result, it seems the cache is not working well.

**To Reproduce**
N/A

**Expected behavior**
Good performance.

**Screenshots**
N/A

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
-  /qs paste does not output anything to file or console.

**Spark result link: (Require)**
- https://spark.lucko.me/#VXEICulqdf

**Additional context**
N/A

**Comment by sandtechnology** [comment]
If you are using timings to track this issue, you will see there are LOTS OF EVENTS, we can not optimize it, also the spark not monitor each tick, but monitor it by each interval.

**Comment by dig** [comment]
I've completely disabled hopper protection and hopper move item event for the time being.

**Comment by Ghost-chu** [comment]
It looks not a problem that we can solve on the plugin side.
Bukkit do really much stupid thing on just get a block material like legacy id and process/convert and performance will get worse.

We are looking for a faster way to scan/get block data.

**Comment by Ghost-chu** [comment]
Please test with https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/656/
I have replaced `Google Guava Cache` with `Caffeine`, it much faster.
Also, I have added some useful stats about caching pool in the Paste, please try it and feedback with the new Paste and Spark report.

**Comment by dig** [comment]
> Please test with https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/656/artifact/target/QuickShop.jar
> I have replaced `Google Guava Cache` with `Caffeine`, it much faster.
> Also, I have added some useful stats about caching pool in the Paste, please try it and feedback with the new Paste and Spark report.

Build doesn't even work, it doesn't let players buy. Says they don't have enough money when they do.

**Comment by Ghost-chu** [comment]
> > Please test with https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/656/artifact/target/QuickShop.jar
> > I have replaced `Google Guava Cache` with `Caffeine`, it much faster.
> > Also, I have added some useful stats about caching pool in the Paste, please try it and feedback with the new Paste and Spark report.
> 
> Build doesn't even work, it doesn't let players buy. Says they don't have enough money when they do.

You need to execute `/qs paste` command to create a paste link and put it on there otherwise I can't help you.

**Comment by Ghost-chu** [comment]
> > Please test with https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/656/artifact/target/QuickShop.jar
> > I have replaced `Google Guava Cache` with `Caffeine`, it much faster.
> > Also, I have added some useful stats about caching pool in the Paste, please try it and feedback with the new Paste and Spark report.
> 
> Build doesn't even work, it doesn't let players buy. Says they don't have enough money when they do.

fixed in 4.0.7.2

**Comment by Ghost-chu** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/683/artifact/target/QuickShop-4.0.7.4.jar
try this one

**Comment by Ghost-chu** [comment]
Try this build: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/684/artifact/target/QuickShop.jar
With [BKCommonLib](https://www.spigotmc.org/resources/bkcommonlib.39590/), I have added a new wrapper to allow plugin use BKCommonLib fast util to improve the general and shop search performance. Try it :)

**Comment by Ghost-chu** [comment]
update: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/685/
also need BKCommonLib

**Comment by Ghost-chu** [comment]
Reopen this issue if it still appears on 4.0.7.4.
