### ISSUE TITLE
[BUG] This costs 10$ , you only have 400000$

### ISSUE THREAD

**Issue by JessePesse123** [Ghost-chu/QuickShop-Reremake#826]
**Describe the bug**
When purchasing it always says i dont enough money, eventhough i have alot. This is since the new update.

**To Reproduce**

**Expected behavior**
Buying the items
**Screenshots**

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.
 
- Error

**Additional context**

**Comment by Ghost-chu** [comment]
Please update to the latest version(4.0.7.0) and provide a valid paste link.
