### ISSUE TITLE
[BUG] woo:foo verbose debug at start-up.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#838]
QuickShop-Remake-SNAPSHOT dev 703

https://github.com/Ghost-chu/QuickShop-Reremake/commit/6ebacc3e5b1a87390eca77ffed12a9f8d90d5f80#diff-d036e4025d02746b1122c0150e0a9da893867bef3506eb3d45bd17edd0c3ffbdR152-R153

https://paste.gg/p/anonymous/5087f47ad6aa40848ee111fe3d7f355e/files/14e513bd6e674fc891ddc5849944e4cc/raw

**Comment by Ghost-chu** [comment]
it used for debugging so it will be removed when released.
