### ISSUE TITLE
Improve sql statement in checkColumns method

### ISSUE THREAD

**Issue by cloakfox** [Ghost-chu/QuickShop-Reremake#842]
Server bootup is hanging when quickshop needs to load. Really annoying.
https://pastebin.com/7yPQfUR0

Staring at that screen for 5+ minutes and nothing happening. So im not using quickshop for now.

Tried latest version, this was the result, fucking crashed the whole server.
https://pastebin.com/M3HPRdnE

**Comment by sandtechnology** [comment]
It should be the mysql server problem, we need to connect to database and load all the shops to prepare shop loading, and it stuck on receiving data from mysql server, try to use sqlite database instead and migrated data by this command:

> /qs convert [sqlite|mysql]
Convert your database to either sqlite or mysql.
This command is CONSOLE ONLY and first make sure to create a backup using /qs export!

**Comment by sandtechnology** [comment]
Emmmm....Look like it should be a performance issue, How many shops do you have?

**Comment by cloakfox** [comment]
I think it's an issue on my end, the SQL server is at max connections, would be helpfull if quickshop shows what it's doing during load up.

**Comment by Ghost-chu** [comment]
This caused by checking database tables is  ready but JDBC waiting for responsing from remote database.

But sadly JDBC (The Bukkit bundle lib for plugins to connect to SQL server) just hang it, QuickShop didn't know what's happening on server side and this is why no logs in this position during boot.

**Comment by Ghost-chu** [comment]
We're not recommend to use MySQL, It no help for performance on QuickShop but mau cause lagg or crash.
QS fetch all data from database to RAM when booting up. And write new data in async thread so faster query no helps for QS and it also will stop QuickShop built-in database backup.

**Comment by Ghost-chu** [comment]
Closed, QuickShop will show the details after try connect to database fails (3 times).
