### ISSUE TITLE
[Feature] /qs purchase <amount>

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Ghost-chu/QuickShop-Reremake#845]
**Describe the Feature**
/qs purchase <amount>
Would allow users to purchase items from a shop without needing to use chat. This would be useful because when players on my server are muted, they are unable to purchase from player shops. A command would allow them to purchase items when they are muted.

**Comment by Ghost-chu** [comment]
Try /qs amount <amount&gt;



---Original---

**Comment by WhatsTheBadNews** [comment]
This works! Thank you
