### ISSUE TITLE
Quickshop not working on 1.13

### ISSUE THREAD

**Issue by jordanwilliams1** [Ghost-chu/QuickShop-Reremake#85]
Qucikshop not working on 1.13.2 on the latest build on spigot, ALSO when i try to /lock a chest with lwc is just open's the chest...

I Get this error when trying to sell too..

https://i.gyazo.com/ade138e2791e057ebc799ebc453a4bf9.png

**Comment by StpNex** [comment]
I received this error aswell, it's probably the LWC compatibility that did not work.
