### ISSUE TITLE
[Feature] Signs design

### ISSUE THREAD

**Issue by ltei01** [Ghost-chu/QuickShop-Reremake#859]
### Describe the Feature:
I want a feature that the name from the seller get the color red or green. The name needs to be green if there is stock in the shop. But the name needs to turn red if the shop is empty. That would make it a lot easier to see if a shop is empty or not. 

### Screenshots:
![2021-03-03_21 01 35](https://user-images.githubusercontent.com/69518371/109865273-28527b00-7c64-11eb-934c-a441de541956.png)

### Additional context:
Also I would love it if it is possible to customize the sign design in the config. For example you can make the sign design with placeholders.

**Comment by Ghost-chu** [comment]
The sign support PlaceHolderAPI already

**Comment by ltei01** [comment]
But with placeholders I can't make it green or red when its out of stock?

**Comment by Ghost-chu** [comment]
messages.json find `signs.header` and replace with value `{1}{0}`.
Make sure you`r le using SNAPSHOT builds.



---Original---
From: ***@***.***&gt;
Date: Fri, May 7, 2021 22:44 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Ghost-chu/QuickShop-Reremake] [Feature] Signs design (#859)




 
But with placeholders I can't make it green or red when its out of stock?
