### ISSUE TITLE
[BUG] QS deletes messages.json without errors when changing "language-name" (Line: 30)

### ISSUE THREAD

**Issue by derMiepz** [Ghost-chu/QuickShop-Reremake#861]
### Describe the bug:
When translating the `messages.json` file and editing `"language-name": "en-US",` to something like `"language-name": "de-DE",` QS deletes the messages.json file when using /qs reload or when restarting the server.

### To Reproduce:
1. Open `messages.json`
2. Change `"language-name": "en-US",` to something else like `"language-name": "de-DE",`
3. Use /qs reload
4. Click on a sign or use some QS commands and check the `\plugins\QuickShop` folder to see that the file got removed

### Expected behavior:
QS should either revert the wrong line to the original one or should give an error in game and in console about the string being wrong

### Screenshots:
https://s.imparium.de/niho0/dUGogaPa52.mp4

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- https://pastebin.com/d6YV1ZR7

### Additional context:
There might be more strings that could cause this behavior. As the time of writing this, I didn't translate the whole file yet so I can't tell.

**Comment by sandtechnology** [comment]
I check that and found it won't delete, instead, it will create a backup file for it.
We use this name to check if is a right language we needed, and we also have a debug for noticing this.
I have add an warning in this snapshot, you can test it: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/835/

**Comment by derMiepz** [comment]
Seems like that fixed the issue! Thank you for your time! <3
