### ISSUE TITLE
Adminshops not adding or subracting money

### ISSUE THREAD

**Issue by stylinnile** [Ghost-chu/QuickShop-Reremake#87]
![image](https://user-images.githubusercontent.com/51105716/58449189-0c559900-80d0-11e9-9c48-f4a6e3840bcb.png)
Im running spigot 1.14(not 1.14.2) with vault 1.7.2, essentialsx 2.16.1.0 and quickshopreremake 1.4.2.13 
Whenever I create an adminshop or unlimited shop buying or selling from it doesnt add/subtract from my balance (see picture). Normal player shops work fine but its just the adminshops that arent working

Any help will be massively appreciated

**Comment by Ghost-chu** [comment]
AdminShop's owner still is you in database.
I mean you pay yourself money so your balance won't will change.

**Comment by vox4455** [comment]
So how do I /setowner to the server instead of a player in the database?

**Comment by kena73** [comment]
Bit late to the party but maybe have it written down somewhere that users will also have to do /qs setowner server ? Sorry if this has been documented and I just missed it.
