### ISSUE TITLE
[Feature] Ability to switch/customize left-click and right-click functions

### ISSUE THREAD

**Issue by VoltroXP** [Ghost-chu/QuickShop-Reremake#871]
### Describe the Feature:
Normally, a player has to left-click (punch) the shop's sign in order use it, and right-click to open up the shop control panel. But, most players (especially those not familiar with the plugin) tend to try to use the shops by right-clicking the signs instead of left-clicking. So, it would be nice if there was a way to customize or swap the functionality of left-clicking and right-clicking on shops. Plus, this could also work well with the already existing customization regarding sneak functions.

### Screenshots:
None

### Additional context:
None

**Comment by Ghost-chu** [comment]
added in 4.0.7.10
