### ISSUE TITLE
MySQL messages missing entries[BUG]

### ISSUE THREAD

**Issue by Bloodlex** [Ghost-chu/QuickShop-Reremake#873]
### Describe the bug:
MySQL table qs_messages doesn't show all the transactions. There are missing entries, that are present in a local file qs.log. It would be also beneficial to store the messages in better format with division into columns with item, price and so on, each value in its own column respectively.

### To Reproduce:
1. Enable MySQL.
2. Do some transactions.
3. There are missing transactions in mySQL database that are present in qs.log file

### Expected behavior:
I expect to have every transactions logged to qs_messages.

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- https://pastebin.com/3jyfeWhs

**Comment by sandtechnology** [comment]
The format of the messages is from the upstream, and could you reproduce this in SQLite mode?

**Comment by Bloodlex** [comment]
> The format of the messages is from the upstream, and could you reproduce this in SQLite mode?

I don't have server running on SQLite at the moment, I've noticed it when starting to use MySQL, because I would like to extract data from there. 

It would be really nice to reformat this messages before it hits MySQL.

**Comment by Starmism** [comment]
I have some moderate knowledge of SQL and database design, I can look into this soon and see if I can refactor our database schema! My thoughts on things not showing up in the database would be that they are still asynchronously queueing and haven't yet been applied but in the plugin's internal state they already have, hence why they're in the logs.

**Comment by Bloodlex** [comment]
@Starmism Thank you very much! Would be really nice to have everything logged in there and also easy to fetch from a database! 👍 🙂
