### ISSUE TITLE
[BUG] Can't use shops in adventure mode.

### ISSUE THREAD

**Issue by VoltroXP** [Ghost-chu/QuickShop-Reremake#875]
### Describe the bug:
While in adventure mode, you cant use shops since you need to left-click/punch them. However, right-clicking shop signs still works, so I would think a similar way of detecting player input could be used for left-clicking.

### To Reproduce:
1. Create a shop
2. Go into adventure mode
3. Left-click on sign to buy from it
4. Doesn't work

### Expected behavior:
I expected to be able to purchase from shops while in adventure mode.

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- https://pastebin.com/knsStKaP

### Additional context:
This bug also kind of plays in to another request I made here to add the ability to switch/customize left-click and right-click functions.

**Comment by Ghost-chu** [comment]
Seems the server doesn't handle the sign-click event under adventure event.

**Comment by VoltroXP** [comment]
If this could be fixed, I could change the gamemode of my spawn world to adventure mode, which would allow for things like barriers to not show up. But, because of this, and not being able to change the left-blick or right-click functions, I can't change the world to adventure mode since then nobody could use the shop.

**Comment by Ghost-chu** [comment]
sadly it looks is client behavor, i'm not sure how to resolve this issue.

**Comment by VoltroXP** [comment]
Then could you add my other feature request so the left-click and right-click functions could be changed or at least swapped? The problem with the interaction in adventure mode only seems to occur for left-clicking due to that being associated with breaking. So, if the buttons could be swapped or changed, that should allow players to purchase from the shops while in adventure mode.

**Comment by Ghost-chu** [comment]
right-click is hardcode to pop up control panel.
maybe @sandtechnology

**Comment by Ghost-chu** [comment]
Try this build: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/909/
Added Adventure Gamemode support (little hacky) and swap LEFT*RIGHT ability.

**Comment by Ghost-chu** [comment]
Closed due impled
