### ISSUE TITLE
Display Item show name config option doesn't work

### ISSUE THREAD

**Issue by deadman96385** [Ghost-chu/QuickShop-Reremake#88]
I am on 1.14.2 paperspigot, the floating blocks above the chest show up as well as the hologram. But in the config display-item-show-name is set to false which I think entails that the hologram shouldn't be enabled.

**Comment by Ghost-chu** [comment]
QuickShop never manage Item's hologram and QuickShop not have the Hologram feature, so i think this is another plugin's issue.

You should feedback to that plugin not QuickShop.

**Comment by deadman96385** [comment]
Ah now that you say that, it makes sense I have a plugin called Holodrop which enables a title on dropped items. I guess your plugin spawns a dropped item that is persistent.

**Comment by Ghost-chu** [comment]
> Ah now that you say that, it makes sense I have a plugin called Holodrop which enables a title on dropped items. I guess your plugin spawns a dropped item that is persistent.

Yes, you are right.
You should contact plugin's author solve this problem, quickshop have api to allow other plugin check the item is or not the shop's display-item
