### ISSUE TITLE
[BUG]某些情况下预览会报错

### ISSUE THREAD

**Issue by CirnoTH** [Ghost-chu/QuickShop-Reremake#882]
### Describe the bug:
某些情况下预览会报错, 详见日志

### To Reproduce:
idk, 似乎某些情况下预览就会出现这个问题

### Expected behavior:
没有报错

### Screenshots:
报错日志如下:
https://paste.ubuntu.com/p/FdSYcVYBmV/

### Paste link:
 Execute command `/qs paste`, and you will get a link contains your server information, paste it under this text.  
 **You must create a paste, except plugin completely won't work.**  
 If you create failed, you should find a paste file under the `plugins/QuickShop` folder.
- 如果需要可通过dc或qq联系我

**Comment by Ghost-chu** [comment]
This is a server bug, please report it to the server software developer.
