### ISSUE TITLE
SuperiorSyblock2 Integration

### ISSUE THREAD

**Issue by KickSquareMC** [Ghost-chu/QuickShop-Reremake#890]
Hello, I'd like to suggest a simple superiorskyblock feature suggestion. Superiorskyblock2 is the most feature-rich and optimized skyblock core on the market. Here's the 2 things I would suggest:
1) Players can only place quickshops on their island
2) quickshops get deleted when islands get deleted

Useful links:
[https://bg-software.com/api-docs/superiorskyblock/](url)
[https://wiki.bg-software.com/#/superiorskyblock/api/](url)
[https://github.com/OmerBenGera/SuperiorSkyblock2/](url)

**Comment by Ghost-chu** [comment]
The issue has been closed because we cannot access their wiki page(404)

**Comment by Ghost-chu** [comment]
added
