### ISSUE TITLE
[Feature] Command to display buying shops

### ISSUE THREAD

**Issue by adennkal** [Ghost-chu/QuickShop-Reremake#891]
### Describe the Feature:
A command working similar to /qs find, allowing users to display all shops near them that buy items. 

### Additional context:
In our case we have multiple areas with a large amount of shops close to each other, making combing through them to find ones that one could sell items to very tedious. This feature would allow users to quickly get an overview over what items are currently being bought and where.

**Comment by Ghost-chu** [comment]
I think find command enough, reopen this ticket if still want it.
