### ISSUE TITLE
1.4.4 Task #48 for QuickShop vReremake 1.4.4 generated an exception

### ISSUE THREAD

**Issue by kaniesha** [Ghost-chu/QuickShop-Reremake#91]
I just updated to version 1.4.4 and the console showed this error about 15-20 times. Here's one of them: https://gist.github.com/kaniesha/d0330ddd76fc7bd4c41eb2a3c85a3843

Server running 1.14.2 via git-Spigot-093165d-ba575a5  ver 1.14.2-R0.1-SNAPSHOT
Full log attached:
[2019-05-31-latest1.log](https://github.com/Ghost-chu/QuickShop-Reremake/files/3242094/2019-05-31-latest1.log)

**Comment by Ghost-chu** [comment]
It looks might spigot's fault, but i will try fix it.

**Comment by kaniesha** [comment]
I honestly believe you, as the spigot version is an early release. Just making rounds of bug reports in case plugin devs can help.

**Comment by Ghost-chu** [comment]
I got a trouble with network, our country firewall banned protocols, i can't push code to github and start builds.

Sorry for delay!

**Comment by kaniesha** [comment]
It's alright! Thank you for working hard!

**Comment by kaniesha** [comment]
Updated to 1.4.4.3 just now, similar error: https://gist.github.com/kaniesha/9cb0b1797790a28925c32abce87d5de1

**Comment by kaniesha** [comment]
[QuickShop] Task #46 for QuickShop vReremake 1.4.4.3 generated an exception

https://gist.github.com/kaniesha/bd1c1b3057ccf183b39b4cad166916d3

**Comment by Ghost-chu** [comment]
It looks is Spigot's issue, update spigot build version and tryagain.

If still have exception, give me /qs paste and i will try feedback to spigot
