### ISSUE TITLE
[BUG] Remove command description if the player does not have permission

### ISSUE THREAD

**Issue by SrBedrock** [Ghost-chu/QuickShop-Reremake#910]
### Describe the bug:

Players without permission for `/qs removeall`, `/qs info` and `/qs about` can see the command with `/qs help`

### To Reproduce:

1. Remove `quickshop.removeall`, `quickshop.removeall.self`, `quickshop.removeall.others`, `quickshop.about` and `quickshop.about` from players.

2. Use `/qs help`

### Expected behavior:
Players do not see command descriptions that they do not have permission.

### Screenshots:

![image](https://user-images.githubusercontent.com/51332006/114658171-be4bdd80-9cc7-11eb-85cc-bf04d8dc7511.png)

**Comment by Ghost-chu** [comment]
We won't show no command help/tabcomplete if player had no permissions.
Cannot reproduce this issue on test server, check your permission configuration.

To troubleshooting permissions issue, you can use /qs debug to enable debug logger and see permissions verbose.

**Comment by SrBedrock** [comment]
I performed the test after activating the debug with `/qs debug`

QuickShop version: 4.0.7.10
LuckPerms version: 5.3.21

Permission check by LuckPerms:
- quickshop.removeall: https://gist.github.com/SrBedrock/2ed5ff533f493cca6ef9ac18d44b98e7
- quickshop.removeall.self: https://gist.github.com/SrBedrock/90408b44b91072f8940c0864858bfe6e
- quickshop.removeall.other: https://gist.github.com/SrBedrock/d58782f0d6dc8e3b87463f54d485b18c


Player Koyote using the `/qs about`:
- QS Debug Link: https://gist.github.com/SrBedrock/ddeacf7644ab109bb5fe768ce399c7a5
- Image: https://i.imgur.com/k5J0jFA.png

Player Koyote using the `/qs removeall`:
- QS Debug Link: https://gist.github.com/SrBedrock/319ca5b55ba2db63a4bff4fa5ce994a0
- Error: `"no-owner-given": "&cNo owner provided"`

Player Koyote using the `/qs removeall Koyote`:
- QS Debug Link: https://gist.github.com/SrBedrock/60ab5a7f3dbfa68fa739727bbcd71a8f
- Error: `"no-permission": "&cYou do not have permission to do that."`
- **Some calculation is performed because the error takes a long time to return. (lag server)**
- Image: https://i.imgur.com/kktoEw3.png
- Spark Link: https://spark.lucko.me/UkdlDUxtcA

Player Koyote using the `/qs removeall ThiagoROX`:
- QS Debug Link: https://gist.github.com/SrBedrock/96acf4390bd213e118f09935c83c7045
- Error: `"no-permission": "&cYou do not have permission to do that."`
- **Some calculation is performed because the error takes a long time to return. (lag server)**
- Spark Link: https://spark.lucko.me/VcbgD3TwFg

**Comment by SrBedrock** [comment]
New server with:

![image](https://user-images.githubusercontent.com/51332006/114681547-a3d42d00-9ce4-11eb-8e75-0bb4ad747410.png)
***
Command `/qs`:

![image](https://user-images.githubusercontent.com/51332006/114681666-c23a2880-9ce4-11eb-9fb2-b183b9a30b16.png)
***
TabComplete `/qs remove...`:

![image](https://user-images.githubusercontent.com/51332006/114681799-de3dca00-9ce4-11eb-9f21-c5b85fb53a42.png)
***
Command `/qs removeall`:

![image](https://user-images.githubusercontent.com/51332006/114681930-fe6d8900-9ce4-11eb-91ca-924203c3757b.png)
***
TabComplete `/qs removeall ...`:

![image](https://user-images.githubusercontent.com/51332006/114682064-20670b80-9ce5-11eb-8fa8-c53ae596d01e.png)
***
Command `/qs removeall ThiagoROX`:

![image](https://user-images.githubusercontent.com/51332006/114682032-18a76700-9ce5-11eb-987c-2fc1bb3b8e56.png)
***

**Comment by Ghost-chu** [comment]
/qs removeall
and
/qs removeall <player&gt;
is two different command.



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 14, 2021 16:51 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Ghost-chu/QuickShop-Reremake] [BUG] Remove command description if the player does not have permission (#910)




 
New server with:
 

 
 
Command /qs:
 

 
 
TabComplete /qs remove...:
 

 
 
Command /qs removeall:
 

 
 
TabComplete /qs removeall ...:
 

 
 
Command /qs removeall ThiagoROX:

**Comment by Ghost-chu** [comment]
Please provide link created by command /qs paste

**Comment by Ghost-chu** [comment]
Yes, /qs reload will cause server lag because it will unload and load again plugin self to reloading.

**Comment by Ghost-chu** [comment]
also we recommend get support through our discord server because this issue seems too complex.

**Comment by SrBedrock** [comment]
I contacted via discord and my problem will be solved, thanks
