### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wafumoon** [Ghost-chu/QuickShop-Reremake#913]
### Describe the bug:
if player make shop with itemstack >64 then icon of item disappear

### To Reproduce:
1. add something to custom-item-stacksize:
2. make shop with this item with stack >64
3. congratulations! You did it!

### Expected behavior:
Fix it please.

### Screenshots:
![2021-04-15_18 05 24](https://user-images.githubusercontent.com/52106020/114892268-468bc900-9e15-11eb-9677-bfc6c65c239f.png)
![2021-04-15_18 05 26](https://user-images.githubusercontent.com/52106020/114892277-48558c80-9e15-11eb-8b8f-29f32ac040bf.png)

### Paste link:
- https://paste.ubuntu.com/p/BHQ7y6s2F6/

**Comment by sandtechnology** [comment]
Please download the latest version, we have fix this issue: https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-multi-currency.62575/download?version=396410
