### ISSUE TITLE
[Feature] worldedit copy/paste support

### ISSUE THREAD

**Issue by BackSam6348** [Ghost-chu/QuickShop-Reremake#922]
### Describe the Feature: When using the //copy and //paste commands in the WorldEdit Plugin, it would be nice to transfer the entire store data. Currently, it is not completely relocated. 
A clear and concise description of what the feature is.

### Screenshots:
If applicable, add screenshots to help explain your feature.
Leave this section body empty if no screenshots provided.

### Additional context: 
Add any other context about the feature here.
Leave this section body empty if no additional context provided.

**Comment by Ghost-chu** [comment]
Sadly, WorldEdit no events to let our plugin know player copy/paste something, so this is impossible.
