### ISSUE TITLE
Decimal digits like 0.00001 not working

### ISSUE THREAD

**Issue by EfexTo** [Ghost-chu/QuickShop-Reremake#925]
### Describe the bug:
Even by enabling the decimal format and **adding more 0** than 0.01 when I try to sell in the shop an object for 0.00001 **(EXAMPLE)** it gives me **1.0E-4**

### To Reproduce:
1. Just make a shop with the cost of **<0.01**

### Expected behavior:
I would like to sell without any issues items for numbers like **0.00025**

**Comment by sandtechnology** [comment]
It just a document issue, if you enable decimal format, you should also enable `disable-vault-format` and configure `alternate-currency-symbol`, because it need to use QS internal format.
