### ISSUE TITLE
Creating and change price cost money, no matter what.

### ISSUE THREAD

**Issue by Outcahst** [Ghost-chu/QuickShop-Reremake#93]
I have both restarted my server and reloaded QuickShop but this issue remains. Despite my settings in the config, players are still charged for creating a shop and changing its price. This was with 1.1.4, so I also tried getting the latest version (1.1.4.3) but this issue persists.
Also, despite being both costs being set to 0, it charges their default values (10 and 50).

Config:
`
shop:
    #Cost to make a stall
    cost: 0
    #Should we refund when their shops are deleted/removed/broken?
    refund: false

    #Is there a fee for changing prices on a shop (Help deter endless undercutting)
    price-change-requires-fee: false
    #If price changes require a fee, how much is the fee
    fee-for-price-change: 0
`

**Comment by Ghost-chu** [comment]
I will check that later, thanks feedback

**Comment by Ghost-chu** [comment]
Unable to reproduce

**Comment by Outcahst** [comment]
> Unable to reproduce

Would a video help you, or are you just dropping this?

**Comment by Outcahst** [comment]
My bad, just installed 1.1.4.4 which wasn't released at the time of the issue. This is fixed with the latest version, though. Thanks!
