### ISSUE TITLE
[Feature] Permission max shops

### ISSUE THREAD

**Issue by ltei01** [Ghost-chu/QuickShop-Reremake#934]
### Describe the Feature:
My request is really simple. I wonder if its possible to add the option that you can set the shop limit for a player with a permission. So as an example quickshop.shops.9

**Comment by Ghost-chu** [comment]
QuickShop rank limit feature allows you to control how many shops players can create.


For example:
limits:
&nbsp; use: true
&nbsp; default: 10
&nbsp; old-algorithm: false
&nbsp; ranks:
&nbsp; &nbsp; quickshop:
&nbsp; &nbsp; &nbsp; vip: 20
&nbsp; &nbsp; bar:
&nbsp; &nbsp; &nbsp; foo: 40


In this configuration, the player has permission quickshop.vip can create 20 shops, or player has permission bar.foo can create 40 shops.


Closed #934



---Original---
From: ***@***.***&gt;
Date: Fri, May 7, 2021 22:43 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Ghost-chu/QuickShop-Reremake] [Feature] Permission max shops (#934)




 
Describe the Feature:
 
My request is really simple. I wonder if its possible to add the option that you can set the shop limit for a player with a permission. So as an example quickshop.shops.9
 
Screenshots:
 
Additional context:

**Comment by Ghost-chu** [comment]
QuickShop rank limit feature allows you to control how many shops players can create.

For example:
limits:
  use: true
  default: 10
  old-algorithm: false
  ranks:
    quickshop:
      vip: 20
    bar:
      foo: 40

In this configuration, the player has permission quickshop.vip can create 20 shops, or player has permission bar.foo can create 40 shops.
