### ISSUE TITLE
[Feature] Display "Out of Stock" or "Out of Space" instead of "Selling/Buying 0"

### ISSUE THREAD

**Issue by Andre601** [Ghost-chu/QuickShop-Reremake#939]
### Describe the Feature:
The second line that usually displays `Selling <number>` or `Buying <number>` should display `Out of Stock` in Sell and `Out of Space` in Buy-Mode when the shop doesn't have any items to sell or no more space to buy items respectively.

### Additional context:

**Comment by Ghost-chu** [comment]
done
