### ISSUE TITLE
No 'stacktrace.app.packages

### ISSUE THREAD

**Issue by farmermoonshine** [Ghost-chu/QuickShop-Reremake#96]
[QuickShop]: Enabling QuickShop vReremake 1.4.4.8
[QuickShop]: Quickshop Reremake
[QuickShop]: Author:Ghost_chu
[QuickShop]: Original author:Netherfoam, Timtower, KaiNoMood
[QuickShop]: Let's us start load plugin
[QuickShop]: Translator: Ghost_chu
[QuickShop]: Contributors: Timtower, Netherfoam, KaiNoMood and Mgazul
[QuickShop]: Language Zone: English (en_US)
[QuickShop]: Support Version: Reremake
[QuickShop]: bStats module loaded.
WARN 04/06/2019 10:29:03
10:29:03[io.sentry.DefaultSentryClientFactory]: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
[io.sentry.DefaultSentryClientFactory]: No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
INFO 04/06/2019 10:29:03
10:29:03[QuickShop]: Complete to load Itemname i18n.
[QuickShop]: Starting loading Enchantment i18n...
[QuickShop]: Complete to load enchname i18n.
[QuickShop]: Starting loading Potion i18n...
[QuickShop]: Complete to load potionname i18n.
[QuickShop]: Limit cfg found...
[QuickShop]: Limits.use: false
[QuickShop]: Loading shops from database...
[QuickShop]: Used 1ms to fetch all shops from database.
[QuickShop]: Successfully loaded 0 shops! (Used 1ms, Avg 0ms per shop)
[QuickShop]: 0 shops will load after chunk loaded, 0 shops will load after world loaded.
[QuickShop]: Registering Listeners
[QuickShop]: Cleaning purchase messages from database that are over a week old...
[QuickShop]: Posting stats data...
[QuickShop]: Metrics submited.
[QuickShop]: QuickShop loaded!

**Comment by Ghost-chu** [comment]
1.4.4.10 already comed out dude
