### ISSUE TITLE
[BUG]Cannot sneaking to create shops

### ISSUE THREAD

**Issue by shuiqing2046** [Ghost-chu/QuickShop-Reremake#984]
Describe the bug:
Cannot sneaking to create shops
无法潜行创建商店

To Reproduce:
服务器版本1.16.5 无任何相关报错,除潜行创建商店功能无效外未发现其它问题.

`  interact:
    sneak-to-create: true`

/qs paste:
https://paste.ubuntu.com/p/jrd4m43rwn/

**Comment by sandtechnology** [comment]
Please change `interact-mode` to 0 to fix it

**Comment by shuiqing2046** [comment]
改了个sneak-to-control: true 重载错误
https://paste.ubuntu.com/p/wkjNBpWfnB/

**Comment by sandtechnology** [comment]
We are NOT SUPPORT reloading after running update command to update or manually replace plugin jar, considering restart the server.

**Comment by Ghost-chu** [comment]
> We are NOT SUPPORT reloading after running update command to update or manually replace plugin jar, considering restart the server.

I can reproduce `/qs reload` broken in recent updates
