### ISSUE TITLE
Extra event after a successful purchase

### ISSUE THREAD

**Issue by LJack2k** [Ghost-chu/QuickShop-Reremake#99]
At this moment in the ShopManager.class the event ShopPurchaseEvent gets fired before the actual purchase has been handled. This is indeed correct so other plugins can do its thing and cancel it if needed. However since purchase could fail after it (money/economy issues) it would be very handy to have a event that gets fired after a successful purchase event, let's call it ShopSuccesfullPurchaseEvent. It can have the same properties as the current one, but plugins that listen are sure that the purchase was indeed successful.

I would like to have 2 extra getter tho. getTaxed() which contains the amount that has been taxed and getTax() which is the tax setting from the config that has been used to calculate the total cost tax.

If I'm doing something totaly wrong with these events, please let me know. I'm in your Discord incase you want to message me with @LJack2k#8949.

**Comment by Ghost-chu** [comment]
Thanks your advice, we will think about it when v2.0 refactoring.

**Comment by Ghost-chu** [comment]
Added in latest snapshot, ShopSuccessPurchaseEvent
